# 📋 РУКОВОДСТВО ПО ИСПОЛЬЗОВАНИЮ ШАБЛОНА

## Просмотр результатов

**Ноутбук уже выполнен.** Все графики и выводы видны сразу при открытии на GitHub.

### Источник данных:

**Датасет:** Stroke Prediction Dataset  
**Источник:** [Kaggle - Stroke Prediction Dataset](https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset)

Навигация: [REDMI.md](https://github.com/vokoder1990/ml_practic/blob/main/stroke-prediction/REDMI.md)

Итоги анализа датасета: [ANALYSIS_REPORT.md](https://github.com/vokoder1990/ml_practic/blob/main/stroke-prediction/ANALYSIS_REPORT.md)


##  ОСНОВНЫЕ НАСТРОЙКИ [(блок 1.3)](#scrollTo=gsHs-qXFxVsG)

###  Обязательные

| Переменная | Описание | Пример |
|------------|----------|--------|
| `PROJECT_NAME` | Имя папки проекта (без пробелов и `cycle_`) | `'stroke'` |
| `CYCLE_NUMBER` | Номер цикла эксперимента (целое число ≥1) | `4` |
| `TARGET_COLUMN` | Целевая переменная | `'stroke'` |

###  Загрузка данных

| Переменная | Описание | Пример |
|------------|----------|--------|
| `LOAD_MODE` | `'drive'` - Google Drive, `'local'` - локальный файл | `'drive'` |
| `FILE_ID` | ID файла на Google Drive (при `LOAD_MODE='drive'`) | `'1Jsq2V0lFfB...'` |
| `LOCAL_DATA_PATH` | Путь к файлу (при `LOAD_MODE='local'`) | `'/content/data.csv'` |

###  Типы колонок (приведение)

| Переменная | Описание | Пример |
|------------|----------|--------|
| `date_columns` | Колонки с датами → `datetime` | `[]` |
| `int_columns` | Целочисленные колонки → `Int64` (с поддержкой NaN) | `['hypertension', 'heart_disease']` |
| `float_columns` | Вещественные колонки → `float64` | `['age', 'avg_glucose_level', 'bmi']` |
| `categorical_columns` | Категориальные → `string` (кодирование в EDA) | `['gender', 'work_type']` |
| `text_columns` | Текстовые колонки → `strip() + lower()` | `[]` |
| `columns_to_drop` | Полное удаление колонок | `['id']` |

###  Разбиение выборок

| Переменная | Описание | Значение по умолчанию |
|------------|----------|----------------------|
| `SPLIT_TRAIN_SIZE` | Доля train выборки | `0.60` |
| `SPLIT_VAL_SIZE` | Доля validation выборки | `0.20` |
| `SPLIT_TEST_SIZE` | Доля test выборки | `0.20` |
| `RANDOM_STATE` | Seed для воспроизводимости | `99` |

###  Очистка и фильтрация

| Переменная | Описание | Значение по умолчанию |
|------------|----------|----------------------|
| `DROP_ROWS_WITH_NULLS` | Удалять строки с NaN (лучше оставить False, обработка в EDA) | `False` |
| `NUMERIC_RANGES` | Допустимые диапазоны для числовых колонок | `{'age':(1,82), 'bmi':(10,60), 'avg_glucose_level':(50,300)}` |
| `DROP_OUT_OF_RANGE` | Удалять значения вне `NUMERIC_RANGES` | `True` |
| `OUTLIER_IQR_COEFF` | Коэффициент для IQR (только анализ, не удаление) | `1.5` |
| `DROP_RARE_CATEGORIES` | Удалять редкие категории (включая редкий NaN) | `True` |
| `RARE_CATEGORY_THRESHOLD` | Доля < порога → редкая категория | `0.01` (1%) |
| `COLUMNS_TO_CHECK_RARE` | Какие колонки проверять на редкость | `['gender']` |
| `RARE_CATEGORIES_TO_KEEP` | Редкие категории, которые НЕ удалять | `[]` |
| `SUSPICIOUS_VALUES` | Маркеры пропусков для поиска (анализ) | `[-1, -999, 999, 9999]` |

###  Анализ (только вывод, без изменений)

| Переменная | Описание | Значение по умолчанию |
|------------|----------|----------------------|
| `LOW_CARDINALITY_THRESHOLD` | Порог для подсказки categorical_columns | `20` |
| `FORCE_TASK_TYPE` | Принудительный тип задачи (`''`, `'classification'`, `'regression'`) | `''` |

---

## 📁 СТРУКТУРА

<pre>
📁 {PROJECT_NAME}/
└── 📁 cycle_{CYCLE_NUMBER}/
    └── 📁 preprocessing/
        ├── 📁 checkpoints/
        │   ├── 📄 00_raw.csv
        │   ├── 📄 01_structure.csv
        │   └── 📄 02_cleaned.csv
        ├── 📁 splits/
        │   ├── 📄 X_train.csv
        │   ├── 📄 X_val.csv
        │   ├── 📄 X_test.csv
        │   ├── 📄 y_train.csv
        │   ├── 📄 y_val.csv
        │   └── 📄 y_test.csv
        ├── 📁 reports/
        │   └── 📄 preprocessing_report.txt   # единый отчёт
        └── 📄 metadata.json
</pre>

## 📋 СОДЕРЖАНИЕ METADATA.JSON

Файл `metadata.json` сохраняется в корень `preprocessing/` и содержит всю информацию, необходимую для EDA и Modeling ноутбуков.

```json
{
  "project_name": "stroke",
  "cycle_number": 4,
  "target_column": "stroke",
  "task_type": "classification",
  "feature_names": ["gender", "age", "hypertension", ...],
  "feature_count": 19,
  "train_size": 3400,
  "val_size": 850,
  "test_size": 850,
  "total_size": 5100,
  "split_ratio": {
    "train": 0.6,
    "val": 0.2,
    "test": 0.2
  },
  "random_state": 99,
  "date_processed": "2026-04-28 15:30:00",
  "has_missing_values": true,
  "classes": ["0", "1"],
  "class_count": 2,
  "train_class_distribution": {"0": 3000, "1": 400},
  "package_versions": {
    "python": "3.10.12",
    "pandas": "2.0.3",
    "numpy": "1.25.2",
    "scikit-learn": "1.2.2",
    "statsmodels": "0.14.0"
  },
  "data_contract": {
    "version": "1.0",
    "description": "Контракт между preprocessing и EDA",
    "X_train": {
      "file": "X_train.csv",
      "format": "csv",
      "shape": [3400, 19]
    },
    "y_train": {
      "file": "y_train.csv",
      "dtype": "int64"
    },
    "guaranteed_columns": ["gender", "age", "hypertension", ...],
    "categorical_columns_hint": ["gender", "work_type"],
    "numerical_columns_hint": ["age", "bmi", "avg_glucose_level"],
    "target_column": "stroke"
  }
}
```

---
✅ **После завершения предобработки** переходим в ноутбук **EDA**

# СТРУКТУРА ШАБЛОНА ПРЕДОБРАБОТКИ ДАННЫХ

**Версия 9.1** (с изоляцией циклов)

---

## ЧАСТЬ 1: НАСТРОЙКА И ЗАГРУЗКА

| Блок | Название |
|------|----------|
| 1.1 | Загрузка библиотек |
| 1.2 | Служебные функции проверки |
| 1.3 | Настройки проекта (менять под задачу) |
| 1.4 | Монтирование Google Drive |
| 1.5 | Загрузка данных |
| 1.6 | Настройка путей проекта |
| 1.7 | Сохранение исходных данных |

---

## ЧАСТЬ 2: ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ

| Блок | Название |
|------|----------|
| 2.1 | Базовый осмотр данных |
| 2.2 | Дополнительные проверки и поиск аномалий |

---

## ЧАСТЬ 3: ПРЕДОБРАБОТКА ДАННЫХ

| Блок | Название |
|------|----------|
| 3.1 | Переименование колонок |
| 3.2 | Приведение типов данных |
| 3.3 | Удаление ненужных колонок |
| 3.4 | Обработка аномалий (пропуски, диапазоны, редкие категории) |
| 3.5 | Сохранение контрольной точки |

---

## ЧАСТЬ 4: ОЧИСТКА И ФИНАЛИЗАЦИЯ

| Блок | Название |
|------|----------|
| 4.1 | Механическая очистка текста и категорий |
| 4.2 | Сохранение контрольной точки |

---

## ЧАСТЬ 5: РАЗДЕЛЕНИЕ ДАННЫХ

| Блок | Название |
|------|----------|
| 5.1 | Подготовка к разделению (создание X и y) |
| 5.2 | Разделение на train/val/test |

---

## ЧАСТЬ 6: АНАЛИЗ TRAIN ВЫБОРКИ

| Блок | Название |
|------|----------|
| 6.1 | Проверка на выбросы (IQR) |
| 6.2 | Корреляция числовых признаков |
| 6.3 | Проверка на мультиколлинеарность (VIF) |
| 6.4 | Рекомендации по кодированию категориальных признаков |
| 6.5 | Проверка на константные и низковариативные признаки |

---

## ЧАСТЬ 7: СОХРАНЕНИЕ И ФИНАЛИЗАЦИЯ

| Блок | Название |
|------|----------|
| 7.1 | Сохранение выборок, метаданных и единого отчёта |
| 7.2 | Финальная валидация сплитов (защита от багов) |

---

## КОНТРОЛЬНЫЕ ТОЧКИ (папка `checkpoints/`)

| Файл | Описание |
|------|----------|
| `00_raw.csv` | Исходные данные |
| `01_structure.csv` | После типов и удаления колонок |
| `02_cleaned.csv` | После механической очистки |

---

## РЕЗУЛЬТАТЫ

**Папка `splits/` (внутри `cycle_N/preprocessing/`):**
- `X_train.csv`, `X_val.csv`, `X_test.csv`
- `y_train.csv`, `y_val.csv`, `y_test.csv`

**Папка `reports/` (внутри `cycle_N/preprocessing/`):**
- `preprocessing_report.txt` - единый отчёт

**Корень `preprocessing/` (внутри `cycle_N/preprocessing/`):**
- `metadata.json` - метаданные для EDA и modeling

**Папка `checkpoints/` (внутри `cycle_N/preprocessing/`):**
- `00_raw.csv`, `01_structure.csv`, `02_cleaned.csv`

# БЛОК 1. import библиотек

In [ ]:
# 1.1 ЗАГРУЗКА БИБЛИОТЕК

import pandas as pd
import numpy as np
import os
import sys
import json
import warnings
import sklearn
from datetime import datetime
from sklearn.model_selection import train_test_split
from IPython.display import display
import shutil

# Настройка отображения
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
warnings.filterwarnings('ignore')

# Определение окружения (Colab или локально)
try:
    from google.colab import drive
    IN_COLAB = True
    print("✓ Среда выполнения: Google Colab")
except ImportError:
    IN_COLAB = False
    print("✓ Среда выполнения: локальная / Kaggle")

# Установка недостающих пакетов (с обработкой ошибок)
def install_if_missing(package_name):
    """
    Проверяет, установлен ли пакет. Если нет, пытается установить.
    При ошибке установки выдаёт понятное сообщение и продолжает работу.
    """
    try:
        __import__(package_name)
        print(f"✓ {package_name} уже установлен")
        return True
    except ImportError:
        print(f"📦 Установка {package_name}...")
        try:
            # Пытаемся установить через pip
            result = os.system(f'{sys.executable} -m pip install {package_name} --quiet')
            if result == 0:
                print(f"   ✓ {package_name} установлен")
                return True
            else:
                print(f"   ⚠️ Ошибка установки {package_name} (код {result})")
                print(f"   💡 Возможно, нет прав или интернета. Установите вручную:")
                print(f"      pip install {package_name}")
                return False
        except Exception as e:
            print(f"   ⚠️ Ошибка установки {package_name}: {e}")
            print(f"   💡 Установите вручную: pip install {package_name}")
            return False

# Устанавливаем statsmodels
install_if_missing('statsmodels')

# Автоопределение версий для воспроизводимости
def print_versions():
    print("\n📦 Версии пакетов:")
    print(f"   Python: {sys.version.split()[0]}")
    print(f"   pandas: {pd.__version__}")
    print(f"   numpy: {np.__version__}")
    print(f"   scikit-learn: {sklearn.__version__}")

    try:
        import statsmodels
        print(f"   statsmodels: {statsmodels.__version__}")
    except ImportError:
        pass

print_versions()

✓ Среда выполнения: Google Colab
✓ statsmodels уже установлен

📦 Версии пакетов:
   Python: 3.12.13
   pandas: 2.2.2
   numpy: 2.0.2
   scikit-learn: 1.6.1
   statsmodels: 0.14.6

In [ ]:
# 1.2 СЛУЖЕБНЫЕ ФУНКЦИИ ПРОВЕРКИ ДАННЫХ

def is_split_ready(df, X, TARGET_COLUMN):
    """
    Проверяет готовность данных перед разделением на X и y
    """
    if df is None:
        print("   ⚠️ Пропускаем: данные не загружены")
        return False

    if not TARGET_COLUMN:
        print("   ⚠️ Пропускаем: TARGET_COLUMN не указан (задайте в блоке 3)")
        return False

    if TARGET_COLUMN not in df.columns:
        print(f"   ⚠️ Пропускаем: колонка '{TARGET_COLUMN}' не найдена в данных")
        return False

    if X is None:
        print("   ⚠️ Пропускаем: X = None (признаки не созданы)")
        return False

    if len(X) == 0:
        print("   ⚠️ Пропускаем: X пуст (0 признаков)")
        return False

    # Дополнительная проверка: X и df должны быть согласованы
    if len(X) != len(df):
        print(f"   ⚠️ Пропускаем: размеры не совпадают X={len(X)}, df={len(df)}")
        print(f"      Возможно, X создан из другого датафрейма")
        return False

    return True


def is_train_ready(X_train, y_train=None):
    """
    Проверяет готовность train-данных
    """
    if X_train is None:
        print("   ⚠️ Пропускаем: X_train = None")
        return False
    if len(X_train) == 0:
        print("   ⚠️ Пропускаем: X_train пуст (0 объектов)")
        return False
    if y_train is not None:
        if len(y_train) == 0:
            print("   ⚠️ Пропускаем: y_train пуст (0 объектов)")
            return False
        if len(X_train) != len(y_train):
            print(f"   ⚠️ Пропускаем: размеры не совпадают X_train={len(X_train)}, y_train={len(y_train)}")
            return False
    return True


def convert_to_serializable(obj):
    """
    Рекурсивно конвертирует numpy/pandas-типы в Python-типы для JSON-сериализации
    """
    if isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    elif isinstance(obj, np.bool_):
        return bool(obj)
    elif isinstance(obj, pd.Timestamp):
        return str(obj)
    elif isinstance(obj, (list, tuple)):
        return [convert_to_serializable(item) for item in obj]
    elif isinstance(obj, dict):
        return {key: convert_to_serializable(value) for key, value in obj.items()}
    else:
        return obj

# Настройки проекта

In [ ]:
# 1.3 НАСТРОЙКИ ПРОЕКТА (менять под каждую задачу)

# --------------------------------------------
# 1. ЗАГРУЗКА ДАННЫХ
# --------------------------------------------
LOAD_MODE = 'drive'     # 'drive' (Google Drive) или 'local' (локальный файл)
FILE_ID = '1Jsq2V0lFfBurcSZm-fQUJXRB9nUWsG_I'  # ID файла на Google Drive (для LOAD_MODE='drive')
LOCAL_DATA_PATH = '/content/data.csv'           # Путь к локальному файлу (для LOAD_MODE='local')

# --------------------------------------------
# 2. ПРОЕКТ
# --------------------------------------------
PROJECT_NAME = 'stroke'  # Имя проекта. Все данные будут сохранены в папке с этим именем

# --------------------------------------------
# 3. ЦИКЛ ЭКСПЕРИМЕНТА
# --------------------------------------------
# Каждый новый эксперимент (изменение очистки, Feature Engineering и т.д.) - новый номер цикла
# Данные сохраняются в cycle_{CYCLE_NUMBER}/preprocessing/
CYCLE_NUMBER = 5  # 🔄 МЕНЯТЬ ВРУЧНУЮ ПРИ КАЖДОМ НОВОМ ЭКСПЕРИМЕНТЕ

# --------------------------------------------
# 4. РАЗБИЕНИЕ ВЫБОРОК (блок 7)
# --------------------------------------------
SPLIT_TRAIN_SIZE = 0.60   # Доля train выборки (60%)
SPLIT_VAL_SIZE = 0.20     # Доля validation выборки (20%)
SPLIT_TEST_SIZE = 0.20    # Доля test выборки (20%)
RANDOM_STATE = 99       # Seed для воспроизводимости разбиения

# Проверка, что сумма долей равна 1.0
assert abs(SPLIT_TRAIN_SIZE + SPLIT_VAL_SIZE + SPLIT_TEST_SIZE - 1.0) < 0.001, \
    "❌ Сумма долей разбиения должна быть равна 1.0"

# --------------------------------------------
# 5. ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ (для поиска аномалий в блоке 2.2)
# --------------------------------------------
# Значения, которые могут быть маркерами пропусков или ошибок в данных
SUSPICIOUS_VALUES = [
    # Маркеры пропусков
    -1, -999, -9999, -99999,
    999, 9999, 99999, 999999, 9999999,
    # Специальные коды
    99, 999,
    # Экстремальные
    999999999,
    # Технические (границы uint8)
    127, 255,
]

# --------------------------------------------
# 6. ПРИВЕДЕНИЕ ТИПОВ (блок 3.2)
# --------------------------------------------
date_columns = []              # Колонки с датами (будут преобразованы в datetime)
int_columns = ['hypertension', 'heart_disease']   # Целочисленные колонки (будут Int64 с поддержкой NaN)
float_columns = ['age', 'avg_glucose_level', 'bmi']  # Вещественные колонки (будут float64)
categorical_columns = [         # Категориальные колонки (будут string, кодирование в EDA)
    'gender',
    'ever_married',
    'work_type',
    'residence_type',
    'smoking_status'
]
text_columns = []              # Текстовые колонки (будут очищены: strip + lower)

# --------------------------------------------
# 7. УДАЛЕНИЕ КОЛОНОК (блок 3.3)
# --------------------------------------------
columns_to_drop = ['id']       # Колонки, которые будут полностью удалены из датасета

# --------------------------------------------
# 8. ЦЕЛЕВАЯ ПЕРЕМЕННАЯ (блок 5.1)
# --------------------------------------------
TARGET_COLUMN = 'stroke'       # Название колонки с целевой переменной
FORCE_TASK_TYPE = 'classification'  # Принудительный тип задачи: '', 'classification', 'regression'
                                    # Если пусто - автоопределение по количеству уникальных значений

# --------------------------------------------
# 9. ОБРАБОТКА АНОМАЛИЙ (блок 3.4)
# --------------------------------------------
# Пропуски (NaN)
DROP_ROWS_WITH_NULLS = False         # Удалять строки с NaN в ЛЮБЫХ колонках (сейчас отключено)
COLUMNS_TO_CHECK_NULLS = []          # Список колонок для проверки NaN (пусто = все колонки)

# Диапазоны (невозможные значения)
DROP_OUT_OF_RANGE = True             # Удалять значения вне указанных диапазонов
NUMERIC_RANGES = {                   # Допустимые диапазоны для числовых колонок
    'age': (1, 82),                  # Возраст: от 1 до 82 лет
    'bmi': (10, 60),                 # Индекс массы тела: от 10 до 60
    'avg_glucose_level': (50, 300),  # Уровень глюкозы: от 50 до 300
}

# Выбросы (анализ, без удаления - удаление в EDA)
OUTLIER_IQR_COEFF = 1.5              # Коэффициент для IQR метода (анализ выбросов)
DROP_PERCENTILE_OUTLIERS = False     # Удалять выбросы по перцентилям (отключено)
PERCENTILE_RANGE = (0.01, 0.99)      # Диапазон перцентилей (1% - 99%)

# Редкие категории
DROP_RARE_CATEGORIES = True          # Удалять редкие категории (включая редкие NaN)
RARE_CATEGORY_THRESHOLD = 0.01       # Порог: категории с долей < 1% считаются редкими
COLUMNS_TO_CHECK_RARE = ['gender']   # Какие колонки проверять на редкие категории
RARE_CATEGORIES_TO_KEEP = []         # не удалять редкую категорию

# --------------------------------------------
# 10. БАЗОВЫЙ ПУТЬ (автоопределение)
# --------------------------------------------
# Определяем, в какой среде работаем (Colab или локально)
if 'IN_COLAB' not in globals():
    try:
        from google.colab import drive
        IN_COLAB = True
    except ImportError:
        IN_COLAB = False

if IN_COLAB:
    BASE_PATH = '/content/drive/MyDrive/ml_learning'   # Путь в Google Drive
else:
    BASE_PATH = os.path.join(os.getcwd(), 'ml_learning')  # Локальный путь

# --------------------------------------------
# 11. ПОРОГИ ДЛЯ АНАЛИЗА (блок 2.2)
# --------------------------------------------
# Колонки с количеством уникальных значений < этого порога считаются low-cardinality
# и рекомендуются для включения в categorical_columns
LOW_CARDINALITY_THRESHOLD = 20

# --------------------------------------------
# ВЫВОД НАСТРОЕК (для информации)
# --------------------------------------------
print(f"\n📁 ПРОЕКТ: {PROJECT_NAME}")
print(f"🎯 ЦЕЛЬ: {TARGET_COLUMN}")
print(f"📊 ТИП ЗАДАЧИ: {FORCE_TASK_TYPE if FORCE_TASK_TYPE else 'автоопределение'}")
print(f"📂 BASE_PATH: {BASE_PATH}")

print(f"\n📥 ЗАГРУЗКА: {LOAD_MODE}")
if LOAD_MODE == 'drive':
    print(f"   FILE_ID: {FILE_ID}")

print(f"\n🔧 РАЗБИЕНИЕ: train={SPLIT_TRAIN_SIZE:.0%}, val={SPLIT_VAL_SIZE:.0%}, test={SPLIT_TEST_SIZE:.0%}, seed={RANDOM_STATE}")

print(f"\n🧹 ОЧИСТКА:")
print(f"   Пропуски: {DROP_ROWS_WITH_NULLS} ({COLUMNS_TO_CHECK_NULLS if COLUMNS_TO_CHECK_NULLS else 'все колонки'})")
print(f"   Диапазоны: {DROP_OUT_OF_RANGE}")
if DROP_OUT_OF_RANGE:
    for col, (min_v, max_v) in NUMERIC_RANGES.items():
        print(f"      {col}: [{min_v}, {max_v}]")
print(f"   Выбросы IQR: {OUTLIER_IQR_COEFF} (только анализ, удаление в EDA)")
print(f"   Редкие категории: {DROP_RARE_CATEGORIES} (порог {RARE_CATEGORY_THRESHOLD:.1%}, колонки: {COLUMNS_TO_CHECK_RARE})")

print(f"\n⚠️ ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ: {SUSPICIOUS_VALUES[:5]}...")  # первые 5 для краткости

print("\n✓ Настройки загружены\n")

📁 ПРОЕКТ: stroke
🎯 ЦЕЛЬ: stroke
📊 ТИП ЗАДАЧИ: classification
📂 BASE_PATH: /content/drive/MyDrive/ml_learning

📥 ЗАГРУЗКА: drive
   FILE_ID: 1Jsq2V0lFfBurcSZm-fQUJXRB9nUWsG_I

🔧 РАЗБИЕНИЕ: train=60%, val=20%, test=20%, seed=99

🧹 ОЧИСТКА:
   Пропуски: False (все колонки)
   Диапазоны: True
      age: [1, 82]
      bmi: [10, 60]
      avg_glucose_level: [50, 300]
   Выбросы IQR: 1.5 (только анализ, удаление в EDA)
   Редкие категории: True (порог 1.0%, колонки: ['gender'])

⚠️ ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ: [-1, -999, -9999, -99999, 999]...

✓ Настройки загружены

In [ ]:
# 1.4 МОНТИРОВАНИЕ GOOGLE DRIVE

print("\n" + "="*50)
print("📂 МОНТИРОВАНИЕ GOOGLE DRIVE")
print("="*50)

if IN_COLAB:
    if BASE_PATH.startswith('/content/drive'):
        if os.path.ismount('/content/drive'):
            print("✓ Google Drive уже смонтирован")
        else:
            print("📂 Монтирование Google Drive...")

            # Если есть папка /content/drive, но она НЕ точка монтирования
            if os.path.exists('/content/drive') and not os.path.ismount('/content/drive'):
                backup_name = f'/content/drive_backup_{datetime.now().strftime("%Y%m%d_%H%M%S")}'
                print(f"   ⚠️ Обнаружена папка /content/drive (не точка монтирования)")
                print(f"   Перемещаем в {backup_name}")
                shutil.move('/content/drive', backup_name)

            # Монтируем Google Drive с обработкой ошибок
            try:
                drive.mount('/content/drive')
                print("✓ Google Drive смонтирован")
            except Exception as e:
                print(f"\n❌ ОШИБКА МОНТИРОВАНИЯ: {e}")
                print("   Возможные причины:")
                print("   • Нет подключения к интернету")
                print("   • Нет прав доступа к Google Drive")
                print("   • Проблемы с авторизацией")
                print("\n   💡 Решение:")
                print("   • Проверьте интернет-соединение")
                print("   • Перезапустите среду выполнения (Runtime → Restart runtime)")
                print("   • При монтировании нажмите на ссылку и скопируйте код авторизации")
                raise  # Останавливаем выполнение, так как без Drive дальше не продолжить
    else:
        print("✓ BASE_PATH не на Google Drive, монтирование не требуется")
else:
    print("✓ Локальная среда, монтирование не требуется")

print("="*50 + "\n")

==================================================
📂 МОНТИРОВАНИЕ GOOGLE DRIVE
==================================================
✓ Google Drive уже смонтирован
==================================================

In [ ]:
# 1.5 ЗАГРУЗКА ДАННЫХ

if LOAD_MODE == 'drive':
    if not FILE_ID:
        raise ValueError("❌ FILE_ID не указан в настройках (блок 1.3)")

    # Только для файлов < 100 MB
    # Для файлов > 100 MB:
    #   !pip install gdown
    #   import gdown
    #   gdown.download(f'https://drive.google.com/uc?id={FILE_ID}', 'data.csv')

    url = f'https://drive.google.com/uc?export=download&id={FILE_ID}'
    print(f"📥 Загрузка с Google Drive...")

    try:
        df = pd.read_csv(url)
        print(f"✓ Данные загружены: {df.shape[0]} строк, {df.shape[1]} колонок")
    except Exception as e:
        print(f"❌ Ошибка загрузки: {e}")
        print("   Проверьте, что файл доступен по ссылке (Anyone with link)")
        raise

elif LOAD_MODE == 'local':
    if not os.path.exists(LOCAL_DATA_PATH):
        raise FileNotFoundError(f"❌ Файл не найден: {LOCAL_DATA_PATH}")

    df = pd.read_csv(LOCAL_DATA_PATH)
    print(f"✓ Данные загружены локально: {df.shape[0]} строк, {df.shape[1]} колонок")

else:
    raise ValueError(f"❌ LOAD_MODE должен быть 'drive' или 'local', получено: '{LOAD_MODE}'")

📥 Загрузка с Google Drive...
✓ Данные загружены: 5110 строк, 12 колонок

In [ ]:
# 1.6 НАСТРОЙКА ПУТЕЙ ПРОЕКТА (С УЧЁТОМ ЦИКЛОВ И ЗАЩИТОЙ ОТ ПЕРЕЗАПИСИ)

import shutil

# Проверка, что BASE_PATH определён
if 'BASE_PATH' not in globals():
    raise NameError("❌ BASE_PATH не определён. Выполните блок 1.3")

# Проверка, что PROJECT_NAME определён
if 'PROJECT_NAME' not in globals():
    raise NameError("❌ PROJECT_NAME не определён. Выполните блок 1.3")

# Проверка, что PROJECT_NAME не содержит 'cycle_'
if 'cycle_' in PROJECT_NAME:
    raise ValueError(f"❌ PROJECT_NAME не должен содержать 'cycle_': {PROJECT_NAME}")

# Проверка, что CYCLE_NUMBER определён и является положительным целым числом
if 'CYCLE_NUMBER' not in globals():
    raise NameError("❌ CYCLE_NUMBER не определён. Укажите его в блоке 1.3")

if not isinstance(CYCLE_NUMBER, int) or CYCLE_NUMBER <= 0:
    raise ValueError(f"❌ CYCLE_NUMBER должен быть положительным целым числом, получено: {CYCLE_NUMBER}")

# --------------------------------------------
# БАЗОВЫЕ ПУТИ
# --------------------------------------------
PROJECT_PATH = os.path.join(BASE_PATH, 'datasets', PROJECT_NAME)

# --------------------------------------------
# ПУТИ С УЧЁТОМ ЦИКЛА
# --------------------------------------------
CYCLE_PATH = os.path.join(PROJECT_PATH, f'cycle_{CYCLE_NUMBER}')
PREPROCESSING_PATH = os.path.join(CYCLE_PATH, 'preprocessing')

# ========================================
# ЗАЩИТА ОТ ПЕРЕЗАПИСИ (С ПОЛНЫМ УДАЛЕНИЕМ)
# ========================================
if os.path.exists(CYCLE_PATH):
    print(f"\n⚠️ ВНИМАНИЕ: Папка цикла {CYCLE_NUMBER} уже существует!")
    print(f"   {CYCLE_PATH}")

    # Проверяем, есть ли файлы в preprocessing
    if os.path.exists(PREPROCESSING_PATH):
        existing_files = os.listdir(PREPROCESSING_PATH)
        if existing_files:
            print(f"   Обнаружены существующие файлы: {existing_files[:5]}...")
            if 'final_model.joblib' in existing_files:
                print("   ⚠️ ВНИМАНИЕ: Обнаружена финальная модель! Перезапись удалит её.")

    print(f"\n   Что делать:")
    print(f"   • Если хотите СОЗДАТЬ НОВЫЙ ЦИКЛ, измените CYCLE_NUMBER на {CYCLE_NUMBER + 1} в блоке 1.3")
    print(f"   • Если хотите ПЕРЕЗАПИСАТЬ текущий цикл, введите 'y'")

    response = input(f"\n   Продолжить с перезаписью? (y/N): ")
    if response.lower() != 'y':
        print("❌ Операция отменена. Измените CYCLE_NUMBER и запустите заново.")
        raise SystemExit(0)
    else:
        print(f"   ⚠️ Продолжаем с перезаписью cycle_{CYCLE_NUMBER}")
        # ПОЛНОЕ УДАЛЕНИЕ СТАРОЙ ПАПКИ
        shutil.rmtree(CYCLE_PATH)
        print(f"   🗑️ Старая папка цикла удалена")

# --------------------------------------------
# СОЗДАНИЕ ПАПОК ЦИКЛА
# --------------------------------------------
CHECKPOINT_PATH = os.path.join(PREPROCESSING_PATH, 'checkpoints')
SPLITS_PATH = os.path.join(PREPROCESSING_PATH, 'splits')
REPORTS_PATH = os.path.join(PREPROCESSING_PATH, 'reports')

for path in [CYCLE_PATH, PREPROCESSING_PATH, CHECKPOINT_PATH, SPLITS_PATH, REPORTS_PATH]:
    os.makedirs(path, exist_ok=True)

print(f"\n🔄 ЦИКЛ {CYCLE_NUMBER} (изолированный)")
print(f"📂 СТРУКТУРА ЦИКЛА {CYCLE_NUMBER}:")
print(f"   {CYCLE_PATH}/")
print(f"   └── preprocessing/")
print(f"       ├── checkpoints/")
print(f"       ├── splits/")
print(f"       └── reports/")

# Условное сообщение в зависимости от окружения
if IN_COLAB:
    print(f"\n✓ Папки созданы на Google Drive")
else:
    print(f"\n✓ Папки созданы локально")

print("=" * 50 + "\n")

🔄 ЦИКЛ 5 (изолированный)
📂 СТРУКТУРА ЦИКЛА 5:
   /content/drive/MyDrive/ml_learning/datasets/stroke/cycle_5/
   └── preprocessing/
       ├── checkpoints/
       ├── splits/
       └── reports/

✓ Папки созданы на Google Drive
==================================================

In [ ]:
# 1.7 СОХРАНЕНИЕ ИСХОДНЫХ ДАННЫХ

if 'df' not in globals() or df is None or df.empty:
    raise ValueError("❌ Данные не загружены. Выполните блок 1.5")

raw_backup_path = os.path.join(CHECKPOINT_PATH, '00_raw.csv')
df.to_csv(raw_backup_path, index=False)
print(f"✓ Контрольная точка сохранена: checkpoints/00_raw.csv")

✓ Контрольная точка сохранена: checkpoints/00_raw.csv

# БЛОК 2. Общая info

In [ ]:
# 2.1 ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ

if df is None or df.empty:
    print("❌ Данные не загружены. Выполните блок 1.5")
else:
    print("\n" + "="*50)
    print("🔍 ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ")
    print("="*50)

    # Размер таблицы
    print(f"\n📏 РАЗМЕР: {df.shape[0]} строк, {df.shape[1]} колонок")

    # Названия колонок
    print(f"\n📋 КОЛОНКИ ({len(df.columns)}):")
    print(f"   {df.columns.tolist()}")

    # Типы данных
    print(f"\n📊 ТИПЫ ДАННЫХ:")
    type_counts = df.dtypes.value_counts()
    for dtype, count in type_counts.items():
        print(f"   {dtype}: {count}")

    # Первые 5 строк
    print(f"\n👀 ПЕРВЫЕ 5 СТРОК:")
    display(df.head())

    # Пропуски
    print(f"\n🚫 ПРОПУСКИ:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) > 0:
        for col, count in missing.items():
            pct = count / len(df) * 100
            print(f"   {col}: {count} ({pct:.1f}%)")
    else:
        print("   ✓ Пропусков нет")

    # Дубликаты
    print(f"\n📑 ДУБЛИКАТЫ:")
    duplicates_count = df.duplicated().sum()
    if duplicates_count > 0:
        print(f"   Полных дубликатов строк: {duplicates_count} ({duplicates_count/len(df)*100:.2f}%)")
    else:
        print("   ✓ Дубликатов нет")

    # Числовые колонки (универсальный выбор)
    print(f"\n🔢 ЧИСЛОВЫЕ КОЛОНКИ:")
    numeric_cols = df.select_dtypes(include=['number']).columns.tolist()
    if numeric_cols:
        print(f"   {numeric_cols}")
    else:
        print("   Числовых колонок нет")

    # Категориальные колонки (универсальный выбор)
    print(f"\n🏷️ КАТЕГОРИАЛЬНЫЕ КОЛОНКИ:")
    categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
    if categorical_cols:
        print(f"   {categorical_cols}")
    else:
        print("   Категориальных колонок нет")

    # Boolean колонки (отдельно, их не надо кодировать как категории)
    print(f"\n🔘 BOOLEAN КОЛОНКИ (0/1):")
    bool_cols = df.select_dtypes(include=['bool']).columns.tolist()
    if bool_cols:
        print(f"   {bool_cols}")
        print(f"   💡 Boolean колонки можно оставить как есть (0/1), не кодируя как категории")
    else:
        print("   Boolean колонок нет")

    # Базовая статистика по числовым
    if numeric_cols:
        print(f"\n📈 СТАТИСТИКА ПО ЧИСЛОВЫМ:")
        display(df[numeric_cols].describe())

    print("\n" + "="*50)
    print("✓ Первичный осмотр завершён")
    print("="*50 + "\n")

==================================================
🔍 ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ
==================================================

📏 РАЗМЕР: 5110 строк, 12 колонок

📋 КОЛОНКИ (12):
   ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

📊 ТИПЫ ДАННЫХ:
   object: 5
   int64: 4
   float64: 3

👀 ПЕРВЫЕ 5 СТРОК:

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

🚫 ПРОПУСКИ:
   bmi: 201 (3.9%)

📑 ДУБЛИКАТЫ:
   ✓ Дубликатов нет

🔢 ЧИСЛОВЫЕ КОЛОНКИ:
   ['id', 'age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke']

🏷️ КАТЕГОРИАЛЬНЫЕ КОЛОНКИ:
   ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

🔘 BOOLEAN КОЛОНКИ (0/1):
   Boolean колонок нет

📈 СТАТИСТИКА ПО ЧИСЛОВЫМ:

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

==================================================
✓ Первичный осмотр завершён
==================================================

In [ ]:
# 2.2 ДОПОЛНИТЕЛЬНЫЕ ПРОВЕРКИ (только вывод в консоль, отчёт будет в preprocessing_report.txt)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем проверки.")
else:
    # --------------------------------------------
    # Диапазоны числовых колонок (min/max)
    # --------------------------------------------
    print("\n--- ДИАПАЗОНЫ ЧИСЛОВЫХ КОЛОНОК ---")
    numeric_cols = df.select_dtypes(include=['number']).columns
    if len(numeric_cols) > 0:
        for col in numeric_cols:
            print(f"{col}: min = {df[col].min()}, max = {df[col].max()}")
    else:
        print("Нет числовых колонок для анализа")

    # --------------------------------------------
    # Проверка пустых строк ("" вместо NaN) в текстовых колонках
    # --------------------------------------------
    print("\n--- ПУСТЫЕ СТРОКИ В ТЕКСТОВЫХ КОЛОНКАХ ---")
    text_cols = df.select_dtypes(include=['object']).columns
    empty_found = False
    for col in text_cols:
        empty_count = (df[col] == '').sum()
        if empty_count > 0:
            print(f"{col}: {empty_count} пустых строк")
            empty_found = True
    if not empty_found:
        print("Пустых строк ('' вместо NaN) не обнаружено")

    # --------------------------------------------
    # Проверка на подозрительные значения в числовых колонках
    # --------------------------------------------
    print("\n--- ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ ---")
    suspicious = SUSPICIOUS_VALUES if 'SUSPICIOUS_VALUES' in globals() else [-1, -999, 999999, 999999999]
    suspicious_found = False
    for col in numeric_cols:
        for val in suspicious:
            count = (df[col] == val).sum()
            if count > 0:
                print(f"{col}: {count} раз встречается {val}")
                suspicious_found = True
    if not suspicious_found:
        print("Подозрительных значений не обнаружено")

    # --------------------------------------------
    # Проверка на аномально высокую долю NaN
    # --------------------------------------------
    print("\n--- АНОМАЛЬНО ВЫСОКАЯ ДОЛЯ NaN ---")
    high_null_cols = []
    for col in df.columns:
        null_pct = df[col].isna().mean() * 100
        if null_pct > 30:  # порог можно настроить
            high_null_cols.append((col, null_pct))

    if high_null_cols:
        print("   ⚠️ Обнаружены колонки с >30% пропусков:")
        for col, pct in high_null_cols:
            print(f"      {col}: {pct:.1f}% NaN")
        print("   💡 Рекомендация: проверьте, не являются ли NaN маркером пропусков")
        print("      (например, -1 или 999 вместо NaN)")
    else:
        print("   ✓ Нет колонок с аномально высокой долей NaN (>30%)")

    # --------------------------------------------
    # Уникальные значения в колонках с малым количеством вариантов
    # --------------------------------------------
    print("\n--- УНИКАЛЬНЫЕ ЗНАЧЕНИЯ (колонки с < 20 вариантов) ---")

    low_cardinality_cols = []
    potential_int_cols = []

    # Используем порог из настроек (по умолчанию 20)
    threshold = LOW_CARDINALITY_THRESHOLD if 'LOW_CARDINALITY_THRESHOLD' in globals() else 20

    for col in df.columns:
        unique_count = df[col].nunique()
        if unique_count < threshold:
            low_cardinality_cols.append(col)
            print(f"\n{col} ({unique_count} уникальных значений):")
            print(df[col].unique())

        # Проверка на потенциально целочисленные колонки
        if df[col].dtype in ['int64', 'Int64', 'int32', 'int16', 'int8']:
            potential_int_cols.append(col)
        elif df[col].dtype in ['float64', 'float32']:
            col_clean = df[col].dropna()
            if len(col_clean) > 0:
                is_finite = np.isfinite(col_clean).all()
                # Используем np.allclose с допуском для защиты от floating point precision
                is_integer = np.allclose(col_clean, col_clean.round(), atol=1e-8)
                if is_finite and is_integer:
                    potential_int_cols.append(col)

    # --------------------------------------------
    # ИСКЛЮЧАЕМ ЦЕЛЕВУЮ КОЛОНКУ ИЗ low_cardinality_cols
    # --------------------------------------------
    if TARGET_COLUMN in low_cardinality_cols:
        low_cardinality_cols.remove(TARGET_COLUMN)
        print(f"\n   ℹ️ '{TARGET_COLUMN}' (целевая) исключена из списка категориальных")

    # --------------------------------------------
    # Подсказка для categorical_columns
    # --------------------------------------------
    if low_cardinality_cols:
        print("\n" + "="*60)
        print("💡 ПОДСКАЗКА 1: КАТЕГОРИАЛЬНЫЕ КОЛОНКИ")
        print("   Эти колонки имеют мало уникальных значений (<20).")
        print("   Их рекомендуется добавить в список 'categorical_columns'")
        print("   в блоке настроек проекта.\n")
        print("   Скопируй этот список в categorical_columns:")
        print(f"   categorical_columns = {low_cardinality_cols}")
        print("="*60)

    # --------------------------------------------
    # Подсказка для int_columns
    # --------------------------------------------
    if potential_int_cols:
        print("\n" + "="*60)
        print("💡 ПОДСКАЗКА 2: ЦЕЛОЧИСЛЕННЫЕ КОЛОНКИ")
        print("   Эти колонки являются целыми числами.")
        print("   Их рекомендуется добавить в список 'int_columns'")
        print("   в блоке настроек проекта.\n")
        print("   Скопируй этот список в int_columns:")
        print(f"   int_columns = {potential_int_cols}")
        print("="*60)

    print("\n✅ Анализ завершён. Полный отчёт будет сохранён в preprocessing_report.txt")

--- ДИАПАЗОНЫ ЧИСЛОВЫХ КОЛОНОК ---
id: min = 67, max = 72940
age: min = 0.08, max = 82.0
hypertension: min = 0, max = 1
heart_disease: min = 0, max = 1
avg_glucose_level: min = 55.12, max = 271.74
bmi: min = 10.3, max = 97.6
stroke: min = 0, max = 1

--- ПУСТЫЕ СТРОКИ В ТЕКСТОВЫХ КОЛОНКАХ ---
Пустых строк ('' вместо NaN) не обнаружено

--- ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ ---
id: 1 раз встречается 99
avg_glucose_level: 2 раз встречается 99

--- АНОМАЛЬНО ВЫСОКАЯ ДОЛЯ NaN ---
   ✓ Нет колонок с аномально высокой долей NaN (>30%)

--- УНИКАЛЬНЫЕ ЗНАЧЕНИЯ (колонки с < 20 вариантов) ---

gender (3 уникальных значений):
['Male' 'Female' 'Other']

hypertension (2 уникальных значений):
[0 1]

heart_disease (2 уникальных значений):
[1 0]

ever_married (2 уникальных значений):
['Yes' 'No']

work_type (5 уникальных значений):
['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']

Residence_type (2 уникальных значений):
['Urban' 'Rural']

smoking_status (4 уникальных значений):
['formerly smoked' 'never smoked' 'smokes' 'Unknown']

stroke (2 уникальных значений):
[1 0]

   ℹ️ 'stroke' (целевая) исключена из списка категориальных

============================================================
💡 ПОДСКАЗКА 1: КАТЕГОРИАЛЬНЫЕ КОЛОНКИ
   Эти колонки имеют мало уникальных значений (<20).
   Их рекомендуется добавить в список 'categorical_columns'
   в блоке настроек проекта.

   Скопируй этот список в categorical_columns:
   categorical_columns = ['gender', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']
============================================================

============================================================
💡 ПОДСКАЗКА 2: ЦЕЛОЧИСЛЕННЫЕ КОЛОНКИ
   Эти колонки являются целыми числами.
   Их рекомендуется добавить в список 'int_columns'
   в блоке настроек проекта.

   Скопируй этот список в int_columns:
   int_columns = ['id', 'hypertension', 'heart_disease', 'stroke']
============================================================

✅ Анализ завершён. Полный отчёт будет сохранён в preprocessing_report.txt

# БЛОК 3. Предобработка данных

# Ручное rename_dict

In [ ]:
# 3.1 ПЕРЕИМЕНОВАНИЕ КОЛОНОК

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("📝 ПЕРЕИМЕНОВАНИЕ КОЛОНОК")
    print("="*50)

    # Сохраняем старые названия для сравнения
    old_columns = df.columns.tolist()

    # Автоматическая чистка
    df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]

    # Проверяем, какие колонки изменились
    changed_cols = []
    for old, new in zip(old_columns, df.columns):
        if old != new:
            changed_cols.append(f"{old} → {new}")

    if changed_cols:
        print("\n✓ Автоматическая чистка выполнена:")
        for change in changed_cols:
            print(f"   {change}")
    else:
        print("\n✓ Названия колонок уже в правильном формате")

    # Проверка и автоматическое разрешение дубликатов
    if len(df.columns) != len(set(df.columns)):
        print(f"\n⚠️ Обнаружены дубликаты колонок!")

        from collections import Counter
        counter = Counter()
        new_cols = []
        for col in df.columns:
            counter[col] += 1
            if counter[col] > 1:
                new_cols.append(f"{col}_{counter[col]-1}")
            else:
                new_cols.append(col)

        print(f"   Разрешаем дубликаты добавлением суффиксов:")
        for old, new in zip(df.columns, new_cols):
            if old != new:
                print(f"      {old} → {new}")

        df.columns = new_cols
        print(f"\n✓ Дубликаты разрешены")

    # Ручное переименование (раскомментируйте и заполните при необходимости)
    # --------------------------------------------
    # rename_dict = {
    #     'старое_название': 'новое_название',
    #     # добавьте свои пары...
    # }
    #
    # if rename_dict:
    #     existing_rename = {k: v for k, v in rename_dict.items() if k in df.columns}
    #     if existing_rename:
    #         df = df.rename(columns=existing_rename)
    #         print(f"\n✓ Ручное переименование:")
    #         for old, new in existing_rename.items():
    #             print(f"   {old} → {new}")
    #     else:
    #         print("\n⚠️ Колонки для ручного переименования не найдены")

    # Итоговый список колонок
    print(f"\n📋 Итоговые колонки ({len(df.columns)}):")
    print(f"   {df.columns.tolist()}")

    print("\n" + "="*50)
    print("✓ Переименование завершено")
    print("="*50 + "\n")

==================================================
📝 ПЕРЕИМЕНОВАНИЕ КОЛОНОК
==================================================

✓ Автоматическая чистка выполнена:
   Residence_type → residence_type

📋 Итоговые колонки (12):
   ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

==================================================
✓ Переименование завершено
==================================================

In [ ]:
# 3.2 ПРИВЕДЕНИЕ ТИПОВ ДАННЫХ

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🔧 ПРИВЕДЕНИЕ ТИПОВ ДАННЫХ")
    print("="*50)

    # Преобразование в даты
    if date_columns:
        print("\n📅 ДАТЫ:")
        for col in date_columns:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors='coerce')
                print(f"   ✓ {col} → datetime")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n📅 ДАТЫ: не заданы")

    # Преобразование в целые числа с поддержкой NaN
    if int_columns:
        print("\n🔢 ЦЕЛЫЕ ЧИСЛА (Int64):")
        for col in int_columns:
            if col in df.columns:
                # Сохраняем количество значений до преобразования для логирования потерь
                before_count = df[col].count()
                df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
                after_count = df[col].count()
                lost = before_count - after_count
                if lost > 0:
                    print(f"   ✓ {col} → Int64 (⚠️ {lost} значений стали NaN)")
                else:
                    print(f"   ✓ {col} → Int64")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n🔢 ЦЕЛЫЕ ЧИСЛА: не заданы")

    # Преобразование в числа с плавающей точкой
    if float_columns:
        print("\n📊 ВЕЩЕСТВЕННЫЕ ЧИСЛА (float64):")
        for col in float_columns:
            if col in df.columns:
                before_count = df[col].count()
                df[col] = pd.to_numeric(df[col], errors='coerce')
                after_count = df[col].count()
                lost = before_count - after_count
                if lost > 0:
                    print(f"   ✓ {col} → float64 (⚠️ {lost} значений стали NaN)")
                else:
                    print(f"   ✓ {col} → float64")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n📊 ВЕЩЕСТВЕННЫЕ ЧИСЛА: не заданы")

    # Преобразование категориальных колонок в string (не category!)
    # Кодирование будет выполнено в EDA ноутбуке
    if categorical_columns:
        print("\n🏷️ КАТЕГОРИАЛЬНЫЕ (string):")
        for col in categorical_columns:
            if col in df.columns:
                # Используем string тип (нейтральный, без навязывания category)
                df[col] = df[col].astype('string')
                print(f"   ✓ {col} → string (кодирование будет в EDA)")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n🏷️ КАТЕГОРИАЛЬНЫЕ: не заданы")

    # Итоговые типы данных
    print("\n📋 ИТОГОВЫЕ ТИПЫ ДАННЫХ:")
    print(df.dtypes)

    print("\n" + "="*50)
    print("✓ Приведение типов завершено")
    print("="*50 + "\n")

==================================================
🔧 ПРИВЕДЕНИЕ ТИПОВ ДАННЫХ
==================================================

📅 ДАТЫ: не заданы

🔢 ЦЕЛЫЕ ЧИСЛА (Int64):
   ✓ hypertension → Int64
   ✓ heart_disease → Int64

📊 ВЕЩЕСТВЕННЫЕ ЧИСЛА (float64):
   ✓ age → float64
   ✓ avg_glucose_level → float64
   ✓ bmi → float64

🏷️ КАТЕГОРИАЛЬНЫЕ (string):
   ✓ gender → string (кодирование будет в EDA)
   ✓ ever_married → string (кодирование будет в EDA)
   ✓ work_type → string (кодирование будет в EDA)
   ✓ residence_type → string (кодирование будет в EDA)
   ✓ smoking_status → string (кодирование будет в EDA)

📋 ИТОГОВЫЕ ТИПЫ ДАННЫХ:
id                            int64
gender               string[python]
age                         float64
hypertension                  Int64
heart_disease                 Int64
ever_married         string[python]
work_type            string[python]
residence_type       string[python]
avg_glucose_level           float64
bmi                         float64
smoking_status       string[python]
stroke                        int64
dtype: object

==================================================
✓ Приведение типов завершено
==================================================

In [ ]:
# 3.3 УДАЛЕНИЕ НЕНУЖНЫХ КОЛОНОК

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🗑️ УДАЛЕНИЕ НЕНУЖНЫХ КОЛОНОК")
    print("="*50)

    if columns_to_drop:
        # Проверяем, не удаляем ли таргет
        if TARGET_COLUMN in columns_to_drop:
            print(f"\n🔴 КРИТИЧЕСКАЯ ОШИБКА: TARGET_COLUMN='{TARGET_COLUMN}' находится в columns_to_drop!")
            print("   Целевая колонка не может быть удалена.")
            print(f"\n   Удалите '{TARGET_COLUMN}' из списка columns_to_drop в блоке 1.3")
            raise ValueError(f"TARGET_COLUMN '{TARGET_COLUMN}' не может быть удалён")

        existing_cols = [col for col in columns_to_drop if col in df.columns]
        missing_cols = [col for col in columns_to_drop if col not in df.columns]

        if existing_cols:
            df.drop(columns=existing_cols, inplace=True)
            print(f"\n✓ Удалены колонки: {existing_cols}")
        else:
            print("\n⚠️ Указанные колонки не найдены в датасете")

        if missing_cols:
            print(f"⚠️ Колонки не найдены: {missing_cols}")
    else:
        print("\n✓ Нет колонок для удаления")

    print(f"\n📋 Итоговые колонки ({len(df.columns)}):")
    print(f"   {df.columns.tolist()}")

    print("\n" + "="*50)
    print("✓ Удаление колонок завершено")
    print("="*50 + "\n")

==================================================
🗑️ УДАЛЕНИЕ НЕНУЖНЫХ КОЛОНОК
==================================================

✓ Удалены колонки: ['id']

📋 Итоговые колонки (11):
   ['gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

==================================================
✓ Удаление колонок завершено
==================================================

In [ ]:
# 3.4 ОБРАБОТКА АНОМАЛИЙ (только явный мусор)

# ========================================
# Здесь удаляются только явные ошибки и невозможные значения
# Выбросы (экстремальные, но возможные значения) будут обработаны в EDA
# ========================================

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🧹 ОБРАБОТКА АНОМАЛИЙ")
    print("="*50)

    initial_len = len(df)
    deleted_summary = {}
    removed_categories = {}

    # --------------------------------------------
    # 1. Удаление пропусков
    # --------------------------------------------
    if DROP_ROWS_WITH_NULLS and COLUMNS_TO_CHECK_NULLS:
        print("\n--- 1. Удаление строк с пропусками ---")
        for col in COLUMNS_TO_CHECK_NULLS:
            if col in df.columns:
                nulls_before = df[col].isna().sum()
                if nulls_before > 0:
                    # Сохраняем удаляемые строки для проверки
                    null_mask = df[col].isna()
                    deleted_df = df[null_mask].copy()

                    # Проверка целевой переменной в удалённых строках
                    if TARGET_COLUMN in df.columns:
                        total_stroke_pct = df[TARGET_COLUMN].mean() * 100
                        deleted_stroke_pct = deleted_df[TARGET_COLUMN].mean() * 100

                        if deleted_stroke_pct > total_stroke_pct * 1.5:
                            print(f"      ⚠️ ВНИМАНИЕ: В удаляемых строках целевой переменной {deleted_stroke_pct:.1f}%")
                            print(f"         Это выше среднего ({total_stroke_pct:.1f}%)")
                            print(f"         Рекомендуется не удалять, а заполнить пропуски")

                    df.dropna(subset=[col], inplace=True)
                    deleted_summary[f'Пропуски в {col}'] = nulls_before
                    print(f"   ✓ {col}: удалено {nulls_before} строк")

                    # Проверка целевой переменной в удалённых строках
                    if TARGET_COLUMN in deleted_df.columns:
                        target_counts = deleted_df[TARGET_COLUMN].value_counts().to_dict()
                        print(f"      📊 Распределение целевой переменной в удалённых строках:")
                        for val, count in target_counts.items():
                            pct = count / nulls_before * 100
                            print(f"         {val}: {count} ({pct:.1f}%)")
                else:
                    print(f"   ✓ {col}: пропусков нет")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")
    else:
        print("\n--- 1. Удаление пропусков: ОТКЛЮЧЕНО (перенесено в EDA) ---")

    # --------------------------------------------
    # 2. Удаление значений вне диапазонов
    # --------------------------------------------
    if DROP_OUT_OF_RANGE and NUMERIC_RANGES:
        print("\n--- 2. Удаление значений вне диапазонов (NaN сохраняются) ---")
        for col, (min_val, max_val) in NUMERIC_RANGES.items():
            if col in df.columns:
                before = len(df)
                # Сохраняем строки с NaN И строки в диапазоне
                mask = df[col].isna() | ((df[col] >= min_val) & (df[col] <= max_val))
                deleted_df = df[~mask].copy()
                df = df[mask]
                deleted = before - len(df)
                if deleted > 0:
                    deleted_summary[f'Диапазон {col} [{min_val}, {max_val}]'] = deleted
                    print(f"   ✓ {col}: удалено {deleted} строк")

                    # Проверка целевой переменной в удалённых строках
                    if TARGET_COLUMN in deleted_df.columns:
                        target_counts = deleted_df[TARGET_COLUMN].value_counts().to_dict()
                        print(f"      📊 Распределение целевой переменной в удалённых строках:")
                        for val, count in target_counts.items():
                            pct = count / deleted * 100
                            print(f"         {val}: {count} ({pct:.1f}%)")
                else:
                    print(f"   ✓ {col}: все значения в диапазоне")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")

    # --------------------------------------------
    # 3. Удаление редких категорий (включая NaN)
    # --------------------------------------------
    if DROP_RARE_CATEGORIES and COLUMNS_TO_CHECK_RARE:
        print("\n--- 3. Удаление редких категорий ---")
        for col in COLUMNS_TO_CHECK_RARE:
            if col in df.columns:
                before = len(df)

                # Проверяем NaN в категориальной колонке
                nan_count = df[col].isna().sum()
                if nan_count > 0:
                    nan_pct = nan_count / len(df)
                    if nan_pct < RARE_CATEGORY_THRESHOLD:
                        # NaN редкая "категория", удаляем
                        nan_mask = df[col].isna()
                        deleted_df = df[nan_mask].copy()
                        df = df[df[col].notna()]
                        deleted = before - len(df)
                        deleted_summary[f'NaN в {col} (редкие)'] = deleted
                        print(f"   ✓ {col}: удалено {deleted} строк с NaN (редкая категория, {nan_pct:.2%})")

                        # Проверка целевой переменной в удалённых строках
                        if TARGET_COLUMN in deleted_df.columns:
                            target_counts = deleted_df[TARGET_COLUMN].value_counts().to_dict()
                            print(f"      📊 Распределение целевой переменной в удалённых строках:")
                            for val, count in target_counts.items():
                                pct = count / deleted * 100
                                print(f"         {val}: {count} ({pct:.1f}%)")

                        before = len(df)  # обновляем для дальнейших проверок
                    else:
                        print(f"   ⚠️ {col}: NaN составляют {nan_pct:.2%} (> порога), НЕ удаляются")

                # Проверяем обычные редкие категории (без учёта NaN)
                value_counts = df[col].value_counts(normalize=True)
                rare_values = value_counts[value_counts < RARE_CATEGORY_THRESHOLD].index.tolist()
                rare_values = [v for v in rare_values if v not in RARE_CATEGORIES_TO_KEEP]

                if rare_values:
                    mask = ~df[col].isin(rare_values)
                    deleted_df = df[~mask].copy()
                    df = df[mask]
                    deleted = before - len(df)
                    deleted_summary[f'Редкие в {col}'] = deleted
                    # Сохраняем список удалённых категорий
                    if col not in removed_categories:
                        removed_categories[col] = []
                    removed_categories[col].extend(rare_values)
                    print(f"   ✓ {col}: удалено {deleted} строк, редкие: {rare_values}")

                    # Проверка целевой переменной в удалённых строках
                    if TARGET_COLUMN in deleted_df.columns:
                        target_counts = deleted_df[TARGET_COLUMN].value_counts().to_dict()
                        print(f"      📊 Распределение целевой переменной в удалённых строках:")
                        for val, count in target_counts.items():
                            pct = count / deleted * 100
                            print(f"         {val}: {count} ({pct:.1f}%)")
                else:
                    if nan_count == 0 or nan_pct >= RARE_CATEGORY_THRESHOLD:
                        print(f"   ✓ {col}: редких категорий нет")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")

    # --------------------------------------------
    # 4. Сброс индекса
    # --------------------------------------------
    df.reset_index(drop=True, inplace=True)

    # --------------------------------------------
    # 5. Проверка на чрезмерное удаление
    # --------------------------------------------
    if len(df) < initial_len * 0.5:
        print("\n⚠️ ВНИМАНИЕ: Удалено более 50% строк!")
        print("   Проверьте настройки диапазонов и порогов в блоке 1.3")

    # --------------------------------------------
    # 6. СБОР СТАТИСТИКИ ДЛЯ ОТЧЁТА
    # --------------------------------------------
    # Статистика удалений (для отчёта)
    rows_original = initial_len
    rows_final = len(df)
    rows_removed = initial_len - len(df)
    removal_reasons = deleted_summary  # deleted_summary создаётся выше в коде

    # Границы обрезки (для отчёта)
    clipping_boundaries = {}
    if 'NUMERIC_RANGES' in globals():
        for col, (min_val, max_val) in NUMERIC_RANGES.items():
            clipping_boundaries[col] = {
                "min": min_val,
                "max": max_val,
                "action": "drop" if DROP_OUT_OF_RANGE else "none"
            }

    print("\n📊 Статистика очистки собрана (removal_reasons, clipping_boundaries, removed_categories)")
    print("   Будет использована в итоговом отчёте preprocessing_report.txt")

    # --------------------------------------------
    # ИТОГИ
    # --------------------------------------------
    print("\n" + "="*60)
    print("📊 ИТОГИ УДАЛЕНИЯ АНОМАЛИЙ")
    print("="*60)

    if deleted_summary:
        print(f"\n{'Причина удаления':<35} {'Строк':>10} {'%':>10}")
        print("-" * 60)
        for reason, count in deleted_summary.items():
            pct = count / initial_len * 100
            print(f"{reason:<35} {count:>10} {pct:>9.2f}%")

        total_deleted = initial_len - len(df)
        total_pct = total_deleted / initial_len * 100
        print("-" * 60)
        print(f"{'ВСЕГО УДАЛЕНО':<35} {total_deleted:>10} {total_pct:>9.2f}%")
        print(f"{'ОСТАЛОСЬ СТРОК':<35} {len(df):>10}")
    else:
        print("\n✓ Аномалий не обнаружено, строки не удалялись")
        print(f"✓ Осталось строк: {len(df)}")

    print("="*60)
    print("\n✓ Обработка аномалий завершена\n")

==================================================
🧹 ОБРАБОТКА АНОМАЛИЙ
==================================================

--- 1. Удаление пропусков: ОТКЛЮЧЕНО (перенесено в EDA) ---

--- 2. Удаление значений вне диапазонов (NaN сохраняются) ---
   ✓ age: удалено 43 строк
      📊 Распределение целевой переменной в удалённых строках:
         0: 43 (100.0%)
   ✓ bmi: удалено 13 строк
      📊 Распределение целевой переменной в удалённых строках:
         0: 13 (100.0%)
   ✓ avg_glucose_level: все значения в диапазоне

--- 3. Удаление редких категорий ---
   ✓ gender: удалено 1 строк, редкие: ['Other']
      📊 Распределение целевой переменной в удалённых строках:
         0: 1 (100.0%)

📊 Статистика очистки собрана (removal_reasons, clipping_boundaries, removed_categories)
   Будет использована в итоговом отчёте preprocessing_report.txt

============================================================
📊 ИТОГИ УДАЛЕНИЯ АНОМАЛИЙ
============================================================

Причина удаления                         Строк          %
------------------------------------------------------------
Диапазон age [1, 82]                        43      0.84%
Диапазон bmi [10, 60]                       13      0.25%
Редкие в gender                              1      0.02%
------------------------------------------------------------
ВСЕГО УДАЛЕНО                               57      1.12%
ОСТАЛОСЬ СТРОК                            5053
============================================================

✓ Обработка аномалий завершена

In [ ]:
# 3.5 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ (после структурирования)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ")
    print("="*50)

    structure_backup_path = os.path.join(CHECKPOINT_PATH, '01_structure.csv')
    df.to_csv(structure_backup_path, index=False)

    print(f"\n✓ Контрольная точка сохранена:")
    print(f"   checkpoints/01_structure.csv")
    print(f"   Размер: {len(df)} строк, {len(df.columns)} колонок")

    print("\n" + "="*50 + "\n")

==================================================
💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ
==================================================

✓ Контрольная точка сохранена:
   checkpoints/01_structure.csv
   Размер: 5053 строк, 11 колонок

==================================================

# БЛОК 4. Очистка данных

In [ ]:
# 4.1 МЕХАНИЧЕСКАЯ ОЧИСТКА ТЕКСТА И КАТЕГОРИЙ

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🧼 МЕХАНИЧЕСКАЯ ОЧИСТКА")
    print("="*50)

    # --------------------------------------------
    # 1. Очистка текстовых колонок (из настроек)
    # --------------------------------------------
    print("\n--- 1. Текстовые колонки (из text_columns) ---")

    if text_columns:
        for col in text_columns:
            if col in df.columns:
                # Для категориальных колонок сначала преобразуем в object
                if df[col].dtype.name == 'category':
                    df[col] = df[col].astype(object)

                mask = df[col].notna()
                if mask.any():
                    df.loc[mask, col] = df.loc[mask, col].astype(str).str.strip().str.lower()
                print(f"   ✓ {col}: strip + lower")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")
    else:
        print("   ✓ Нет текстовых колонок в настройках")

    # --------------------------------------------
    # 2. Очистка категориальных колонок (ТОЛЬКО из настроек)
    # --------------------------------------------
    print("\n--- 2. Категориальные колонки (из categorical_columns) ---")

    if categorical_columns:
        for col in categorical_columns:
            if col in df.columns:
                # Для категориальных колонок сначала преобразуем в object
                if df[col].dtype.name == 'category':
                    df[col] = df[col].astype(object)

                mask = df[col].notna()
                if mask.any():
                    df.loc[mask, col] = df.loc[mask, col].astype(str).str.strip().str.lower()
                    df.loc[mask, col] = df.loc[mask, col].str.replace(' ', '_')

                print(f"   ✓ {col}: strip + lower + пробелы→'_'")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")
    else:
        print("   ✓ Нет категориальных колонок в настройках")

    # --------------------------------------------
    # 3. Предупреждение о необработанных object-колонках
    # --------------------------------------------
    print("\n--- 3. Проверка необработанных колонок ---")

    # Собираем все колонки, которые были обработаны
    processed_cols = set(text_columns) | set(categorical_columns)

    # Находим object-колонки, не попавшие в обработку
    unprocessed_object_cols = [
        col for col in df.select_dtypes(include=['object']).columns
        if col not in processed_cols
    ]

    if unprocessed_object_cols:
        print(f"   ⚠️ Обнаружены необработанные object-колонки:")
        for col in unprocessed_object_cols:
            print(f"      - {col}")
        print(f"   💡 Добавьте их в text_columns или categorical_columns в блоке 1.3")
    else:
        print("   ✓ Все object-колонки обработаны")

    # --------------------------------------------
    # 4. Проверка на появление 'nan' как строки
    # --------------------------------------------
    print("\n--- 4. Проверка на строки 'nan' ---")
    nan_string_cols = []
    for col in df.select_dtypes(include=['object', 'category']).columns:
        if (df[col] == 'nan').any():
            count = (df[col] == 'nan').sum()
            nan_string_cols.append(f"{col} ({count})")

    if nan_string_cols:
        print(f"   ⚠️ Обнаружены строки 'nan': {', '.join(nan_string_cols)}")
    else:
        print("   ✓ Строк 'nan' не обнаружено")

    print("\n" + "="*50)
    print("✓ Механическая очистка завершена")
    print("="*50 + "\n")

==================================================
🧼 МЕХАНИЧЕСКАЯ ОЧИСТКА
==================================================

--- 1. Текстовые колонки (из text_columns) ---
   ✓ Нет текстовых колонок в настройках

--- 2. Категориальные колонки (из categorical_columns) ---
   ✓ gender: strip + lower + пробелы→'_'
   ✓ ever_married: strip + lower + пробелы→'_'
   ✓ work_type: strip + lower + пробелы→'_'
   ✓ residence_type: strip + lower + пробелы→'_'
   ✓ smoking_status: strip + lower + пробелы→'_'

--- 3. Проверка необработанных колонок ---
   ✓ Все object-колонки обработаны

--- 4. Проверка на строки 'nan' ---
   ✓ Строк 'nan' не обнаружено

==================================================
✓ Механическая очистка завершена
==================================================

In [ ]:
# 4.2 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ (перед разбиением)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ")
    print("="*50)

    cleaned_backup_path = os.path.join(CHECKPOINT_PATH, '02_cleaned.csv')
    df.to_csv(cleaned_backup_path, index=False)

    print(f"\n✓ Контрольная точка сохранена:")
    print(f"   checkpoints/02_cleaned.csv")
    print(f"   Размер: {len(df)} строк, {len(df.columns)} колонок")

    print("\n" + "="*50 + "\n")

==================================================
💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ
==================================================

✓ Контрольная точка сохранена:
   checkpoints/02_cleaned.csv
   Размер: 5053 строк, 11 колонок

==================================================

# БЛОК 5. Разделение данных

In [ ]:
# 5.1 ПОДГОТОВКА К РАЗДЕЛЕНИЮ (СОЗДАНИЕ X И y)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🎯 ПОДГОТОВКА К РАЗДЕЛЕНИЮ")
    print("="*50)

    # Проверка целевой колонки
    if not TARGET_COLUMN:
        print("\n⚠️ ВНИМАНИЕ: Целевая колонка не указана!")
        print("   Укажите TARGET_COLUMN в блоке 1.3")
    elif TARGET_COLUMN not in df.columns:
        print(f"\n❌ ОШИБКА: Колонка '{TARGET_COLUMN}' не найдена")
        print(f"   Доступные колонки: {df.columns.tolist()}")
    else:
        # --------------------------------------------
        # Проверка на пропуски в целевой колонке (NaN)
        # --------------------------------------------
        null_count = df[TARGET_COLUMN].isna().sum()

        if null_count > 0:
            null_pct = null_count / len(df) * 100

            if null_pct > 10:
                print(f"\n🔴 КРИТИЧЕСКО: {null_pct:.1f}% пропусков в целевой колонке '{TARGET_COLUMN}!'")
                print("   Это не нормально. Проверьте источник данных.")
                print("   Возможные причины:")
                print("   • Ошибка при сборе данных")
                print("   • Пропуски не случайны (например, у тяжёлых пациентов)")
                print("\n   Невозможно продолжать обучение модели.")
                raise ValueError(f"Слишком много пропусков в целевой колонке: {null_pct:.1f}%")
            else:
                print(f"\n⚠️ Обнаружено {null_count} пропусков ({null_pct:.1f}%) в целевой колонке '{TARGET_COLUMN}'")
                print(f"   Удаляем строки с пропущенной целевой переменной...")
                df = df.dropna(subset=[TARGET_COLUMN])
                print(f"   ✓ Осталось {len(df)} строк")
                print(f"   ⚠️ Будьте внимательны: удаление строк с NaN в целевой переменной -")
                print(f"      единственно корректный способ обработки пропусков в y.")
        else:
            print(f"\n✓ Целевая колонка '{TARGET_COLUMN}' - пропусков нет")

        # --------------------------------------------
        # Отделение признаков (X) и цели (y)
        # --------------------------------------------
        print("\n--- Отделение X и y ---")

        X = df.drop(columns=[TARGET_COLUMN])
        y = df[TARGET_COLUMN]

        print(f"✓ Признаки X: {X.shape[0]} строк, {X.shape[1]} колонок")
        print(f"✓ Целевая переменная y: {len(y)} значений")

        # --------------------------------------------
        # Информация о целевой переменной
        # --------------------------------------------
        print("\n--- Информация о целевой переменной ---")

        if y.dtype in ['int64', 'Int64', 'float64', 'int32', 'float32']:
            print(f"   Тип: числовой")
            print(f"   Уникальных значений: {y.nunique()}")
            if y.nunique() <= 10:
                print(f"   Диапазон: {y.min()} - {y.max()}")
        else:
            print(f"   Тип: {y.dtype}")
            print(f"   Уникальных значений: {y.nunique()}")
            if y.nunique() <= 20:
                print(f"   Значения: {sorted(y.unique().tolist())}")

        # --------------------------------------------
        # Определение типа задачи
        # --------------------------------------------
        if FORCE_TASK_TYPE:
            is_classification = FORCE_TASK_TYPE == 'classification'
            task_source = "принудительно"
        else:
            # Исправлено: явные скобки для правильного приоритета
            is_classification = (y.dtype not in ['int64', 'Int64', 'float64', 'int32', 'float32']) or (y.nunique() <= 10)
            task_source = "автоопределение"

        # Сохраняем для использования в других блоках
        IS_CLASSIFICATION = is_classification

        print(f"\n📊 Тип задачи: {'классификация' if is_classification else 'регрессия'} ({task_source})")

        # --------------------------------------------
        # Анализ дисбаланса классов (для классификации)
        # --------------------------------------------
        if is_classification and y.nunique() <= 20:
            print("\n--- Анализ дисбаланса классов ---")

            class_counts = y.value_counts()
            total = len(y)
            n_classes = len(class_counts)
            max_count = class_counts.max()
            min_count = class_counts.min()
            ratio = max_count / min_count

            print(f"   Всего классов: {n_classes}")
            print(f"   Соотношение max/min: {ratio:.1f}:1")
            print(f"\n   Распределение:")
            for cls, count in class_counts.items():
                pct = count / total * 100
                bar = '█' * int(pct / 2)
                print(f"   Класс {cls}: {count:>6} ({pct:>5.1f}%) {bar}")

            if ratio > 3:
                print(f"\n   ⚠️ Обнаружен дисбаланс классов ({ratio:.1f}:1)")
                print("   💡 Рекомендации:")
                print("      - Использовать class_weight='balanced'")
                print("      - Или применить SMOTE для балансировки")
            elif ratio > 1.5:
                print(f"\n   ℹ️ Умеренный дисбаланс ({ratio:.1f}:1)")
                print("      Можно использовать class_weight='balanced'")
            else:
                print(f"\n   ✓ Классы сбалансированы ({ratio:.1f}:1)")
        else:
            print("\n--- Анализ дисбаланса ---")
            print("   ℹ️ Задача регрессии или много классов: не применимо")

        print("\n" + "="*50)
        print("✓ Подготовка к разделению завершена")
        print("="*50 + "\n")

==================================================
🎯 ПОДГОТОВКА К РАЗДЕЛЕНИЮ
==================================================

✓ Целевая колонка 'stroke' - пропусков нет

--- Отделение X и y ---
✓ Признаки X: 5053 строк, 10 колонок
✓ Целевая переменная y: 5053 значений

--- Информация о целевой переменной ---
   Тип: числовой
   Уникальных значений: 2
   Диапазон: 0 - 1

📊 Тип задачи: классификация (принудительно)

--- Анализ дисбаланса классов ---
   Всего классов: 2
   Соотношение max/min: 19.3:1

   Распределение:
   Класс 0:   4804 ( 95.1%) ███████████████████████████████████████████████
   Класс 1:    249 (  4.9%) ██

   ⚠️ Обнаружен дисбаланс классов (19.3:1)
   💡 Рекомендации:
      - Использовать class_weight='balanced'
      - Или применить SMOTE для балансировки

==================================================
✓ Подготовка к разделению завершена
==================================================

In [ ]:
# 5.2 РАЗДЕЛЕНИЕ НА ТРИ ВЫБОРКИ (TRAIN / VAL / TEST)

print("\n" + "="*50)
print("✂️ РАЗДЕЛЕНИЕ НА ВЫБОРКИ")
print("="*50)

# Проверка готовности
if not is_split_ready(df, X, TARGET_COLUMN):
    X_train = X_val = X_test = y_train = y_val = y_test = None
    print("❌ Разделение отменено")
else:
    # Определение типа задачи (используем переменную из блока 5.1)
    if 'IS_CLASSIFICATION' in globals():
        is_classification = IS_CLASSIFICATION
    else:
        # Fallback на случай, если блок 5.1 не выполнился
        if FORCE_TASK_TYPE:
            is_classification = FORCE_TASK_TYPE == 'classification'
        else:
            is_classification = (y.dtype not in ['int64', 'Int64', 'float64', 'int32', 'float32']) or (y.nunique() <= 10)

    # Проверка минимального размера
    min_samples = 30
    if len(X) < min_samples:
        print(f"\n⚠️ КРИТИЧЕСКОЕ ПРЕДУПРЕЖДЕНИЕ: Датасет слишком маленький!")
        print(f"   Текущий размер: {len(X)} строк")
        print(f"   Минимальный размер для разбиения: {min_samples} строк")
        print(f"\n   Рекомендации:")
        print(f"   - Собрать больше данных")
        print(f"   - Использовать кросс-валидацию вместо train/val/test")
        print(f"\n❌ Разделение отменено")
        X_train = X_val = X_test = y_train = y_val = y_test = None
    else:
        # Проверка маленьких классов
        if is_classification:
            class_counts = y.value_counts()
            small_classes = class_counts[class_counts < 3].index.tolist()
            if small_classes:
                print(f"\n⚠️ ВНИМАНИЕ: Обнаружены классы с < 3 примерами:")
                for cls in small_classes:
                    print(f"   Класс '{cls}': {class_counts[cls]} примеров")
                print(f"   Стратификация может работать некорректно")

        # Первое разделение: train + temp
        temp_size = SPLIT_VAL_SIZE + SPLIT_TEST_SIZE
        print(f"\n--- Шаг 1: train ({SPLIT_TRAIN_SIZE:.0%}) + temp ({temp_size:.0%}) ---")

        X_train, X_temp, y_train, y_temp = train_test_split(
            X, y,
            test_size=temp_size,
            random_state=RANDOM_STATE,
            stratify=y if is_classification else None
        )

        print(f"   Train: {len(X_train)} строк ({len(X_train)/len(X)*100:.1f}%)")
        print(f"   Temp:  {len(X_temp)} строк ({len(X_temp)/len(X)*100:.1f}%)")

        # Второе разделение: temp → val + test
        print(f"\n--- Шаг 2: temp → val ({SPLIT_VAL_SIZE:.0%}) + test ({SPLIT_TEST_SIZE:.0%}) ---")

        X_val, X_test, y_val, y_test = train_test_split(
            X_temp, y_temp,
            test_size=SPLIT_TEST_SIZE / temp_size,
            random_state=RANDOM_STATE,
            stratify=y_temp if is_classification else None
        )

        print(f"   Val:  {len(X_val)} строк ({len(X_val)/len(X)*100:.1f}%)")
        print(f"   Test: {len(X_test)} строк ({len(X_test)/len(X)*100:.1f}%)")

        # Итоговые размеры
        print("\n--- Итоговые размеры ---")
        print(f"   Train: {len(X_train):>6} ({len(X_train)/len(X)*100:>5.1f}%)")
        print(f"   Val:   {len(X_val):>6} ({len(X_val)/len(X)*100:>5.1f}%)")
        print(f"   Test:  {len(X_test):>6} ({len(X_test)/len(X)*100:>5.1f}%)")
        print(f"   Всего: {len(X):>6} (100%)")

        # Финальная проверка
        print("\n--- Финальная проверка ---")

        if len(X_train) == 0 or len(X_val) == 0 or len(X_test) == 0:
            print("   ❌ ОШИБКА: Одна из выборок пуста!")
        else:
            print("   ✓ Все выборки содержат данные")

        # Проверка классов в выборках
        if is_classification:
            train_classes = set(y_train.unique())
            val_classes = set(y_val.unique())
            test_classes = set(y_test.unique())
            all_classes = set(y.unique())

            if len(train_classes) < len(all_classes):
                missing = all_classes - train_classes
                print(f"   ⚠️ В train отсутствуют классы: {missing}")
            else:
                print(f"   ✓ Все классы присутствуют в train")

            # --------------------------------------------
            # ПРОВЕРКА МИНИМАЛЬНОГО КОЛИЧЕСТВА ПРИМЕРОВ РЕДКОГО КЛАССА
            # --------------------------------------------
            print("\n--- Проверка редких классов в выборках ---")

            MIN_RARE_CLASS_SAMPLES = 5  # порог для предупреждения

            val_class_counts = y_val.value_counts()
            test_class_counts = y_test.value_counts()

            min_val_count = val_class_counts.min()
            min_test_count = test_class_counts.min()
            min_val_class = val_class_counts.idxmin()
            min_test_class = test_class_counts.idxmin()

            warning_issued = False

            if min_val_count < MIN_RARE_CLASS_SAMPLES:
                print(f"   ⚠️ В val выборке класс '{min_val_class}' имеет только {min_val_count} примеров")
                print(f"      Это может быть недостаточно для надёжной оценки метрик")
                warning_issued = True

            if min_test_count < MIN_RARE_CLASS_SAMPLES:
                print(f"   ⚠️ В test выборке класс '{min_test_class}' имеет только {min_test_count} примеров")
                print(f"      Это может быть недостаточно для надёжной оценки метрик")
                warning_issued = True

            if warning_issued:
                print(f"\n   💡 Рекомендации:")
                print(f"      - Попробовать другой random_state (сейчас {RANDOM_STATE})")
                print(f"      - Увеличить размер val/test выборок")
                print(f"      - Рассмотреть stratified k-fold вместо фиксированного разбиения")
            else:
                print(f"   ✓ Все классы имеют ≥{MIN_RARE_CLASS_SAMPLES} примеров в val и test")

            # --------------------------------------------
            # ДЕТАЛЬНОЕ РАСПРЕДЕЛЕНИЕ КЛАССОВ
            # --------------------------------------------
            print("\n--- Распределение классов по выборкам ---")

            # Получаем распределение в исходных данных
            original_dist = y.value_counts(normalize=True)

            # Распределение по выборкам
            train_dist = y_train.value_counts(normalize=True)
            val_dist = y_val.value_counts(normalize=True)
            test_dist = y_test.value_counts(normalize=True)

            # Вывод таблицы
            print(f"\n   {'Класс':<10} {'Исходное':>10} {'Train':>10} {'Val':>10} {'Test':>10}")
            print("   " + "-" * 52)

            for cls in sorted(all_classes):
                orig_pct = original_dist.get(cls, 0) * 100
                train_pct = train_dist.get(cls, 0) * 100
                val_pct = val_dist.get(cls, 0) * 100
                test_pct = test_dist.get(cls, 0) * 100

                print(f"   {str(cls):<10} {orig_pct:>9.1f}% {train_pct:>9.1f}% {val_pct:>9.1f}% {test_pct:>9.1f}%")

            print("\n   Абсолютные значения:")
            print(f"   {'Класс':<10} {'Train':>10} {'Val':>10} {'Test':>10}")
            print("   " + "-" * 42)
            for cls in sorted(all_classes):
                train_abs = (y_train == cls).sum()
                val_abs = (y_val == cls).sum()
                test_abs = (y_test == cls).sum()
                print(f"   {str(cls):<10} {train_abs:>10} {val_abs:>10} {test_abs:>10}")

            # Проверка качества стратификации
            print("\n   📊 Проверка стратификации:")
            max_deviation = 0
            for cls in sorted(all_classes):
                orig = original_dist[cls]
                train_dev = abs(train_dist.get(cls, 0) - orig) / orig * 100
                val_dev = abs(val_dist.get(cls, 0) - orig) / orig * 100
                test_dev = abs(test_dist.get(cls, 0) - orig) / orig * 100
                max_deviation = max(max_deviation, train_dev, val_dev, test_dev)

            if max_deviation < 5:
                print("   ✓ Отклонение <5% - стратификация работает отлично")
            elif max_deviation < 10:
                print(f"   ⚡ Отклонение {max_deviation:.1f}% - стратификация приемлема")
            else:
                print(f"   ⚠️ Отклонение {max_deviation:.1f}% - возможен дисбаланс")

        # Параметры разбиения
        print(f"\n📌 Параметры разбиения:")
        print(f"   train={SPLIT_TRAIN_SIZE:.0%}, val={SPLIT_VAL_SIZE:.0%}, test={SPLIT_TEST_SIZE:.0%}")
        print(f"   random_state={RANDOM_STATE}")
        if is_classification:
            print(f"   stratify=True")

print("\n" + "="*50)
print("✓ Разделение завершено")
print("="*50 + "\n")

==================================================
✂️ РАЗДЕЛЕНИЕ НА ВЫБОРКИ
==================================================

--- Шаг 1: train (60%) + temp (40%) ---
   Train: 3031 строк (60.0%)
   Temp:  2022 строк (40.0%)

--- Шаг 2: temp → val (20%) + test (20%) ---
   Val:  1011 строк (20.0%)
   Test: 1011 строк (20.0%)

--- Итоговые размеры ---
   Train:   3031 ( 60.0%)
   Val:     1011 ( 20.0%)
   Test:    1011 ( 20.0%)
   Всего:   5053 (100%)

--- Финальная проверка ---
   ✓ Все выборки содержат данные
   ✓ Все классы присутствуют в train

--- Проверка редких классов в выборках ---
   ✓ Все классы имеют ≥5 примеров в val и test

--- Распределение классов по выборкам ---

   Класс        Исходное      Train        Val       Test
   ----------------------------------------------------
   0               95.1%      95.1%      95.1%      95.1%
   1                4.9%       4.9%       4.9%       4.9%

   Абсолютные значения:
   Класс           Train        Val       Test
   ------------------------------------------
   0                2882        961        961
   1                 149         50         50

   📊 Проверка стратификации:
   ✓ Отклонение <5% - стратификация работает отлично

📌 Параметры разбиения:
   train=60%, val=20%, test=20%
   random_state=99
   stratify=True

==================================================
✓ Разделение завершено
==================================================

# БЛОК 6. Анализ train

In [ ]:
# 6.1 ПРОВЕРКА НА ВЫБРОСЫ В TRAIN ВЫБОРКЕ

print("\n" + "="*50)
print("🔍 ПРОВЕРКА НА ВЫБРОСЫ (TRAIN)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    print(f"\n📐 Метод: IQR, коэффициент = {OUTLIER_IQR_COEFF}")

    # Находим числовые колонки
    numeric_cols_train = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()

    # Исключаем бинарные и low-cardinality колонки (для них IQR не имеет смысла)
    cols_to_skip = []
    for col in numeric_cols_train:
        unique_vals = X_train[col].nunique()
        if unique_vals <= 2:
            cols_to_skip.append(col)
        # Также исключаем целочисленные с ≤5 уникальными значениями (категориальные по сути)
        elif X_train[col].dtype in ['int64', 'Int64'] and unique_vals <= 5:
            cols_to_skip.append(col)

    numeric_cols_train = [col for col in numeric_cols_train if col not in cols_to_skip]

    if cols_to_skip:
        print(f"\n   ℹ️ Пропущены (бинарные/категориальные): {', '.join(cols_to_skip)}")

    # Проверка на NaN в числовых колонках
    if X_train[numeric_cols_train].isnull().any().any():
        print("\n⚠️ ВНИМАНИЕ: Обнаружены NaN в числовых колонках!")
        print("   Корреляция Пирсона будет рассчитана, но NaN игнорируются.")
        print("   Рекомендуется обработать пропуски в EDA перед корреляционным анализом.\n")

    if len(numeric_cols_train) == 0:
        print("\nℹ️ Нет числовых колонок для анализа корреляции")

    else:
        outlier_info = []

        for col in numeric_cols_train:
            Q1 = X_train[col].quantile(0.25)
            Q3 = X_train[col].quantile(0.75)
            IQR = Q3 - Q1

            # Защита от IQR = 0 (все значения одинаковые)
            if IQR == 0:
                continue

            lower_bound = Q1 - OUTLIER_IQR_COEFF * IQR
            upper_bound = Q3 + OUTLIER_IQR_COEFF * IQR

            outliers = X_train[(X_train[col] < lower_bound) | (X_train[col] > upper_bound)]
            outlier_count = len(outliers)
            outlier_pct = outlier_count / len(X_train) * 100

            # Определяем уровень
            if outlier_pct == 0:
                level = "🟢"
            elif outlier_pct < 5:
                level = "🟢"
            elif outlier_pct < 10:
                level = "🟡"
            else:
                level = "🔴"

            outlier_info.append({
                'col': col,
                'count': outlier_count,
                'pct': outlier_pct,
                'bounds': (lower_bound, upper_bound),
                'level': level
            })

        if outlier_info:
            print("\n⚠️ Обнаружены выбросы:\n")
            print(f"   {'':<3} {'Колонка':<22} {'Выбросов':>10} {'%':>8} {'Границы [низ, верх]':>32}")
            print("   " + "-" * 80)

            for info in outlier_info:
                bounds_str = f"[{info['bounds'][0]:.2f}, {info['bounds'][1]:.2f}]"
                print(f"   {info['level']} {info['col']:<20} {info['count']:>10} {info['pct']:>7.1f}% {bounds_str:>32}")

            # Сводка по уровням
            print("\n💡 Рекомендации:")

            high_outlier_cols = [info for info in outlier_info if info['pct'] > 10]
            medium_outlier_cols = [info for info in outlier_info if 5 <= info['pct'] <= 10]
            low_outlier_cols = [info for info in outlier_info if 0 < info['pct'] < 5]
            no_outlier_cols = [info for info in outlier_info if info['pct'] == 0]

            if high_outlier_cols:
                cols = ', '.join([info['col'] for info in high_outlier_cols])
                print(f"\n   🔴 Высокий % выбросов (>10%): {cols}")
                print("      → Проверьте данные на ошибки или используйте RobustScaler")

            if medium_outlier_cols:
                cols = ', '.join([info['col'] for info in medium_outlier_cols])
                print(f"\n   🟡 Умеренный % выбросов (5-10%): {cols}")
                print("      → Рассмотрите clipping (обрезание по квантилям)")

            if low_outlier_cols:
                cols = ', '.join([info['col'] for info in low_outlier_cols])
                print(f"\n   🟢 Низкий % выбросов (<5%): {cols}")
                print("      → Можно оставить, большинство моделей устойчивы")

            if no_outlier_cols:
                cols = ', '.join([info['col'] for info in no_outlier_cols])
                print(f"\n   ✅ Нет выбросов: {cols}")
        else:
            print("\n✅ Выбросов не обнаружено")

print("\n" + "="*50)
print("✓ Проверка на выбросы завершена")
print("="*50 + "\n")

==================================================
🔍 ПРОВЕРКА НА ВЫБРОСЫ (TRAIN)
==================================================

📐 Метод: IQR, коэффициент = 1.5

   ℹ️ Пропущены (бинарные/категориальные): hypertension, heart_disease

⚠️ ВНИМАНИЕ: Обнаружены NaN в числовых колонках!
   Корреляция Пирсона будет рассчитана, но NaN игнорируются.
   Рекомендуется обработать пропуски в EDA перед корреляционным анализом.


⚠️ Обнаружены выбросы:

       Колонка                  Выбросов        %              Границы [низ, верх]
   --------------------------------------------------------------------------------
   🟢 age                           0     0.0%                 [-26.50, 113.50]
   🔴 avg_glucose_level           359    11.8%                  [22.79, 168.14]
   🟢 bmi                          60     2.0%                    [9.40, 47.00]

💡 Рекомендации:

   🔴 Высокий % выбросов (>10%): avg_glucose_level
      → Проверьте данные на ошибки или используйте RobustScaler

   🟢 Низкий % выбросов (<5%): bmi
      → Можно оставить, большинство моделей устойчивы

   ✅ Нет выбросов: age

==================================================
✓ Проверка на выбросы завершена
==================================================

In [ ]:
# 6.2 КОРРЕЛЯЦИЯ ЧИСЛОВЫХ ПРИЗНАКОВ (TRAIN)

print("\n" + "="*50)
print("📈 КОРРЕЛЯЦИЯ ЧИСЛОВЫХ ПРИЗНАКОВ (TRAIN)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    # Находим числовые колонки
    numeric_cols_train = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()

    # Исключаем бинарные и low-cardinality колонки (как в 6.1)
    cols_to_skip = []
    for col in numeric_cols_train:
        unique_vals = X_train[col].nunique()
        if unique_vals <= 2:
            cols_to_skip.append(col)
        elif X_train[col].dtype in ['int64', 'Int64'] and unique_vals <= 5:
            cols_to_skip.append(col)

    numeric_cols_train = [col for col in numeric_cols_train if col not in cols_to_skip]

    if cols_to_skip:
        print(f"\n   ℹ️ Пропущены (бинарные/категориальные): {', '.join(cols_to_skip)}")
        print(f"      Корреляция Пирсона для них не интерпретируется корректно")

    if len(numeric_cols_train) == 0:
        print("\nℹ️ Нет числовых колонок для анализа корреляции")
    elif len(numeric_cols_train) == 1:
        print(f"\nℹ️ Только одна числовая колонка: {numeric_cols_train[0]}")
        print("   Корреляцию посчитать невозможно")
    else:
        corr_matrix = X_train[numeric_cols_train].corr()

        # Поиск сильных корреляций (>0.7)
        high_corr_pairs = []
        for i in range(len(corr_matrix.columns)):
            for j in range(i+1, len(corr_matrix.columns)):
                corr_value = corr_matrix.iloc[i, j]
                if abs(corr_value) > 0.7:
                    high_corr_pairs.append((corr_matrix.columns[i], corr_matrix.columns[j], corr_value))

        if high_corr_pairs:
            print("\n⚠️ Обнаружены сильные корреляции (|r| > 0.7):\n")
            for col1, col2, corr in high_corr_pairs:
                # Определяем цвет по силе корреляции
                if abs(corr) > 0.9:
                    level = "🔴"
                elif abs(corr) > 0.8:
                    level = "🟠"
                elif abs(corr) > 0.7:
                    level = "🟡"
                else:
                    level = "🟢"

                direction = "→" if corr > 0 else "←"
                print(f"   {level} {col1} {direction} {col2}: {corr:+.2f}")

            print("\n💡 Рекомендации:")
            print("   • Для линейных моделей (LR, Ridge): удалите один из пары")
            print("   • Для tree-based (RF, XGBoost): можно оставить оба")
            print("   • Рассмотрите PCA для уменьшения размерности")
        else:
            print("\n✅ Сильных корреляций (|r| > 0.7) не обнаружено")

        # Топ-5 корреляций с цветовой индикацией
        print("\n📊 Топ-5 по абсолютной величине:\n")

        corr_pairs = []
        for i in range(len(corr_matrix.columns)):
            for j in range(i+1, len(corr_matrix.columns)):
                corr_pairs.append((
                    corr_matrix.columns[i],
                    corr_matrix.columns[j],
                    corr_matrix.iloc[i, j]
                ))

        corr_pairs.sort(key=lambda x: abs(x[2]), reverse=True)

        print(f"   {'':<3} {'Пара признаков':<40} {'Корреляция':>12}")
        print("   " + "-" * 58)

        for i, (col1, col2, corr) in enumerate(corr_pairs[:5], 1):
            abs_corr = abs(corr)

            # Определяем цвет по силе корреляции
            if abs_corr > 0.7:
                level = "🔴"
            elif abs_corr > 0.5:
                level = "🟠"
            elif abs_corr > 0.3:
                level = "🟡"
            else:
                level = "🟢"

            direction = "→" if corr > 0 else "←"
            pair_str = f"{col1} {direction} {col2}"
            print(f"   {level} {pair_str:<38} {corr:>+10.2f}")

        # Сводка по уровням корреляции
        print("\n💡 Градация:")
        print("   🔴 Сильная (|r| > 0.7)  - высокая мультиколлинеарность")
        print("   🟠 Средняя (|r| > 0.5)  - умеренная связь")
        print("   🟡 Слабая (|r| > 0.3)   - заметная связь")
        print("   🟢 Очень слабая (|r| ≤ 0.3) - практически нет связи")

print("\n" + "="*50)
print("✓ Анализ корреляции завершён")
print("="*50 + "\n")

==================================================
📈 КОРРЕЛЯЦИЯ ЧИСЛОВЫХ ПРИЗНАКОВ (TRAIN)
==================================================

   ℹ️ Пропущены (бинарные/категориальные): hypertension, heart_disease
      Корреляция Пирсона для них не интерпретируется корректно

✅ Сильных корреляций (|r| > 0.7) не обнаружено

📊 Топ-5 по абсолютной величине:

       Пара признаков                             Корреляция
   ----------------------------------------------------------
   🟡 age → bmi                                   +0.36
   🟢 age → avg_glucose_level                     +0.24
   🟢 avg_glucose_level → bmi                     +0.20

💡 Градация:
   🔴 Сильная (|r| > 0.7)  - высокая мультиколлинеарность
   🟠 Средняя (|r| > 0.5)  - умеренная связь
   🟡 Слабая (|r| > 0.3)   - заметная связь
   🟢 Очень слабая (|r| ≤ 0.3) - практически нет связи

==================================================
✓ Анализ корреляции завершён
==================================================

In [ ]:
# 6.3 ПРОВЕРКА НА МУЛЬТИКОЛЛИНЕАРНОСТЬ (VIF)

print("\n" + "="*50)
print("🔗 МУЛЬТИКОЛЛИНЕАРНОСТЬ (VIF)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    numeric_cols_train = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()

    # Исключаем бинарные и low-cardinality колонки
    cols_to_skip = []
    for col in numeric_cols_train:
        unique_vals = X_train[col].nunique()
        if unique_vals <= 2:
            cols_to_skip.append(col)
        elif X_train[col].dtype in ['int64', 'Int64'] and unique_vals <= 5:
            cols_to_skip.append(col)

    numeric_cols_vif = [col for col in numeric_cols_train if col not in cols_to_skip]

    if cols_to_skip:
        print(f"\n   ℹ️ Пропущены (бинарные/категориальные): {', '.join(cols_to_skip)}")
        print(f"      VIF для бинарных переменных интерпретируется неоднозначно")

    # --------------------------------------------
    # ПРОВЕРКА ПРОПУСКОВ. ИСКЛЮЧАЕМ КОЛОНКИ С NaN
    # --------------------------------------------
    null_counts = X_train[numeric_cols_vif].isnull().sum()
    cols_with_nulls = null_counts[null_counts > 0].index.tolist()

    if cols_with_nulls:
        print(f"\n⚠️ Обнаружены пропуски в колонках: {cols_with_nulls}")
        print(f"   ❌ Исключены из VIF (из-за пропусков): {cols_with_nulls}")
        print(f"   После обработки пропусков в EDA пересчитайте VIF при необходимости.")

        # Исключаем колонки с пропусками
        numeric_cols_vif = [col for col in numeric_cols_vif if col not in cols_with_nulls]

    if len(numeric_cols_vif) <= 1:
        print(f"\nℹ️ Недостаточно непрерывных числовых колонок для VIF (нужно ≥2)")
        print(f"   Найдено: {len(numeric_cols_vif)}")
    else:
        print(f"\n✅ Данные готовы: {len(numeric_cols_vif)} непрерывных числовых колонок без пропусков")

        try:
            from statsmodels.stats.outliers_influence import variance_inflation_factor
            from statsmodels.tools.tools import add_constant

            # Подготовка данных
            X_vif = X_train[numeric_cols_vif].copy()
            for col in X_vif.columns:
                if X_vif[col].dtype == 'Int64':
                    X_vif[col] = X_vif[col].astype(float)

            X_vif_const = add_constant(X_vif)

            # Расчёт VIF
            vif_data = []
            for i in range(1, len(X_vif_const.columns)):
                vif = variance_inflation_factor(X_vif_const.values, i)
                vif_data.append({
                    "feature": X_vif_const.columns[i],
                    "VIF": round(vif, 2)
                })

            vif_data.sort(key=lambda x: x["VIF"], reverse=True)

            # Анализ результатов
            high_vif = [v for v in vif_data if v["VIF"] > 10]
            moderate_vif = [v for v in vif_data if 5 < v["VIF"] <= 10]

            print("\n📊 РЕЗУЛЬТАТЫ VIF:\n")

            if high_vif:
                print("🔴 Высокая мультиколлинеарность (VIF > 10):")
                for v in high_vif:
                    print(f"   {v['feature']}: VIF = {v['VIF']}")
                print("\n💡 Рекомендация: удалите признаки с VIF > 10")
                print("   (начиная с самого высокого, пересчитывая VIF после каждого удаления)")

            if moderate_vif:
                print("🟡 Умеренная мультиколлинеарность (5 < VIF ≤ 10):")
                for v in moderate_vif:
                    print(f"   {v['feature']}: VIF = {v['VIF']}")
                if not high_vif:
                    print("\n💡 Рекомендация: можно оставить, но следите за интерпретацией коэффициентов")

            if not high_vif and not moderate_vif:
                print("🟢 Мультиколлинеарность в норме (VIF ≤ 5)")

            # Топ-5 VIF
            print("\n📈 Топ-5 VIF:")
            for i, v in enumerate(vif_data[:5], 1):
                if v["VIF"] > 10:
                    icon = "🔴"
                elif v["VIF"] > 5:
                    icon = "🟡"
                else:
                    icon = "🟢"
                print(f"   {icon} {i}. {v['feature']}: {v['VIF']}")

        except ImportError:
            print("\n⚠️ statsmodels не установлен")
            print("   Выполните: !pip install statsmodels")
        except Exception as e:
            print(f"\n⚠️ Ошибка при расчёте VIF: {e}")

print("\n" + "="*50)
print("✓ Проверка мультиколлинеарности завершена")
print("="*50 + "\n")

==================================================
🔗 МУЛЬТИКОЛЛИНЕАРНОСТЬ (VIF)
==================================================

   ℹ️ Пропущены (бинарные/категориальные): hypertension, heart_disease
      VIF для бинарных переменных интерпретируется неоднозначно

⚠️ Обнаружены пропуски в колонках: ['bmi']
   ❌ Исключены из VIF (из-за пропусков): ['bmi']
   После обработки пропусков в EDA пересчитайте VIF при необходимости.

✅ Данные готовы: 2 непрерывных числовых колонок без пропусков

📊 РЕЗУЛЬТАТЫ VIF:

🟢 Мультиколлинеарность в норме (VIF ≤ 5)

📈 Топ-5 VIF:
   🟢 1. age: 1.06
   🟢 2. avg_glucose_level: 1.06

==================================================
✓ Проверка мультиколлинеарности завершена
==================================================

In [ ]:
# 6.4 РЕКОМЕНДАЦИИ ПО КОДИРОВАНИЮ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ

print("\n" + "="*50)
print("🏷️ КОДИРОВАНИЕ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    categorical_cols_train = X_train.select_dtypes(include=['category', 'object']).columns.tolist()

    if len(categorical_cols_train) == 0:
        print("\nℹ️ Нет категориальных признаков для анализа")
    else:
        print(f"\n📊 Найдено категориальных признаков: {len(categorical_cols_train)}\n")

        _summary = []

        for col in categorical_cols_train:
            unique_count = X_train[col].nunique()
            total_count = len(X_train[col])
            top_cat = X_train[col].value_counts().head(2)
            top1_pct = (top_cat.iloc[0] / total_count) * 100

            # Определяем рекомендацию и уровень
            if unique_count == 2:
                rec_linear = "ручной маппинг ({'A':0, 'B':1})"
                rec_tree = "ручной маппинг или оставить как есть"
                recommendation = f"{rec_linear} (линейные) / {rec_tree} (деревья)"
                priority = "🟢"
                priority_desc = "идеально"
            elif unique_count <= 5:
                rec_linear = f"OneHotEncoder ({unique_count} колонок)"
                rec_tree = "OrdinalEncoder или оставить как category"
                recommendation = f"{rec_linear} (линейные) / {rec_tree} (деревья)"
                priority = "🟢"
                priority_desc = "отлично"
            elif unique_count <= 10:
                rec_linear = f"OneHotEncoder ({unique_count} колонок, осторожно)"
                rec_tree = "OrdinalEncoder или TargetEncoder"
                recommendation = f"{rec_linear} (линейные) / {rec_tree} (деревья)"
                priority = "🟡"
                priority_desc = "нормально"
            elif unique_count <= 50:
                rec = "TargetEncoder (обязательно с cross-validation!)"
                recommendation = f"{rec} (для любых моделей)"
                priority = "🟠"
                priority_desc = "осторожно"
            else:
                rec = "TargetEncoder (с CV + smoothing) или FeatureHasher"
                recommendation = f"{rec} (для высококардинальных)"
                priority = "🔴"
                priority_desc = "проблема"

            # Добавляем предупреждение для TargetEncoder
            if unique_count > 10:
                print(f"      ⚠️⚠️⚠️ TargetEncoder требует КРОСС-ВАЛИДАЦИЮ внутри train, иначе target leakage!")

            _summary.append({
                'col': col,
                'unique': unique_count,
                'top_cat': top_cat.index[0],
                'top_pct': top1_pct,
                'rec': recommendation,
                'priority': priority,
                'priority_desc': priority_desc
            })

            print(f"   {priority} {col}:")
            print(f"      Уникальных значений: {unique_count}")
            print(f"      Топ: '{top_cat.index[0]}' ({top1_pct:.1f}%)")

            if unique_count == 2:
                print(f"      → Ручной маппинг в EDA (напр., {{'Yes': 1, 'No': 0}})")
            elif unique_count <= 5:
                print(f"      → OneHotEncoder ({unique_count} колонок)")
            elif unique_count <= 10:
                print(f"      → OneHotEncoder ({unique_count} колонок)")
                if top1_pct > 90:
                    print(f"      ⚠️ Доминирующая категория ({top1_pct:.1f}%)")
            elif unique_count <= 50:
                print(f"      → TargetEncoder / FrequencyEncoder")
            else:
                print(f"      → TargetEncoder / FeatureHasher")
                print(f"      ⚠️ Высокая кардинальность ({unique_count} значений)")
            print()

        # Сводная таблица
        print("   " + "-"*70)
        print("\n📋 СВОДКА ПО ВСЕМ КАТЕГОРИАЛЬНЫМ ПРИЗНАКАМ:\n")
        print(f"   {'':<3} {'Признак':<18} {'Уник':>6} {'Топ %':>7} {'Рекомендация':<32}")
        print("   " + "-"*70)

        for s in _summary:
            print(f"   {s['priority']} {s['col']:<15} {s['unique']:>6} {s['top_pct']:>6.1f}% {s['rec']:<32}")

        # Градация
        print("\n   " + "-"*70)
        print("\n📖 ГРАДАЦИЯ:")
        print("   🟢 Зелёный  → низкая кардинальность (≤5)")
        print("   🟡 Жёлтый   → средняя кардинальность (6-10)")
        print("   🟠 Оранжевый → высокая кардинальность (11-50)")
        print("   🔴 Красный  → очень высокая кардинальность (>50)")

        # Общие рекомендации
        print("\n💡 ЧТО ДЕЛАТЬ В EDA:")
        print("   • Бинарные (2 значения) → ручной маппинг через .map()")
        print("   • Низкокардинальные (≤10) → OneHotEncoder (drop='first')")
        print("   • Среднекардинальные (11-50) → TargetEncoder или FrequencyEncoder")
        print("   • Высококардинальные (>50) → TargetEncoder или FeatureHasher")

        print("\n📌 ПО ТИПУ МОДЕЛИ:")
        print("   • Линейные модели → OneHotEncoder или TargetEncoder")
        print("   • Деревья (RF, XGBoost) → OrdinalEncoder (не LabelEncoder!)")
        print("   • CatBoost → встроенная обработка категорий")

        print("\n⚠️ ВАЖНО:")
        print("   • Кодирование выполняется в EDA ноутбуке, не здесь")
        print("   • При OneHotEncoding используйте drop='first'")
        print("   • TargetEncoder считайте ТОЛЬКО на train")

print("\n" + "="*50)
print("✓ Анализ категориальных признаков завершён")
print("="*50 + "\n")

==================================================
🏷️ КОДИРОВАНИЕ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ
==================================================

ℹ️ Нет категориальных признаков для анализа

==================================================
✓ Анализ категориальных признаков завершён
==================================================

In [ ]:
# 6.5 ПРОВЕРКА НА КОНСТАНТНЫЕ И НИЗКОВАРИАТИВНЫЕ ПРИЗНАКИ

print("\n" + "="*50)
print("🔒 ПРОВЕРКА НА БЕСПОЛЕЗНЫЕ ПРИЗНАКИ (TRAIN)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    constant_cols = []
    near_constant_cols = []
    low_variance_cols = []

    for col in X_train.columns:
        unique_count = X_train[col].nunique()

        if unique_count == 1:
            constant_cols.append(col)
        elif unique_count == 2:
            value_counts = X_train[col].value_counts(normalize=True)
            max_ratio = value_counts.max()
            # Пороги: 99% - почти константные, 95% - низковариативные
            if max_ratio > 0.99:
                near_constant_cols.append((col, max_ratio))
            elif max_ratio > 0.95:
                low_variance_cols.append((col, unique_count, max_ratio))

    # ========================================
    # 1. КОНСТАНТНЫЕ ПРИЗНАКИ (1 уникальное значение)
    # ========================================
    if constant_cols:
        print("\n🔴 КОНСТАНТНЫЕ КОЛОНКИ (только одно значение):\n")
        for col in constant_cols:
            value = X_train[col].iloc[0]
            print(f"   • {col}: '{value}'")

        print("\n💡 РЕКОМЕНДАЦИЯ:")
        print("   Константные признаки можно удалить на ЛЮБОМ этапе, так как они не несут информации:")
        print("   • Вариант 1: Удалить сейчас через columns_to_drop (блок 1.3)")
        print("   • Вариант 2: Оставить для анализа в EDA, удалить позже")
        print("   • Вариант 3: Игнорировать в модели (многие алгоритмы автоматически их не используют)")
        print("\n📌 Если решили удалить сейчас, добавьте в блок 1.3:")
        print(f"   columns_to_drop = {constant_cols}")
    else:
        print("\n🟢 Константных колонок нет")

    # ========================================
    # 2. ПОЧТИ КОНСТАНТНЫЕ (>99% одно значение)
    # ========================================
    if near_constant_cols:
        print("\n🟡 ПОЧТИ КОНСТАНТНЫЕ (>99% одно значение):\n")
        for col, ratio in near_constant_cols:
            print(f"   • {col}: {ratio*100:.1f}% - одно значение")

        print("\n💡 РЕКОМЕНДАЦИЯ:")
        print("   Почти константные признаки имеют очень низкую дисперсию.")
        print("   • Для линейных моделей: лучше удалить (не добавят информации)")
        print("   • Для деревьев: можно оставить (алгоритм сам их проигнорирует)")
        print("   • Решение: проверьте в EDA, нет ли редких, но важных значений")
    else:
        print("\n🟢 Почти константных колонок (>99%) нет")

    # ========================================
    # 3. НИЗКОВАРИАТИВНЫЕ (>95% одно значение)
    # ========================================
    if low_variance_cols:
        print("\n🟠 НИЗКОВАРИАТИВНЫЕ (>95% одно значение):\n")
        for col, unique_count, max_ratio in low_variance_cols:
            print(f"   • {col}: {unique_count} значений, {max_ratio*100:.1f}% доминирует")

        print("\n💡 РЕКОМЕНДАЦИЯ:")
        print("   Низковариативные признаки имеют сильный дисбаланс внутри себя.")
        print("   • Для задач с дисбалансом целевой переменной:")
        print("     Редкое значение может быть критически важным!")
        print("   • Рекомендация: НЕ удалять без анализа в EDA")
        print("   • Проверьте в EDA корреляцию с целевой переменной")
    else:
        print("\n🟢 Низковариативных колонок (>95%) нет")

    # ========================================
    # 4. СВОДКА
    # ========================================
    print("\n" + "-"*50)
    print("\n📊 СВОДКА:")
    print(f"   Всего признаков: {len(X_train.columns)}")
    print(f"   🔴 Константных: {len(constant_cols)}")
    print(f"   🟡 Почти константных (>99%): {len(near_constant_cols)}")
    print(f"   🟠 Низковариативных (>95%): {len(low_variance_cols)}")
    print(f"   🟢 Нормальных: {len(X_train.columns) - len(constant_cols) - len(near_constant_cols) - len(low_variance_cols)}")

    if constant_cols or near_constant_cols:
        print("\n⚠️ Если удалили константные или почти константные признаки через columns_to_drop,")
        print("   рекомендуется перезапустить пайплайн для обновления сплитов и метаданных.")

print("\n" + "="*50)
print("✓ Проверка завершена")
print("="*50 + "\n")

==================================================
🔒 ПРОВЕРКА НА БЕСПОЛЕЗНЫЕ ПРИЗНАКИ (TRAIN)
==================================================

🟢 Константных колонок нет

🟢 Почти константных колонок (>99%) нет

🟢 Низковариативных колонок (>95%) нет

--------------------------------------------------

📊 СВОДКА:
   Всего признаков: 10
   🔴 Константных: 0
   🟡 Почти константных (>99%): 0
   🟠 Низковариативных (>95%): 0
   🟢 Нормальных: 10

==================================================
✓ Проверка завершена
==================================================

# БЛОК 7. Сохранение и итоги

In [ ]:
# 7.1 СОХРАНЕНИЕ ВЫБОРОК, МЕТАДАННЫХ И ЕДИНОГО ОТЧЁТА

print("\n" + "="*50)
print("💾 СОХРАНЕНИЕ ВЫБОРОК И МЕТАДАННЫХ")
print("="*50)

if not is_train_ready(X_train):
    print("\n⚠️ Пропускаем: выборки не созданы")
else:
    # --------------------------------------------
    # Сохранение признаков (X)
    # --------------------------------------------
    print("\n--- Сохранение признаков (X) ---")

    X_train_path = os.path.join(SPLITS_PATH, 'X_train.csv')
    X_val_path = os.path.join(SPLITS_PATH, 'X_val.csv')
    X_test_path = os.path.join(SPLITS_PATH, 'X_test.csv')

    X_train.to_csv(X_train_path, index=False)
    X_val.to_csv(X_val_path, index=False)
    X_test.to_csv(X_test_path, index=False)

    print(f"   ✓ X_train.csv ({len(X_train)} строк, {len(X_train.columns)} признаков)")
    print(f"   ✓ X_val.csv ({len(X_val)} строк)")
    print(f"   ✓ X_test.csv ({len(X_test)} строк)")

    # --------------------------------------------
    # Сохранение целевой переменной (y)
    # --------------------------------------------
    print("\n--- Сохранение целевой переменной (y) ---")

    y_train_path = os.path.join(SPLITS_PATH, 'y_train.csv')
    y_val_path = os.path.join(SPLITS_PATH, 'y_val.csv')
    y_test_path = os.path.join(SPLITS_PATH, 'y_test.csv')

    y_train.to_csv(y_train_path, index=False, header=True)
    y_val.to_csv(y_val_path, index=False, header=True)
    y_test.to_csv(y_test_path, index=False, header=True)

    print(f"   ✓ y_train.csv ({len(y_train)} значений)")
    print(f"   ✓ y_val.csv ({len(y_val)} значений)")
    print(f"   ✓ y_test.csv ({len(y_test)} значений)")

    # --------------------------------------------
    # Проверка сохранённых файлов
    # --------------------------------------------
    print("\n--- Проверка сохранённых файлов ---")

    expected_files = ['X_train.csv', 'X_val.csv', 'X_test.csv',
                      'y_train.csv', 'y_val.csv', 'y_test.csv']

    saved_files = os.listdir(SPLITS_PATH)
    missing_files = [f for f in expected_files if f not in saved_files]

    if missing_files:
        print(f"   ⚠️ Не найдены файлы: {missing_files}")
    else:
        print(f"   ✓ Все 6 файлов сохранены в: {SPLITS_PATH}")

    # --------------------------------------------
    # Определение типа задачи
    # --------------------------------------------
    if FORCE_TASK_TYPE:
        task_type = FORCE_TASK_TYPE
    else:
        if y.dtype in ['int64', 'Int64', 'float64'] and y.nunique() > 10:
            task_type = "regression"
        else:
            task_type = "classification"

    # --------------------------------------------
    # Сбор версий пакетов
    # --------------------------------------------
    package_versions = {
        "python": sys.version.split()[0],
        "pandas": pd.__version__,
        "numpy": np.__version__,
        "scikit-learn": sklearn.__version__
    }

    try:
        import statsmodels
        package_versions["statsmodels"] = statsmodels.__version__
    except ImportError:
        pass

    # --------------------------------------------
    # DATA CONTRACT (явный контракт для EDA)
    # --------------------------------------------

    # Собираем исходные типы колонок из настроек
    categorical_columns_original = categorical_columns if 'categorical_columns' in globals() else []
    int_columns_original = int_columns if 'int_columns' in globals() else []
    float_columns_original = float_columns if 'float_columns' in globals() else []

    # Преобразуем dtypes в строки для JSON
    x_dtypes_str = {}
    for col, dtype in X_train.dtypes.items():
        # Обрабатываем Int64 (pandas extension type)
        if hasattr(dtype, 'name'):
            x_dtypes_str[col] = dtype.name
        else:
            x_dtypes_str[col] = str(dtype)

    data_contract = {
        "version": "1.0",
        "description": "Контракт между preprocessing и EDA. EDA должен соблюдать этот формат.",
        "X_train": {
            "file": "X_train.csv",
            "format": "csv",
            "index": False,
            "encoding": "utf-8",
            "dtypes": x_dtypes_str,
            "shape": list(X_train.shape)
        },
        "y_train": {
            "file": "y_train.csv",
            "format": "csv",
            "index": False,
            "encoding": "utf-8",
            "dtype": str(y_train.dtype),
            "shape": len(y_train)
        },
        "X_val": {
            "file": "X_val.csv",
            "format": "csv",
            "index": False,
            "encoding": "utf-8",
            "shape": list(X_val.shape)
        },
        "X_test": {
            "file": "X_test.csv",
            "format": "csv",
            "index": False,
            "encoding": "utf-8",
            "shape": list(X_test.shape)
        },
        "guaranteed_columns": X_train.columns.tolist(),
        "categorical_columns_hint": categorical_columns_original,
        "numerical_columns_hint": int_columns_original + float_columns_original,
        "target_column": TARGET_COLUMN
    }

    # --------------------------------------------
    # Подготовка метаданных
    # --------------------------------------------
    metadata = {
        "project_name": str(PROJECT_NAME),
        "base_path": str(BASE_PATH),
        "cycle_number": CYCLE_NUMBER,
        "target_column": str(TARGET_COLUMN),
        "task_type": task_type,
        "feature_names": X_train.columns.tolist(),
        "feature_count": len(X_train.columns),
        "train_size": len(X_train),
        "val_size": len(X_val),
        "test_size": len(X_test),
        "total_size": len(X),
        "split_ratio": {
            "train": SPLIT_TRAIN_SIZE,
            "val": SPLIT_VAL_SIZE,
            "test": SPLIT_TEST_SIZE
        },
        "random_state": RANDOM_STATE,
        "date_processed": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "has_missing_values": bool(df.isnull().sum().sum() > 0),
        "package_versions": package_versions,
        "data_contract": data_contract
    }

    # Информация о классах (для классификации)
    if task_type == "classification":
        metadata["classes"] = [str(cls) for cls in sorted(y.unique().tolist())]
        metadata["class_count"] = y.nunique()
        train_dist = y_train.value_counts().to_dict()
        metadata["train_class_distribution"] = {str(k): int(v) for k, v in train_dist.items()}
    else:
        metadata["target_min"] = float(y.min()) if not pd.isna(y.min()) else None
        metadata["target_max"] = float(y.max()) if not pd.isna(y.max()) else None
        metadata["target_mean"] = float(y.mean()) if not pd.isna(y.mean()) else None

    # --------------------------------------------
    # Сохранение метаданных в JSON
    # --------------------------------------------
    print("\n--- Сохранение метаданных ---")

    metadata_serializable = convert_to_serializable(metadata)

    metadata_path = os.path.join(PREPROCESSING_PATH, 'metadata.json')
    with open(metadata_path, 'w', encoding='utf-8') as f:
        json.dump(metadata_serializable, f, ensure_ascii=False, indent=2)

    print(f"   ✓ metadata.json сохранён")

    # --------------------------------------------
    # СОЗДАНИЕ ЕДИНОГО ОТЧЁТА preprocessing_report.txt
    # --------------------------------------------
    print("\n--- Создание единого отчёта ---")

    report_lines = []
    report_lines.append("=" * 70)
    report_lines.append("ОТЧЁТ ПО ПРЕДОБРАБОТКЕ ДАННЫХ")
    report_lines.append("=" * 70)
    report_lines.append(f"Проект: {PROJECT_NAME}")
    report_lines.append(f"Цикл: {CYCLE_NUMBER}")
    report_lines.append(f"Дата: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append("")

    # ========== РАЗДЕЛ 1: ИСХОДНЫЕ ДАННЫЕ ==========
    report_lines.append("=" * 70)
    report_lines.append("1. ИСХОДНЫЕ ДАННЫЕ")
    report_lines.append("=" * 70)
    report_lines.append(f"Размер: {df.shape[0]} строк, {df.shape[1]} колонок")
    report_lines.append(f"Целевая переменная: {TARGET_COLUMN}")
    report_lines.append(f"Тип задачи: {task_type}")

    # Список колонок (если >20 - сокращаем)
    all_cols = df.columns.tolist()
    if len(all_cols) <= 20:
        report_lines.append(f"Колонки: {all_cols}")
    else:
        report_lines.append(f"Колонки (первые 20): {all_cols[:20]}... (всего {len(all_cols)})")

    # Пропуски в исходных данных
    missing_before = df.isnull().sum()
    missing_before = missing_before[missing_before > 0]
    if len(missing_before) > 0:
        report_lines.append("Пропуски:")
        for col, count in missing_before.items():
            pct = count / len(df) * 100
            report_lines.append(f"   {col}: {count} ({pct:.2f}%)")
    else:
        report_lines.append("Пропуски: нет")

    # Дубликаты
    duplicates_count = df.duplicated().sum()
    report_lines.append(f"Дубликаты строк: {duplicates_count}")
    report_lines.append("")

    # ========== РАЗДЕЛ 2: НАСТРОЙКИ ОЧИСТКИ ==========
    report_lines.append("=" * 70)
    report_lines.append("2. НАСТРОЙКИ ОЧИСТКИ")
    report_lines.append("=" * 70)

    # Пропуски
    report_lines.append(f"Удаление пропусков: {DROP_ROWS_WITH_NULLS}")
    if DROP_ROWS_WITH_NULLS and COLUMNS_TO_CHECK_NULLS:
        report_lines.append(f"   Колонки для проверки: {COLUMNS_TO_CHECK_NULLS}")

    # Диапазоны
    report_lines.append(f"Удаление вне диапазонов: {DROP_OUT_OF_RANGE}")
    if DROP_OUT_OF_RANGE and NUMERIC_RANGES:
        for col, (min_v, max_v) in NUMERIC_RANGES.items():
            report_lines.append(f"   {col}: [{min_v}, {max_v}]")

    # Редкие категории
    report_lines.append(f"Удаление редких категорий: {DROP_RARE_CATEGORIES}")
    if DROP_RARE_CATEGORIES:
        report_lines.append(f"   Порог: {RARE_CATEGORY_THRESHOLD:.1%}")
        report_lines.append(f"   Колонки для проверки: {COLUMNS_TO_CHECK_RARE}")

    # IQR для выбросов (только для информации)
    report_lines.append(f"Коэффициент IQR (анализ): {OUTLIER_IQR_COEFF}")
    report_lines.append("")

    # ========== РАЗДЕЛ 3: ЛОГ УДАЛЕНИЯ СТРОК ==========
    report_lines.append("=" * 70)
    report_lines.append("3. ЛОГ УДАЛЕНИЯ СТРОК")
    report_lines.append("=" * 70)

    if 'removal_reasons' in globals() and removal_reasons:
        report_lines.append(f"Исходное количество: {rows_original}")
        report_lines.append(f"Конечное количество: {rows_final}")
        report_lines.append(f"Всего удалено: {rows_removed} ({rows_removed/rows_original*100:.2f}%)")
        report_lines.append("")
        report_lines.append("Примечание: причины удаления могут пересекаться")
        report_lines.append("(одна строка может попасть под несколько критериев)")
        report_lines.append("")
        report_lines.append("Причины удаления:")
        for reason, count in removal_reasons.items():
            pct = count / rows_original * 100
            report_lines.append(f"   • {reason}: {count} ({pct:.2f}%)")
    else:
        report_lines.append("Данные об удалении отсутствуют")
    report_lines.append("")

    # ========== РАЗДЕЛ 4: РАЗБИЕНИЕ ВЫБОРОК ==========
    report_lines.append("=" * 70)
    report_lines.append("4. РАЗБИЕНИЕ ВЫБОРОК")
    report_lines.append("=" * 70)
    report_lines.append(f"Train: {len(X_train)} ({SPLIT_TRAIN_SIZE:.0%})")
    report_lines.append(f"Val:   {len(X_val)} ({SPLIT_VAL_SIZE:.0%})")
    report_lines.append(f"Test:  {len(X_test)} ({SPLIT_TEST_SIZE:.0%})")
    report_lines.append(f"random_state: {RANDOM_STATE}")
    report_lines.append(f"Стратификация: {task_type == 'classification'}")

    if task_type == "classification":
        report_lines.append("")
        report_lines.append("Распределение классов в train:")
        for cls in sorted(y_train.unique()):
            count = (y_train == cls).sum()
            pct = count / len(y_train) * 100
            report_lines.append(f"   класс {cls}: {count} ({pct:.1f}%)")
    report_lines.append("")

    # ========== РАЗДЕЛ 5: ИТОГОВЫЕ ХАРАКТЕРИСТИКИ ==========
    report_lines.append("=" * 70)
    report_lines.append("5. ИТОГОВЫЕ ХАРАКТЕРИСТИКИ")
    report_lines.append("=" * 70)

    # Количество признаков
    numeric_cols_final = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()
    categorical_cols_final = X_train.select_dtypes(include=['category', 'object']).columns.tolist()

    report_lines.append(f"Признаков: {len(X_train.columns)}")
    report_lines.append(f"   Числовые: {len(numeric_cols_final)}")
    report_lines.append(f"   Категориальные: {len(categorical_cols_final)}")

    if columns_to_drop:
        actually_dropped = [col for col in columns_to_drop if col in df.columns]
        if actually_dropped:
            report_lines.append(f"Удалённые колонки: {actually_dropped}")

    # Границы обрезки (clipping_boundaries)
    if 'clipping_boundaries' in globals() and clipping_boundaries:
        report_lines.append("")
        report_lines.append("Границы обрезки (clipping_boundaries):")
        for col, bounds in clipping_boundaries.items():
            report_lines.append(f"   {col}: min={bounds['min']}, max={bounds['max']}, action={bounds['action']}")

    # Удалённые редкие категории
    if 'removed_categories' in globals() and removed_categories:
        report_lines.append("")
        report_lines.append("Удалённые редкие категории:")
        for col, categories in removed_categories.items():
            if categories:
                report_lines.append(f"   {col}: {categories}")
            else:
                report_lines.append(f"   {col}: нет удалённых категорий")

    # Пропуски после очистки
    total_nulls = df.isnull().sum().sum()
    if total_nulls == 0:
        report_lines.append("")
        report_lines.append("Пропуски после очистки: нет")
    else:
        report_lines.append("")
        report_lines.append(f"Пропуски после очистки: {total_nulls}")

    # Версии пакетов
    report_lines.append("")
    report_lines.append("Версии пакетов:")
    for pkg, ver in package_versions.items():
        report_lines.append(f"   {pkg}: {ver}")

    report_lines.append("")

    # ========== РАЗДЕЛ 6: РЕКОМЕНДАЦИИ ДЛЯ EDA ==========
    report_lines.append("=" * 70)
    report_lines.append("6. РЕКОМЕНДАЦИИ ДЛЯ EDA")
    report_lines.append("=" * 70)

    recommendations = []

    if categorical_cols_final:
        recommendations.append("• Закодировать категориальные признаки (OneHotEncoder / TargetEncoder)")

    if numeric_cols_final:
        recommendations.append("• Масштабировать числовые признаки (StandardScaler / RobustScaler)")

    if total_nulls > 0:
        recommendations.append("• Обработать оставшиеся пропуски")

    if task_type == "classification":
        class_counts = y_train.value_counts()
        if len(class_counts) >= 2:
            ratio = class_counts.max() / class_counts.min()
            if ratio > 3:
                recommendations.append(f"• Использовать class_weight='balanced' (дисбаланс {ratio:.1f}:1)")

    if not recommendations:
        recommendations.append("• Данные готовы к обучению модели")

    for rec in recommendations:
        report_lines.append(rec)

    report_lines.append("")
    report_lines.append("=" * 70)
    report_lines.append("КОНЕЦ ОТЧЁТА")
    report_lines.append("=" * 70)

    # Сохраняем отчёт
    report_path = os.path.join(REPORTS_PATH, 'preprocessing_report.txt')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report_lines))

    print(f"   ✓ preprocessing_report.txt сохранён в: {REPORTS_PATH}")

    # --------------------------------------------
    # Краткая информация в консоль
    # --------------------------------------------
    print("\n" + "="*50)
    print("📊 ИТОГОВАЯ ИНФОРМАЦИЯ")
    print("="*50)
    print(f"\n   Проект: {PROJECT_NAME}")
    print(f"   Целевая переменная: {TARGET_COLUMN}")
    print(f"   Тип задачи: {task_type}")
    print(f"   Признаков: {len(X_train.columns)}")
    print(f"   Всего данных: {len(X)} строк")
    print(f"   Train: {len(X_train)} ({len(X_train)/len(X)*100:.1f}%)")
    print(f"   Val:   {len(X_val)} ({len(X_val)/len(X)*100:.1f}%)")
    print(f"   Test:  {len(X_test)} ({len(X_test)/len(X)*100:.1f}%)")

    if task_type == "classification":
        print(f"\n   🎯 Классы целевой переменной '{TARGET_COLUMN}':")
        for cls in sorted(y.unique()):
            cls_name = str(cls)
            train_count = (y_train == cls).sum()
            train_pct = train_count / len(y_train) * 100
            print(f"      • {cls_name}: {train_count} в train ({train_pct:.1f}%)")

    print(f"\n   📦 Версии пакетов:")
    for pkg, ver in package_versions.items():
        print(f"      • {pkg}: {ver}")

    print(f"\n   📄 Полный отчёт: {report_path}")
    print(f"\n   📋 Data Contract версия {data_contract['version']} сохранён в metadata.json")

print("\n" + "="*50)
print("✓ Сохранение завершено")
print("="*50 + "\n")

==================================================
💾 СОХРАНЕНИЕ ВЫБОРОК И МЕТАДАННЫХ
==================================================

--- Сохранение признаков (X) ---
   ✓ X_train.csv (3031 строк, 10 признаков)
   ✓ X_val.csv (1011 строк)
   ✓ X_test.csv (1011 строк)

--- Сохранение целевой переменной (y) ---
   ✓ y_train.csv (3031 значений)
   ✓ y_val.csv (1011 значений)
   ✓ y_test.csv (1011 значений)

--- Проверка сохранённых файлов ---
   ✓ Все 6 файлов сохранены в: /content/drive/MyDrive/ml_learning/datasets/stroke/cycle_5/preprocessing/splits

--- Сохранение метаданных ---
   ✓ metadata.json сохранён

--- Создание единого отчёта ---
   ✓ preprocessing_report.txt сохранён в: /content/drive/MyDrive/ml_learning/datasets/stroke/cycle_5/preprocessing/reports

==================================================
📊 ИТОГОВАЯ ИНФОРМАЦИЯ
==================================================

   Проект: stroke
   Целевая переменная: stroke
   Тип задачи: classification
   Признаков: 10
   Всего данных: 5053 строк
   Train: 3031 (60.0%)
   Val:   1011 (20.0%)
   Test:  1011 (20.0%)

   🎯 Классы целевой переменной 'stroke':
      • 0: 2882 в train (95.1%)
      • 1: 149 в train (4.9%)

   📦 Версии пакетов:
      • python: 3.12.13
      • pandas: 2.2.2
      • numpy: 2.0.2
      • scikit-learn: 1.6.1
      • statsmodels: 0.14.6

   📄 Полный отчёт: /content/drive/MyDrive/ml_learning/datasets/stroke/cycle_5/preprocessing/reports/preprocessing_report.txt

   📋 Data Contract версия 1.0 сохранён в metadata.json

==================================================
✓ Сохранение завершено
==================================================

In [ ]:
# 7.2 ФИНАЛЬНАЯ ВАЛИДАЦИЯ СПЛИТОВ (ЗАЩИТА ОТ БАГОВ)

print("\n" + "="*50)
print("🛡️ ФИНАЛЬНАЯ ВАЛИДАЦИЯ СПЛИТОВ")
print("="*50)

validation_passed = True
warnings_list = []

if not is_train_ready(X_train):
    print("\n❌ ВАЛИДАЦИЯ НЕ ПРОЙДЕНА: выборки не созданы")
    validation_passed = False
else:
    print("\n🔍 Проверка целостности данных...\n")

    # --------------------------------------------
    # 1. Проверка колонок (имена и порядок)
    # --------------------------------------------
    print("   1. Колонки:")
    train_cols = X_train.columns.tolist()
    val_cols = X_val.columns.tolist()
    test_cols = X_test.columns.tolist()

    if train_cols == val_cols == test_cols:
        print(f"      ✓ Одинаковый набор колонок ({len(train_cols)} шт.)")
    else:
        print(f"      ❌ Колонки различаются!")
        if train_cols != val_cols:
            diff = set(train_cols) ^ set(val_cols)
            print(f"         Train vs Val: различие {diff}")
        if train_cols != test_cols:
            diff = set(train_cols) ^ set(test_cols)
            print(f"         Train vs Test: различие {diff}")
        validation_passed = False

    # --------------------------------------------
    # 2. Проверка типов данных
    # --------------------------------------------
    print("\n   2. Типы данных:")
    type_mismatch = False
    for col in train_cols:
        train_dtype = X_train[col].dtype
        val_dtype = X_val[col].dtype
        test_dtype = X_test[col].dtype

        if train_dtype != val_dtype or train_dtype != test_dtype:
            print(f"      ⚠️ {col}: train={train_dtype}, val={val_dtype}, test={test_dtype}")
            type_mismatch = True
            warnings_list.append(f"Типы данных различаются в колонке '{col}'")

    if not type_mismatch:
        print(f"      ✓ Типы данных совпадают во всех выборках")

    # --------------------------------------------
    # 3. Проверка на NaN
    # --------------------------------------------
    print("\n   3. Пропуски (NaN):")

    train_nulls = X_train.isnull().sum().sum()
    val_nulls = X_val.isnull().sum().sum()
    test_nulls = X_test.isnull().sum().sum()
    y_nulls = y_train.isnull().sum() + y_val.isnull().sum() + y_test.isnull().sum()

    if train_nulls == 0 and val_nulls == 0 and test_nulls == 0:
        print(f"      ✓ NaN в признаках отсутствуют")
    else:
        print(f"      ❌ Обнаружены NaN:")
        print(f"         Train: {train_nulls}, Val: {val_nulls}, Test: {test_nulls}")
        validation_passed = False

    if y_nulls == 0:
        print(f"      ✓ NaN в целевой переменной отсутствуют")
    else:
        print(f"      ❌ NaN в целевой переменной: {y_nulls}")
        validation_passed = False

    # --------------------------------------------
    # 4. ПРОВЕРКА НА КОНСТАНТНЫЕ ПРИЗНАКИ В VAL/TEST
    #    (защита от вчерашнего бага с FE)
    # --------------------------------------------
    print("\n   4. Константные признаки в val/test:")

    constant_in_val = []
    constant_in_test = []

    for col in train_cols:
        # Проверяем val
        if X_val[col].nunique() == 1:
            val_value = X_val[col].iloc[0]
            train_unique = X_train[col].nunique()
            constant_in_val.append((col, val_value, train_unique))

        # Проверяем test
        if X_test[col].nunique() == 1:
            test_value = X_test[col].iloc[0]
            train_unique = X_train[col].nunique()
            constant_in_test.append((col, test_value, train_unique))

    if constant_in_val:
        print(f"      ⚠️ В val обнаружены константные признаки:")
        for col, val, train_uniq in constant_in_val:
            if train_uniq > 1:
                print(f"         ❌ {col}: только значение '{val}' (в train {train_uniq} значений)")
                warnings_list.append(f"КРИТИЧНО: '{col}' в val константный, а в train имеет {train_uniq} значений")
                validation_passed = False
            else:
                print(f"         ℹ️ {col}: только '{val}' (как и в train)")

    if constant_in_test:
        print(f"      ⚠️ В test обнаружены константные признаки:")
        for col, val, train_uniq in constant_in_test:
            if train_uniq > 1:
                print(f"         ❌ {col}: только значение '{val}' (в train {train_uniq} значений)")
                warnings_list.append(f"КРИТИЧНО: '{col}' в test константный, а в train имеет {train_uniq} значений")
                validation_passed = False
            else:
                print(f"         ℹ️ {col}: только '{val}' (как и в train)")

    if not constant_in_val and not constant_in_test:
        print(f"      ✓ Константных признаков в val/test нет")

    # --------------------------------------------
    # 5. Проверка диапазонов числовых признаков
    # --------------------------------------------
    print("\n   5. Диапазоны числовых признаков:")

    numeric_cols = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()
    range_issues = []

    for col in numeric_cols:
        train_min, train_max = X_train[col].min(), X_train[col].max()
        val_min, val_max = X_val[col].min(), X_val[col].max()
        test_min, test_max = X_test[col].min(), X_test[col].max()

        # Проверяем, что val/test не выходят за пределы train
        tolerance = 0.01 * (train_max - train_min) if train_max != train_min else 0

        if val_min < train_min - tolerance or val_max > train_max + tolerance:
            range_issues.append(f"Val: {col} [{val_min:.2f}, {val_max:.2f}] vs train [{train_min:.2f}, {train_max:.2f}]")
        if test_min < train_min - tolerance or test_max > train_max + tolerance:
            range_issues.append(f"Test: {col} [{test_min:.2f}, {test_max:.2f}] vs train [{train_min:.2f}, {train_max:.2f}]")

    if range_issues:
        print(f"      ⚠️ Значения выходят за пределы train:")
        for issue in range_issues[:3]:
            print(f"         {issue}")
        warnings_list.extend(range_issues)
    else:
        print(f"      ✓ Диапазоны значений в норме")

    # --------------------------------------------
    # 6. Проверка категорий в категориальных признаках
    # --------------------------------------------
    print("\n   6. Категории в категориальных признаках:")

    categorical_cols = X_train.select_dtypes(include=['category', 'object']).columns.tolist()
    category_issues = []

    for col in categorical_cols:
        train_cats = set(X_train[col].dropna().unique())
        val_cats = set(X_val[col].dropna().unique())
        test_cats = set(X_test[col].dropna().unique())

        val_new = val_cats - train_cats
        test_new = test_cats - train_cats

        if val_new:
            category_issues.append(f"Val: '{col}' содержит новые категории: {val_new}")
        if test_new:
            category_issues.append(f"Test: '{col}' содержит новые категории: {test_new}")

    if category_issues:
        print(f"      ⚠️ Обнаружены новые категории:")
        for issue in category_issues:
            print(f"         {issue}")
        warnings_list.extend(category_issues)
    else:
        print(f"      ✓ Все категории из val/test присутствуют в train")

    # --------------------------------------------
    # 7. Проверка классов в целевой переменной
    # --------------------------------------------
    print("\n   7. Классы в целевой переменной:")

    if task_type == "classification":
        train_classes = set(y_train.unique())
        val_classes = set(y_val.unique())
        test_classes = set(y_test.unique())
        all_classes = set(y.unique())

        if train_classes == all_classes:
            print(f"      ✓ Train содержит все классы: {sorted(all_classes)}")
        else:
            missing = all_classes - train_classes
            print(f"      ❌ В train отсутствуют классы: {missing}")
            validation_passed = False

        # Проверка минимального количества примеров
        for cls in all_classes:
            val_count = (y_val == cls).sum()
            test_count = (y_test == cls).sum()

            if val_count == 0:
                print(f"      ❌ Класс '{cls}' отсутствует в val")
                validation_passed = False
            elif val_count < 3:
                warnings_list.append(f"Класс '{cls}' в val имеет только {val_count} примеров")

            if test_count == 0:
                print(f"      ❌ Класс '{cls}' отсутствует в test")
                validation_passed = False
            elif test_count < 3:
                warnings_list.append(f"Класс '{cls}' в test имеет только {test_count} примеров")

        if validation_passed:
            print(f"      ✓ Классы распределены корректно")

    # --------------------------------------------
    # 8. Проверка размеров выборок
    # --------------------------------------------
    print("\n   8. Размеры выборок:")

    if len(X_train) > 0 and len(X_val) > 0 and len(X_test) > 0:
        print(f"      ✓ Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")
    else:
        print(f"      ❌ Одна из выборок пуста!")
        validation_passed = False

    # --------------------------------------------
    # 9. Проверка на дубликаты строк
    # --------------------------------------------
    print("\n   9. Дубликаты строк:")

    train_dups = X_train.duplicated().sum()
    val_dups = X_val.duplicated().sum()
    test_dups = X_test.duplicated().sum()

    if train_dups == 0 and val_dups == 0 and test_dups == 0:
        print(f"      ✓ Дубликатов нет")
    else:
        print(f"      ℹ️ Дубликаты: train={train_dups}, val={val_dups}, test={test_dups}")
        if train_dups > len(X_train) * 0.1:
            warnings_list.append(f"Много дубликатов в train: {train_dups} ({train_dups/len(X_train)*100:.1f}%)")

    # --------------------------------------------
    # ИТОГИ ВАЛИДАЦИИ
    # --------------------------------------------
    print("\n" + "="*50)

    if validation_passed:
        print("✅ ВАЛИДАЦИЯ ПРОЙДЕНА УСПЕШНО")
        print("   Данные готовы к Feature Engineering и Modeling")
    else:
        print("❌ ВАЛИДАЦИЯ НЕ ПРОЙДЕНА")
        print("   Обнаружены критические проблемы. Исправьте перед продолжением.")

    if warnings_list:
        print("\n⚠️ ПРЕДУПРЕЖДЕНИЯ:")
        for i, warning in enumerate(warnings_list[:5], 1):
            print(f"   {i}. {warning}")
        if len(warnings_list) > 5:
            print(f"   ... и ещё {len(warnings_list) - 5}")

print("\n" + "="*50)
print("✓ Финальная валидация завершена")
print("="*50 + "\n")

==================================================
🛡️ ФИНАЛЬНАЯ ВАЛИДАЦИЯ СПЛИТОВ
==================================================

🔍 Проверка целостности данных...

   1. Колонки:
      ✓ Одинаковый набор колонок (10 шт.)

   2. Типы данных:
      ✓ Типы данных совпадают во всех выборках

   3. Пропуски (NaN):
      ❌ Обнаружены NaN:
         Train: 114, Val: 43, Test: 43
      ✓ NaN в целевой переменной отсутствуют

   4. Константные признаки в val/test:
      ✓ Константных признаков в val/test нет

   5. Диапазоны числовых признаков:
      ✓ Диапазоны значений в норме

   6. Категории в категориальных признаках:
      ✓ Все категории из val/test присутствуют в train

   7. Классы в целевой переменной:
      ✓ Train содержит все классы: [np.int64(0), np.int64(1)]

   8. Размеры выборок:
      ✓ Train: 3031, Val: 1011, Test: 1011

   9. Дубликаты строк:
      ✓ Дубликатов нет

==================================================
❌ ВАЛИДАЦИЯ НЕ ПРОЙДЕНА
   Обнаружены критические проблемы. Исправьте перед продолжением.

==================================================
✓ Финальная валидация завершена
==================================================