# 📋 РУКОВОДСТВО ПО ИСПОЛЬЗОВАНИЮ ШАБЛОНА

## Просмотр результатов

**Ноутбук уже выполнен.** Все графики и выводы видны сразу при открытии на GitHub.

### Источник данных:

**Датасет:** Stroke Prediction Dataset  
**Источник:** [Kaggle - Stroke Prediction Dataset](https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset)

Итоги анализа датасета: [analysis_report.md](analysis_report.md)

> **Примечание:** Датасет не включён в репозиторий. Для самостоятельного запуска ноутбука необходимо скачать датасет и настроить пути в блоке 1.3.


---

## 🚀 БЫСТРЫЙ СТАРТ

1. Открой блок [**1.3 НАСТРОЙКИ ПРОЕКТА**](#scrollTo=gsHs-qXFxVsG)
2. Укажи `TARGET_COLUMN` и пути к данным
3. При необходимости настрой `int_columns`, `categorical_columns`, `columns_to_drop`
4. Запусти `Runtime → Run all`

---

## ⚙️ ОСНОВНЫЕ НАСТРОЙКИ [(блок 1.3)](#scrollTo=gsHs-qXFxVsG)

| Переменная | Описание | Пример |
|------------|----------|--------|
| `LOAD_MODE` | `'drive'` или `'local'` | `'drive'` |
| `FILE_ID` | ID файла на Google Drive | `'1Jsq2V...'` |
| `PROJECT_NAME` | Имя папки проекта | `'stroke'` |
| `TARGET_COLUMN` | Целевая переменная | `'stroke'` |
| `FORCE_TASK_TYPE` | Тип задачи | `''`, `'classification'`, `'regression'` |
| `int_columns` | Целочисленные колонки | `['age', 'hypertension']` |
| `float_columns` | Вещественные колонки | `['bmi', 'glucose']` |
| `categorical_columns` | Категориальные колонки | `['gender', 'work_type']` |
| `columns_to_drop` | Колонки для удаления | `['id']` |

> 💡 Запусти блок 2.2 - он покажет подсказки для `categorical_columns` и `int_columns`

---

## 📁 РЕЗУЛЬТАТЫ

После выполнения создаётся структура:
<pre>
📁 {PROJECT_NAME}/
├── 📄 00_raw.csv # исходные данные
├── 📄 metadata.json # метаданные проекта
├── 📁 checkpoints/
│ ├── 01_structure.csv # после типов и удаления колонок
│ └── 02_cleaned.csv # после очистки
├── 📁 splits/
│ ├── X_train.csv, X_val.csv, X_test.csv
│ └── y_train.csv, y_val.csv, y_test.csv
└── 📁 reports/
├── data_report.txt
├── analysis_report.txt
└── final_report.txt
</pre>

---

## ⚠️ ВАЖНО

- Все анализы (выбросы, корреляции, VIF) выполняются **только на train**
- Для VIF требуется `statsmodels` (устанавливается автоматически)
- Решения об очистке принимай на основе train

---

## 📚 СЛЕДУЮЩИЙ ЭТАП

После предобработки переходи к ноутбуку **EDA** для визуального анализа данных.

# СТРУКТУРА ШАБЛОНА ПРЕДОБРАБОТКИ ДАННЫХ

**Версия 8.0**

---

## ЧАСТЬ 1: НАСТРОЙКА И ЗАГРУЗКА
| Блок | Название |
|------|----------|
| 1.1 | Загрузка библиотек |
| 1.2 | Служебные функции проверки |
| 1.3 | Настройки проекта (менять под задачу) |
| 1.4 | Монтирование Google Drive |
| 1.5 | Загрузка данных |
| 1.6 | Настройка путей проекта |
| 1.7 | Сохранение исходных данных (`00_raw.csv`) |

---

## ЧАСТЬ 2: ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ
| Блок | Название |
|------|----------|
| 2.1 | Базовый осмотр данных |
| 2.2 | Дополнительные проверки и поиск аномалий |

---

## ЧАСТЬ 3: ПРЕДОБРАБОТКА ДАННЫХ
| Блок | Название |
|------|----------|
| 3.1 | Переименование колонок |
| 3.2 | Приведение типов данных |
| 3.3 | Удаление ненужных колонок |
| 3.4 | Обработка аномалий (пропуски, диапазоны, редкие категории) |
| 3.5 | Сохранение контрольной точки (`01_structure.csv`) |

---

## ЧАСТЬ 4: ОЧИСТКА И ФИНАЛИЗАЦИЯ
| Блок | Название |
|------|----------|
| 4.1 | Механическая очистка текста и категорий |
| 4.2 | Сохранение контрольной точки (`02_cleaned.csv`) |

---

## ЧАСТЬ 5: РАЗБИЕНИЕ ДАННЫХ
| Блок | Название |
|------|----------|
| 5.1 | Подготовка к разделению (создание X и y) |
| 5.2 | Разделение на train/val/test |

---

## ЧАСТЬ 6: АНАЛИЗ TRAIN ВЫБОРКИ
| Блок | Название |
|------|----------|
| 6.1 | Проверка на выбросы (IQR) |
| 6.2 | Корреляция числовых признаков |
| 6.3 | Проверка на мультиколлинеарность (VIF) |
| 6.4 | Рекомендации по кодированию категориальных признаков |
| 6.5 | Проверка на константные и низковариативные признаки |

---

## ЧАСТЬ 7: СОХРАНЕНИЕ И ФИНАЛИЗАЦИЯ
| Блок | Название |
|------|----------|
| 7.1 | Сохранение выборок и метаданных |
| 7.2 | Итоги выполнения и рекомендации |

---

## КОНТРОЛЬНЫЕ ТОЧКИ
| Файл | Описание |
|------|----------|
| `00_raw.csv` | Исходные данные |
| `01_structure.csv` | После типов и удаления колонок |
| `02_cleaned.csv` | После механической очистки |

---

## РЕЗУЛЬТАТЫ

**Папка `splits/`:**
- `X_train.csv`, `X_val.csv`, `X_test.csv`
- `y_train.csv`, `y_val.csv`, `y_test.csv`

**Папка `reports/`:**
- `data_report.txt`
- `analysis_report.txt`
- `final_report.txt`

**Корень проекта:**
- `metadata.json`

---

# БЛОК 1. import библиотек

In [ ]:
# 1.1 ЗАГРУЗКА БИБЛИОТЕК

import pandas as pd
import numpy as np
import os
import sys
import json
import warnings
import sklearn
from datetime import datetime
from sklearn.model_selection import train_test_split
from IPython.display import display
import shutil

# Настройка отображения
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
warnings.filterwarnings('ignore')

# Определение окружения (Colab или локально)
try:
    from google.colab import drive
    IN_COLAB = True
    print("✓ Среда выполнения: Google Colab")
except ImportError:
    IN_COLAB = False
    print("✓ Среда выполнения: локальная / Kaggle")

# Установка недостающих пакетов
def install_if_missing(package_name, import_name=None):
    if import_name is None:
        import_name = package_name

    try:
        __import__(import_name)
    except ImportError:
        print(f"📦 Установка {package_name}...")
        os.system(f'{sys.executable} -m pip install {package_name} --quiet')
        print(f"   ✓ {package_name} установлен")

install_if_missing('statsmodels')

# Автоопределение версий для воспроизводимости
def print_versions():
    print("\n📦 Версии пакетов:")
    print(f"   Python: {sys.version.split()[0]}")
    print(f"   pandas: {pd.__version__}")
    print(f"   numpy: {np.__version__}")
    print(f"   scikit-learn: {sklearn.__version__}")

    try:
        import statsmodels
        print(f"   statsmodels: {statsmodels.__version__}")
    except ImportError:
        pass

print_versions()

✓ Среда выполнения: Google Colab

📦 Версии пакетов:
   Python: 3.12.13
   pandas: 2.2.2
   numpy: 2.0.2
   scikit-learn: 1.6.1
   statsmodels: 0.14.6

In [ ]:
# 1.2 СЛУЖЕБНЫЕ ФУНКЦИИ ПРОВЕРКИ ДАННЫХ

def is_split_ready(df, X, TARGET_COLUMN):

    # Проверяет готовность данных перед разделением на X и y

    if df is None:
        print("   ⚠️ Пропускаем: данные не загружены")
        return False

    if not TARGET_COLUMN:
        print("   ⚠️ Пропускаем: TARGET_COLUMN не указан (задайте в блоке 3)")
        return False

    if TARGET_COLUMN not in df.columns:
        print(f"   ⚠️ Пропускаем: колонка '{TARGET_COLUMN}' не найдена в данных")
        return False

    # 🔧 Проверка существования переменной X
    if 'X' not in globals():
        print("   ⚠️ Пропускаем: X не создан (выполните блок 9)")
        return False

    if X is None or len(X) == 0:
        print("   ⚠️ Пропускаем: X пуст (нет признаков для анализа)")
        return False

    return True


def is_train_ready(X_train, y_train=None):

    # Проверка готовность train-данных

    # 🔧 Проверка существования переменной
    if 'X_train' not in globals() or X_train is None or len(X_train) == 0:
        print("   ⚠️ Пропускаем: X_train не определён (выполните блок 10)")
        return False

    # 🔧 Опциональная проверка y_train
    if y_train is not None:
        if 'y_train' not in globals() or y_train is None or len(y_train) == 0:
            print("   ⚠️ Пропускаем: y_train не определён (выполните блок 10)")
            return False

        if len(X_train) != len(y_train):
            print(f"   ⚠️ Пропускаем: размеры не совпадают X_train={len(X_train)}, y_train={len(y_train)}")
            return False

    return True

# Ввод переменных

In [ ]:
# 1.3 НАСТРОЙКИ ПРОЕКТА (менять под каждую задачу)

# --------------------------------------------
# 1. ЗАГРУЗКА ДАННЫХ
# --------------------------------------------
LOAD_MODE = 'drive'     # 'drive' или 'local'
FILE_ID = '1Jsq2V0lFfBurcSZm-fQUJXRB9nUWsG_I'  # для drive
LOCAL_DATA_PATH = '/content/data.csv'           # для local

# --------------------------------------------
# 2. ПРОЕКТ
# --------------------------------------------
PROJECT_NAME = 'stroke_test'

# --------------------------------------------
# 3. ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ (для поиска аномалий)
# --------------------------------------------
SUSPICIOUS_VALUES = [
    # Маркеры пропусков
    -1, -999, -9999, -99999,
    999, 9999, 99999, 999999, 9999999,
    # Специальные коды
    99, 999,
    # Экстремальные
    999999999,
    # Технические (границы uint8)
    0, 127, 255,
]

# --------------------------------------------
# 4. ПРИВЕДЕНИЕ ТИПОВ (блок 5.1)
# --------------------------------------------
date_columns = []              # пример: ['date', 'birth_date']
int_columns = ['hypertension', 'heart_disease']
float_columns = ['age', 'avg_glucose_level', 'bmi']
categorical_columns = [
    'gender',
    'ever_married',
    'work_type',
    'Residence_type',
    'smoking_status'
]
text_columns = []              # текстовые колонки для strip() + lower()

# --------------------------------------------
# 5. УДАЛЕНИЕ КОЛОНОК (блок 5.2)
# --------------------------------------------
columns_to_drop = ['id']       # пример: ['id', 'user_id', 'timestamp']

# --------------------------------------------
# 6. ЦЕЛЕВАЯ ПЕРЕМЕННАЯ (блок 9)
# --------------------------------------------
TARGET_COLUMN = 'stroke'
FORCE_TASK_TYPE = 'classification'  # '', 'classification', 'regression'

# --------------------------------------------
# 7. РАЗБИЕНИЕ ВЫБОРОК (блок 7)
# --------------------------------------------
SPLIT_TRAIN_SIZE = 0.6
SPLIT_VAL_SIZE = 0.2
SPLIT_TEST_SIZE = 0.2
RANDOM_STATE = 42

assert abs(SPLIT_TRAIN_SIZE + SPLIT_VAL_SIZE + SPLIT_TEST_SIZE - 1.0) < 0.001, \
    "❌ Сумма долей разбиения должна быть равна 1.0"

# --------------------------------------------
# 8. БАЗОВЫЙ ПУТЬ (автоопределение)
# --------------------------------------------
if 'IN_COLAB' not in globals():
    try:
        from google.colab import drive
        IN_COLAB = True
    except ImportError:
        IN_COLAB = False

if IN_COLAB:
    BASE_PATH = '/content/drive/MyDrive/ml_learning'  # ← важно: /content/drive/
else:
    BASE_PATH = os.path.join(os.getcwd(), 'ml_learning')

# --------------------------------------------
# 9. ОБРАБОТКА АНОМАЛИЙ
# --------------------------------------------
# Пропуски
DROP_ROWS_WITH_NULLS = True
COLUMNS_TO_CHECK_NULLS = ['bmi']

# Диапазоны
DROP_OUT_OF_RANGE = True
NUMERIC_RANGES = {
    'age': (1, 82),
    'bmi': (10, 60),
    'avg_glucose_level': (50, 300),
}

# Выбросы
OUTLIER_IQR_COEFF = 1.5
DROP_PERCENTILE_OUTLIERS = False
PERCENTILE_RANGE = (0.01, 0.99)

# Редкие категории
DROP_RARE_CATEGORIES = True
RARE_CATEGORY_THRESHOLD = 0.01
COLUMNS_TO_CHECK_RARE = ['gender']
RARE_CATEGORIES_TO_KEEP = []


# --------------------------------------------
# ВЫВОД НАСТРОЕК
# --------------------------------------------
print(f"\n📁 ПРОЕКТ: {PROJECT_NAME}")
print(f"🎯 ЦЕЛЬ: {TARGET_COLUMN}")
print(f"📊 ТИП ЗАДАЧИ: {FORCE_TASK_TYPE if FORCE_TASK_TYPE else 'автоопределение'}")
print(f"📂 BASE_PATH: {BASE_PATH}")

print(f"\n📥 ЗАГРУЗКА: {LOAD_MODE}")
if LOAD_MODE == 'drive':
    print(f"   FILE_ID: {FILE_ID}")

print(f"\n🔧 РАЗБИЕНИЕ: train={SPLIT_TRAIN_SIZE:.0%}, val={SPLIT_VAL_SIZE:.0%}, test={SPLIT_TEST_SIZE:.0%}, seed={RANDOM_STATE}")

print(f"\n🧹 ОЧИСТКА:")
print(f"   Пропуски: {DROP_ROWS_WITH_NULLS} ({COLUMNS_TO_CHECK_NULLS if COLUMNS_TO_CHECK_NULLS else 'все колонки'})")
print(f"   Диапазоны: {DROP_OUT_OF_RANGE}")
if DROP_OUT_OF_RANGE:
    for col, (min_v, max_v) in NUMERIC_RANGES.items():
        print(f"      {col}: [{min_v}, {max_v}]")
print(f"   Выбросы IQR: {OUTLIER_IQR_COEFF}")
print(f"   Редкие категории: {DROP_RARE_CATEGORIES} (порог {RARE_CATEGORY_THRESHOLD:.1%}, колонки: {COLUMNS_TO_CHECK_RARE})")

print(f"\n⚠️ ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ: {SUSPICIOUS_VALUES[:5]}...")  # первые 5 для краткости

print("\n✓ Настройки загружены\n")

📁 ПРОЕКТ: stroke_test
🎯 ЦЕЛЬ: stroke
📊 ТИП ЗАДАЧИ: classification
📂 BASE_PATH: /content/drive/MyDrive/ml_learning

📥 ЗАГРУЗКА: drive
   FILE_ID: 1Jsq2V0lFfBurcSZm-fQUJXRB9nUWsG_I

🔧 РАЗБИЕНИЕ: train=60%, val=20%, test=20%, seed=42

🧹 ОЧИСТКА:
   Пропуски: True (['bmi'])
   Диапазоны: True
      age: [1, 82]
      bmi: [10, 60]
      avg_glucose_level: [50, 300]
   Выбросы IQR: 1.5
   Редкие категории: True (порог 1.0%, колонки: ['gender'])

⚠️ ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ: [-1, -999, -9999, -99999, 999]...

✓ Настройки загружены

In [ ]:
# 1.4 МОНТИРОВАНИЕ GOOGLE DRIVE

print("\n" + "="*50)
print("📂 МОНТИРОВАНИЕ GOOGLE DRIVE")
print("="*50)

if IN_COLAB:
    if BASE_PATH.startswith('/content/drive'):
        if os.path.ismount('/content/drive'):
            print("✓ Google Drive уже смонтирован")
        else:
            print("📂 Монтирование Google Drive...")

            if os.path.exists('/content/drive') and not os.path.ismount('/content/drive'):
                shutil.rmtree('/content/drive')

            drive.mount('/content/drive')
            print("✓ Google Drive смонтирован")
    else:
        print("✓ BASE_PATH не на Google Drive, монтирование не требуется")
else:
    print("✓ Локальная среда, монтирование не требуется")

print("="*50 + "\n")

==================================================
📂 МОНТИРОВАНИЕ GOOGLE DRIVE
==================================================
✓ Google Drive уже смонтирован
==================================================

In [ ]:
# 1.5 ЗАГРУЗКА ДАННЫХ

if LOAD_MODE == 'drive':
    if not FILE_ID:
        raise ValueError("❌ FILE_ID не указан в настройках (блок 1.3)")

    url = f'https://drive.google.com/uc?id={FILE_ID}'
    print(f"📥 Загрузка с Google Drive...")

    try:
        df = pd.read_csv(url)
        print(f"✓ Данные загружены: {df.shape[0]} строк, {df.shape[1]} колонок")
    except Exception as e:
        print(f"❌ Ошибка загрузки: {e}")
        print("   Проверьте, что файл доступен по ссылке (Anyone with link)")
        raise

elif LOAD_MODE == 'local':
    if not os.path.exists(LOCAL_DATA_PATH):
        raise FileNotFoundError(f"❌ Файл не найден: {LOCAL_DATA_PATH}")

    df = pd.read_csv(LOCAL_DATA_PATH)
    print(f"✓ Данные загружены локально: {df.shape[0]} строк, {df.shape[1]} колонок")

else:
    raise ValueError(f"❌ LOAD_MODE должен быть 'drive' или 'local', получено: '{LOAD_MODE}'")

📥 Загрузка с Google Drive...
✓ Данные загружены: 5110 строк, 12 колонок

In [ ]:
# 1.6 НАСТРОЙКА ПУТЕЙ ПРОЕКТА

# Проверка, что BASE_PATH определён
if 'BASE_PATH' not in globals():
    raise NameError("❌ BASE_PATH не определён. Выполните блок 1.3")

# Определение путей
PROJECT_PATH = os.path.join(BASE_PATH, 'datasets', PROJECT_NAME)
CHECKPOINT_PATH = os.path.join(PROJECT_PATH, 'checkpoints')
SPLITS_PATH = os.path.join(PROJECT_PATH, 'splits')
REPORTS_PATH = os.path.join(PROJECT_PATH, 'reports')

# Создание папок
for path in [PROJECT_PATH, CHECKPOINT_PATH, SPLITS_PATH, REPORTS_PATH]:
    os.makedirs(path, exist_ok=True)
    print(f"   Создана папка: {path}")

# Вывод структуры
print("\n📂 СТРУКТУРА ПРОЕКТА:")
print(f"   {PROJECT_PATH}/")
print(f"   ├── checkpoints/")
print(f"   ├── splits/")
print(f"   └── reports/")
print(f"\n✓ Папки созданы на Google Drive")

   Создана папка: /content/drive/MyDrive/ml_learning/datasets/stroke_test
   Создана папка: /content/drive/MyDrive/ml_learning/datasets/stroke_test/checkpoints
   Создана папка: /content/drive/MyDrive/ml_learning/datasets/stroke_test/splits
   Создана папка: /content/drive/MyDrive/ml_learning/datasets/stroke_test/reports

📂 СТРУКТУРА ПРОЕКТА:
   /content/drive/MyDrive/ml_learning/datasets/stroke_test/
   ├── checkpoints/
   ├── splits/
   └── reports/

✓ Папки созданы на Google Drive

In [ ]:
# Проверочная ячейка
print(f"BASE_PATH: {BASE_PATH}")
print(f"Существует: {os.path.exists(BASE_PATH)}")
print(f"PROJECT_PATH: {PROJECT_PATH}")
print(f"Существует: {os.path.exists(PROJECT_PATH)}")

# Посмотреть содержимое
if os.path.exists(PROJECT_PATH):
    print(f"\nСодержимое {PROJECT_PATH}:")
    for item in os.listdir(PROJECT_PATH):
        print(f"   {item}")

BASE_PATH: /content/drive/MyDrive/ml_learning
Существует: True
PROJECT_PATH: /content/drive/MyDrive/ml_learning/datasets/stroke_test
Существует: True

Содержимое /content/drive/MyDrive/ml_learning/datasets/stroke_test:
   checkpoints
   splits
   reports
   metadata.json

In [ ]:
# 1.7 СОХРАНЕНИЕ ИСХОДНЫХ ДАННЫХ

if 'df' not in globals() or df is None or df.empty:
    raise ValueError("❌ Данные не загружены. Выполните блок 1.5")

raw_backup_path = os.path.join(CHECKPOINT_PATH, '00_raw.csv')
df.to_csv(raw_backup_path, index=False)
print(f"✓ Контрольная точка сохранена: checkpoints/00_raw.csv")

✓ Контрольная точка сохранена: checkpoints/00_raw.csv

# БЛОК 2. Общая info

In [ ]:
# 2.1 ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ

if df is None or df.empty:
    print("❌ Данные не загружены. Выполните блок 1.5")
else:
    print("\n" + "="*50)
    print("🔍 ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ")
    print("="*50)

    # Размер таблицы
    print(f"\n📏 РАЗМЕР: {df.shape[0]} строк, {df.shape[1]} колонок")

    # Названия колонок
    print(f"\n📋 КОЛОНКИ ({len(df.columns)}):")
    print(f"   {df.columns.tolist()}")

    # Типы данных
    print(f"\n📊 ТИПЫ ДАННЫХ:")
    type_counts = df.dtypes.value_counts()
    for dtype, count in type_counts.items():
        print(f"   {dtype}: {count}")

    # Первые 5 строк
    print(f"\n👀 ПЕРВЫЕ 5 СТРОК:")
    display(df.head())

    # Пропуски
    print(f"\n🚫 ПРОПУСКИ:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) > 0:
        for col, count in missing.items():
            pct = count / len(df) * 100
            print(f"   {col}: {count} ({pct:.1f}%)")
    else:
        print("   ✓ Пропусков нет")

    # Дубликаты
    print(f"\n📑 ДУБЛИКАТЫ:")
    duplicates_count = df.duplicated().sum()
    if duplicates_count > 0:
        print(f"   Полных дубликатов строк: {duplicates_count} ({duplicates_count/len(df)*100:.2f}%)")
    else:
        print("   ✓ Дубликатов нет")

    # Числовые колонки
    print(f"\n🔢 ЧИСЛОВЫЕ КОЛОНКИ:")
    numeric_cols = df.select_dtypes(include=['int64', 'Int64', 'float64', 'int32', 'float32']).columns.tolist()
    if numeric_cols:
        print(f"   {numeric_cols}")
    else:
        print("   Числовых колонок нет")

    # Категориальные колонки
    print(f"\n🏷️ КАТЕГОРИАЛЬНЫЕ КОЛОНКИ:")
    categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
    if categorical_cols:
        print(f"   {categorical_cols}")
    else:
        print("   Категориальных колонок нет")

    # Базовая статистика по числовым
    if numeric_cols:
        print(f"\n📈 СТАТИСТИКА ПО ЧИСЛОВЫМ:")
        display(df[numeric_cols].describe())

    print("\n" + "="*50)
    print("✓ Первичный осмотр завершён")
    print("="*50 + "\n")

==================================================
🔍 ПЕРВИЧНЫЙ ОСМОТР ДАННЫХ
==================================================

📏 РАЗМЕР: 5110 строк, 12 колонок

📋 КОЛОНКИ (12):
   ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

📊 ТИПЫ ДАННЫХ:
   object: 5
   int64: 4
   float64: 3

👀 ПЕРВЫЕ 5 СТРОК:

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

🚫 ПРОПУСКИ:
   bmi: 201 (3.9%)

📑 ДУБЛИКАТЫ:
   ✓ Дубликатов нет

🔢 ЧИСЛОВЫЕ КОЛОНКИ:
   ['id', 'age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke']

🏷️ КАТЕГОРИАЛЬНЫЕ КОЛОНКИ:
   ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

📈 СТАТИСТИКА ПО ЧИСЛОВЫМ:

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

==================================================
✓ Первичный осмотр завершён
==================================================

In [ ]:
# 2.2 ДОПОЛНИТЕЛЬНЫЕ ПРОВЕРКИ

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем проверки.")
else:
    # --------------------------------------------
    # Диапазоны числовых колонок (min/max)
    # --------------------------------------------
    print("\n--- ДИАПАЗОНЫ ЧИСЛОВЫХ КОЛОНОК ---")
    numeric_cols = df.select_dtypes(include=['int64', 'Int64', 'float64']).columns
    if len(numeric_cols) > 0:
        for col in numeric_cols:
            print(f"{col}: min = {df[col].min()}, max = {df[col].max()}")
    else:
        print("Нет числовых колонок для анализа")

    # --------------------------------------------
    # Проверка пустых строк ("" вместо NaN) в текстовых колонках
    # --------------------------------------------
    print("\n--- ПУСТЫЕ СТРОКИ В ТЕКСТОВЫХ КОЛОНКАХ ---")
    text_cols = df.select_dtypes(include=['object']).columns
    empty_found = False
    for col in text_cols:
        empty_count = (df[col] == '').sum()
        if empty_count > 0:
            print(f"{col}: {empty_count} пустых строк")
            empty_found = True
    if not empty_found:
        print("Пустых строк ('' вместо NaN) не обнаружено")

    # --------------------------------------------
    # Проверка на подозрительные значения в числовых колонках
    # --------------------------------------------
    print("\n--- ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ ---")
    # Используем список из настроек
    suspicious = SUSPICIOUS_VALUES if 'SUSPICIOUS_VALUES' in globals() else [-1, -999, 999999, 999999999]
    suspicious_found = False
    for col in numeric_cols:
        for val in suspicious:
            count = (df[col] == val).sum()
            if count > 0:
                print(f"{col}: {count} раз встречается {val}")
                suspicious_found = True
    if not suspicious_found:
        print("Подозрительных значений не обнаружено")

    # --------------------------------------------
    # Уникальные значения в колонках с малым количеством вариантов
    # --------------------------------------------
    print("\n--- УНИКАЛЬНЫЕ ЗНАЧЕНИЯ (колонки с < 20 вариантов) ---")

    low_cardinality_cols = []  # для категориальных
    potential_int_cols = []    # для целочисленных

    for col in df.columns:
        unique_count = df[col].nunique()
        if unique_count < 20:
            low_cardinality_cols.append(col)
            print(f"\n{col} ({unique_count} уникальных значений):")
            print(df[col].unique())

        # Проверка на потенциально целочисленные колонки
        if df[col].dtype in ['int64', 'Int64']:
            potential_int_cols.append(col)
        elif df[col].dtype in ['float64']:
            # Проверяем, все ли значения целые (например, 1.0, 2.0)
            if (df[col].dropna() % 1 == 0).all():
                potential_int_cols.append(col)

    # --------------------------------------------
    # Подсказка для categorical_columns
    # --------------------------------------------
    if low_cardinality_cols:
        print("\n" + "="*60)
        print("💡 ПОДСКАЗКА 1: КАТЕГОРИАЛЬНЫЕ КОЛОНКИ")
        print("   Эти колонки имеют мало уникальных значений (<20).")
        print("   Их рекомендуется добавить в список 'categorical_columns'")
        print("   в блоке настроек проекта.\n")
        print("   Скопируй этот список в categorical_columns:")
        print(f"   categorical_columns = {low_cardinality_cols}")
        print("="*60)

    # --------------------------------------------
    # Подсказка для int_columns
    # --------------------------------------------
    if potential_int_cols:
        print("\n" + "="*60)
        print("💡 ПОДСКАЗКА 2: ЦЕЛОЧИСЛЕННЫЕ КОЛОНКИ")
        print("   Эти колонки являются целыми числами.")
        print("   Их рекомендуется добавить в список 'int_columns'")
        print("   в блоке настроек проекта.\n")
        print("   Скопируй этот список в int_columns:")
        print(f"   int_columns = {potential_int_cols}")
        print("="*60)

    # --------------------------------------------
    # Сохранение отчета об осмотре
    # --------------------------------------------
    print("\n--- СОХРАНЕНИЕ ОТЧЕТА ---")

    # Создаем текстовый отчет
    report_lines = []
    report_lines.append("=" * 50)
    report_lines.append("ОТЧЕТ ОБ ОСМОТРЕ ДАННЫХ")
    report_lines.append("=" * 50)
    report_lines.append(f"Дата осмотра: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append(f"Файл: {FILE_ID if LOAD_MODE == 'drive' else LOCAL_DATA_PATH}")
    report_lines.append(f"Размер: {df.shape[0]} строк, {df.shape[1]} колонок")
    report_lines.append("")
    report_lines.append("КОЛОНКИ:")
    report_lines.append(str(df.columns.tolist()))
    report_lines.append("")
    report_lines.append("ТИПЫ ДАННЫХ:")
    report_lines.append(str(df.dtypes.to_dict()))
    report_lines.append("")
    report_lines.append("ПРОПУСКИ:")
    missing_dict = df.isnull().sum().to_dict()
    report_lines.append(str({k: v for k, v in missing_dict.items() if v > 0}))
    report_lines.append("")
    report_lines.append("ДУБЛИКАТЫ СТРОК:")
    report_lines.append(str(df.duplicated().sum()))

    # Сохраняем отчет в файл
    report_path = f'{REPORTS_PATH}/data_report.txt'
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report_lines))

    print(f"✓ Отчет сохранен: {report_path}")

--- ДИАПАЗОНЫ ЧИСЛОВЫХ КОЛОНОК ---
id: min = 67, max = 72940
age: min = 0.08, max = 82.0
hypertension: min = 0, max = 1
heart_disease: min = 0, max = 1
avg_glucose_level: min = 55.12, max = 271.74
bmi: min = 10.3, max = 97.6
stroke: min = 0, max = 1

--- ПУСТЫЕ СТРОКИ В ТЕКСТОВЫХ КОЛОНКАХ ---
Пустых строк ('' вместо NaN) не обнаружено

--- ПОДОЗРИТЕЛЬНЫЕ ЗНАЧЕНИЯ ---
id: 1 раз встречается 99
hypertension: 4612 раз встречается 0
heart_disease: 4834 раз встречается 0
avg_glucose_level: 2 раз встречается 99
stroke: 4861 раз встречается 0

--- УНИКАЛЬНЫЕ ЗНАЧЕНИЯ (колонки с < 20 вариантов) ---

gender (3 уникальных значений):
['Male' 'Female' 'Other']

hypertension (2 уникальных значений):
[0 1]

heart_disease (2 уникальных значений):
[1 0]

ever_married (2 уникальных значений):
['Yes' 'No']

work_type (5 уникальных значений):
['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']

Residence_type (2 уникальных значений):
['Urban' 'Rural']

smoking_status (4 уникальных значений):
['formerly smoked' 'never smoked' 'smokes' 'Unknown']

stroke (2 уникальных значений):
[1 0]

============================================================
💡 ПОДСКАЗКА 1: КАТЕГОРИАЛЬНЫЕ КОЛОНКИ
   Эти колонки имеют мало уникальных значений (<20).
   Их рекомендуется добавить в список 'categorical_columns'
   в блоке настроек проекта.

   Скопируй этот список в categorical_columns:
   categorical_columns = ['gender', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'smoking_status', 'stroke']
============================================================

============================================================
💡 ПОДСКАЗКА 2: ЦЕЛОЧИСЛЕННЫЕ КОЛОНКИ
   Эти колонки являются целыми числами.
   Их рекомендуется добавить в список 'int_columns'
   в блоке настроек проекта.

   Скопируй этот список в int_columns:
   int_columns = ['id', 'hypertension', 'heart_disease', 'stroke']
============================================================

--- СОХРАНЕНИЕ ОТЧЕТА ---
✓ Отчет сохранен: /content/drive/MyDrive/ml_learning/datasets/stroke_test/reports/data_report.txt

# БЛОК 3. Предобработка данных

# Ручное rename_dict

In [ ]:
# 3.1 ПЕРЕИМЕНОВАНИЕ КОЛОНОК

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("📝 ПЕРЕИМЕНОВАНИЕ КОЛОНОК")
    print("="*50)

    # Сохраняем старые названия для сравнения
    old_columns = df.columns.tolist()

    # Автоматическая чистка
    df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]

    # Проверяем, какие колонки изменились
    changed_cols = []
    for old, new in zip(old_columns, df.columns):
        if old != new:
            changed_cols.append(f"{old} → {new}")

    if changed_cols:
        print("\n✓ Автоматическая чистка выполнена:")
        for change in changed_cols:
            print(f"   {change}")
    else:
        print("\n✓ Названия колонок уже в правильном формате")

    # Проверка на дубликаты
    if len(df.columns) != len(set(df.columns)):
        duplicates = df.columns[df.columns.duplicated()].tolist()
        print(f"\n⚠️ ВНИМАНИЕ: Обнаружены дубликаты колонок: {duplicates}")
        print("   Это может вызвать проблемы при дальнейшей обработке!")

    # Ручное переименование (раскомментируйте и заполните при необходимости)
    # --------------------------------------------
    # rename_dict = {
    #     'старое_название': 'новое_название',
    #     # добавьте свои пары...
    # }
    #
    # if rename_dict:
    #     existing_rename = {k: v for k, v in rename_dict.items() if k in df.columns}
    #     if existing_rename:
    #         df = df.rename(columns=existing_rename)
    #         print(f"\n✓ Ручное переименование:")
    #         for old, new in existing_rename.items():
    #             print(f"   {old} → {new}")
    #     else:
    #         print("\n⚠️ Колонки для ручного переименования не найдены")

    # Итоговый список колонок
    print(f"\n📋 Итоговые колонки ({len(df.columns)}):")
    print(f"   {df.columns.tolist()}")

    print("\n" + "="*50)
    print("✓ Переименование завершено")
    print("="*50 + "\n")

==================================================
📝 ПЕРЕИМЕНОВАНИЕ КОЛОНОК
==================================================

✓ Автоматическая чистка выполнена:
   Residence_type → residence_type

📋 Итоговые колонки (12):
   ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

==================================================
✓ Переименование завершено
==================================================

In [ ]:
# 3.2 ПРИВЕДЕНИЕ ТИПОВ ДАННЫХ

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🔧 ПРИВЕДЕНИЕ ТИПОВ ДАННЫХ")
    print("="*50)

    # Преобразование в даты
    if date_columns:
        print("\n📅 ДАТЫ:")
        for col in date_columns:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors='coerce')
                print(f"   ✓ {col} → datetime")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n📅 ДАТЫ: не заданы")

    # Преобразование в целые числа с поддержкой NaN
    if int_columns:
        print("\n🔢 ЦЕЛЫЕ ЧИСЛА (Int64):")
        for col in int_columns:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
                print(f"   ✓ {col} → Int64")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n🔢 ЦЕЛЫЕ ЧИСЛА: не заданы")

    # Преобразование в числа с плавающей точкой
    if float_columns:
        print("\n📊 ВЕЩЕСТВЕННЫЕ ЧИСЛА (float64):")
        for col in float_columns:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')
                print(f"   ✓ {col} → float64")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n📊 ВЕЩЕСТВЕННЫЕ ЧИСЛА: не заданы")

    # Преобразование в категории
    if categorical_columns:
        print("\n🏷️ КАТЕГОРИИ:")
        for col in categorical_columns:
            if col in df.columns:
                df[col] = df[col].astype('category')
                print(f"   ✓ {col} → category")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена, пропускаем")
    else:
        print("\n🏷️ КАТЕГОРИИ: не заданы")

    # Итоговые типы данных
    print("\n📋 ИТОГОВЫЕ ТИПЫ ДАННЫХ:")
    print(df.dtypes)

    print("\n" + "="*50)
    print("✓ Приведение типов завершено")
    print("="*50 + "\n")

==================================================
🔧 ПРИВЕДЕНИЕ ТИПОВ ДАННЫХ
==================================================

📅 ДАТЫ: не заданы

🔢 ЦЕЛЫЕ ЧИСЛА (Int64):
   ✓ hypertension → Int64
   ✓ heart_disease → Int64

📊 ВЕЩЕСТВЕННЫЕ ЧИСЛА (float64):
   ✓ age → float64
   ✓ avg_glucose_level → float64
   ✓ bmi → float64

🏷️ КАТЕГОРИИ:
   ✓ gender → category
   ✓ ever_married → category
   ✓ work_type → category
   ⚠️ Колонка 'Residence_type' не найдена, пропускаем
   ✓ smoking_status → category

📋 ИТОГОВЫЕ ТИПЫ ДАННЫХ:
id                      int64
gender               category
age                   float64
hypertension            Int64
heart_disease           Int64
ever_married         category
work_type            category
residence_type         object
avg_glucose_level     float64
bmi                   float64
smoking_status       category
stroke                  int64
dtype: object

==================================================
✓ Приведение типов завершено
==================================================

In [ ]:
# 3.3 УДАЛЕНИЕ НЕНУЖНЫХ КОЛОНОК

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🗑️ УДАЛЕНИЕ НЕНУЖНЫХ КОЛОНОК")
    print("="*50)

    if columns_to_drop:
        existing_cols = [col for col in columns_to_drop if col in df.columns]
        missing_cols = [col for col in columns_to_drop if col not in df.columns]

        if existing_cols:
            df.drop(columns=existing_cols, inplace=True)
            print(f"\n✓ Удалены колонки: {existing_cols}")
        else:
            print("\n⚠️ Указанные колонки не найдены в датасете")

        if missing_cols:
            print(f"⚠️ Колонки не найдены: {missing_cols}")
    else:
        print("\n✓ Нет колонок для удаления")

    print(f"\n📋 Итоговые колонки ({len(df.columns)}):")
    print(f"   {df.columns.tolist()}")

    print("\n" + "="*50)
    print("✓ Удаление колонок завершено")
    print("="*50 + "\n")

==================================================
🗑️ УДАЛЕНИЕ НЕНУЖНЫХ КОЛОНОК
==================================================

✓ Удалены колонки: ['id']

📋 Итоговые колонки (11):
   ['gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

==================================================
✓ Удаление колонок завершено
==================================================

In [ ]:
# 3.4 ОБРАБОТКА АНОМАЛИЙ

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🧹 ОБРАБОТКА АНОМАЛИЙ")
    print("="*50)

    initial_len = len(df)
    deleted_summary = {}

    # --------------------------------------------
    # 1. Удаление пропусков
    # --------------------------------------------
    if DROP_ROWS_WITH_NULLS and COLUMNS_TO_CHECK_NULLS:
        print("\n--- 1. Удаление строк с пропусками ---")
        for col in COLUMNS_TO_CHECK_NULLS:
            if col in df.columns:
                nulls_before = df[col].isna().sum()
                if nulls_before > 0:
                    df.dropna(subset=[col], inplace=True)
                    deleted_summary[f'Пропуски в {col}'] = nulls_before
                    print(f"   ✓ {col}: удалено {nulls_before} строк")
                else:
                    print(f"   ✓ {col}: пропусков нет")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")

    # --------------------------------------------
    # 2. Удаление по диапазонам
    # --------------------------------------------
    if DROP_OUT_OF_RANGE and NUMERIC_RANGES:
        print("\n--- 2. Удаление значений вне диапазонов ---")
        for col, (min_val, max_val) in NUMERIC_RANGES.items():
            if col in df.columns:
                before = len(df)
                df = df[(df[col] >= min_val) & (df[col] <= max_val)]
                deleted = before - len(df)
                if deleted > 0:
                    deleted_summary[f'Диапазон {col} [{min_val}, {max_val}]'] = deleted
                    print(f"   ✓ {col}: удалено {deleted} строк")
                else:
                    print(f"   ✓ {col}: все значения в диапазоне")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")

    # --------------------------------------------
    # 3. Удаление редких категорий
    # --------------------------------------------
    if DROP_RARE_CATEGORIES and COLUMNS_TO_CHECK_RARE:
        print("\n--- 3. Удаление редких категорий ---")
        for col in COLUMNS_TO_CHECK_RARE:
            if col in df.columns:
                before = len(df)
                value_counts = df[col].value_counts(normalize=True)
                rare_values = value_counts[value_counts < RARE_CATEGORY_THRESHOLD].index.tolist()
                rare_values = [v for v in rare_values if v not in RARE_CATEGORIES_TO_KEEP]

                if rare_values:
                    df = df[~df[col].isin(rare_values)]
                    deleted = before - len(df)
                    deleted_summary[f'Редкие в {col}'] = deleted
                    print(f"   ✓ {col}: удалено {deleted} строк, редкие: {rare_values}")
                else:
                    print(f"   ✓ {col}: редких категорий нет")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")

    # --------------------------------------------
    # 4. Сброс индекса
    # --------------------------------------------
    df.reset_index(drop=True, inplace=True)

    # --------------------------------------------
    # 5. Проверка на чрезмерное удаление
    # --------------------------------------------
    if len(df) < initial_len * 0.5:
        print("\n⚠️ ВНИМАНИЕ: Удалено более 50% строк!")
        print("   Проверьте настройки диапазонов и порогов в блоке 1.3")

    # --------------------------------------------
    # ИТОГИ
    # --------------------------------------------
    print("\n" + "="*60)
    print("📊 ИТОГИ УДАЛЕНИЯ АНОМАЛИЙ")
    print("="*60)

    if deleted_summary:
        print(f"\n{'Причина удаления':<35} {'Строк':>10} {'%':>10}")
        print("-" * 60)
        for reason, count in deleted_summary.items():
            pct = count / initial_len * 100
            print(f"{reason:<35} {count:>10} {pct:>9.2f}%")

        total_deleted = initial_len - len(df)
        total_pct = total_deleted / initial_len * 100
        print("-" * 60)
        print(f"{'ВСЕГО УДАЛЕНО':<35} {total_deleted:>10} {total_pct:>9.2f}%")
        print(f"{'ОСТАЛОСЬ СТРОК':<35} {len(df):>10}")
    else:
        print("\n✓ Аномалий не обнаружено, строки не удалялись")
        print(f"✓ Осталось строк: {len(df)}")

    print("="*60)
    print("\n✓ Обработка аномалий завершена\n")

==================================================
🧹 ОБРАБОТКА АНОМАЛИЙ
==================================================

--- 1. Удаление строк с пропусками ---
   ✓ bmi: удалено 201 строк

--- 2. Удаление значений вне диапазонов ---
   ✓ age: удалено 42 строк
   ✓ bmi: удалено 13 строк
   ✓ avg_glucose_level: все значения в диапазоне

--- 3. Удаление редких категорий ---
   ✓ gender: удалено 1 строк, редкие: ['Other']

============================================================
📊 ИТОГИ УДАЛЕНИЯ АНОМАЛИЙ
============================================================

Причина удаления                         Строк          %
------------------------------------------------------------
Пропуски в bmi                             201      3.93%
Диапазон age [1, 82]                        42      0.82%
Диапазон bmi [10, 60]                       13      0.25%
Редкие в gender                              1      0.02%
------------------------------------------------------------
ВСЕГО УДАЛЕНО                              257      5.03%
ОСТАЛОСЬ СТРОК                            4853
============================================================

✓ Обработка аномалий завершена

In [ ]:
# 3.5 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ (после структурирования)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ")
    print("="*50)

    structure_backup_path = os.path.join(CHECKPOINT_PATH, '01_structure.csv')
    df.to_csv(structure_backup_path, index=False)

    print(f"\n✓ Контрольная точка сохранена:")
    print(f"   checkpoints/01_structure.csv")
    print(f"   Размер: {len(df)} строк, {len(df.columns)} колонок")

    print("\n" + "="*50 + "\n")

==================================================
💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ
==================================================

✓ Контрольная точка сохранена:
   checkpoints/01_structure.csv
   Размер: 4853 строк, 11 колонок

==================================================

# БЛОК 4. Очистка данных

In [ ]:
# 4.1 МЕХАНИЧЕСКАЯ ОЧИСТКА ТЕКСТА И КАТЕГОРИЙ

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🧼 МЕХАНИЧЕСКАЯ ОЧИСТКА")
    print("="*50)

    # --------------------------------------------
    # 1. Очистка текстовых колонок (из настроек)
    # --------------------------------------------
    print("\n--- 1. Текстовые колонки (из text_columns) ---")

    if text_columns:
        for col in text_columns:
            if col in df.columns:
                # Для категориальных колонок сначала преобразуем в object
                if df[col].dtype.name == 'category':
                    df[col] = df[col].astype(object)

                mask = df[col].notna()
                if mask.any():
                    df.loc[mask, col] = df.loc[mask, col].astype(str).str.strip().str.lower()
                print(f"   ✓ {col}: strip + lower")
            else:
                print(f"   ⚠️ Колонка '{col}' не найдена")
    else:
        print("   ✓ Нет текстовых колонок в настройках")

    # --------------------------------------------
    # 2. Очистка категориальных колонок (автоматически)
    # --------------------------------------------
    print("\n--- 2. Категориальные колонки (автоопределение) ---")

    categorical_cols = df.select_dtypes(include=['category', 'object']).columns.tolist()
    categorical_cols = [col for col in categorical_cols if col not in text_columns]

    if categorical_cols:
        for col in categorical_cols:
            # Для категориальных колонок сначала преобразуем в object
            is_categorical = df[col].dtype.name == 'category'
            if is_categorical:
                df[col] = df[col].astype(object)

            mask = df[col].notna()
            if mask.any():
                df.loc[mask, col] = df.loc[mask, col].astype(str).str.strip().str.lower()
                df.loc[mask, col] = df.loc[mask, col].str.replace(' ', '_')

            print(f"   ✓ {col}: strip + lower + пробелы→'_'")
    else:
        print("   ✓ Нет категориальных колонок для очистки")

    # --------------------------------------------
    # 3. Проверка на появление 'nan' как строки
    # --------------------------------------------
    print("\n--- 3. Проверка на строки 'nan' ---")
    nan_string_cols = []
    for col in df.select_dtypes(include=['object', 'category']).columns:
        if (df[col] == 'nan').any():
            count = (df[col] == 'nan').sum()
            nan_string_cols.append(f"{col} ({count})")

    if nan_string_cols:
        print(f"   ⚠️ Обнаружены строки 'nan': {', '.join(nan_string_cols)}")
    else:
        print("   ✓ Строк 'nan' не обнаружено")

    print("\n" + "="*50)
    print("✓ Механическая очистка завершена")
    print("="*50 + "\n")

==================================================
🧼 МЕХАНИЧЕСКАЯ ОЧИСТКА
==================================================

--- 1. Текстовые колонки (из text_columns) ---
   ✓ Нет текстовых колонок в настройках

--- 2. Категориальные колонки (автоопределение) ---
   ✓ gender: strip + lower + пробелы→'_'
   ✓ ever_married: strip + lower + пробелы→'_'
   ✓ work_type: strip + lower + пробелы→'_'
   ✓ residence_type: strip + lower + пробелы→'_'
   ✓ smoking_status: strip + lower + пробелы→'_'

--- 3. Проверка на строки 'nan' ---
   ✓ Строк 'nan' не обнаружено

==================================================
✓ Механическая очистка завершена
==================================================

In [ ]:
# 4.2 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ (перед разбиением)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ")
    print("="*50)

    cleaned_backup_path = os.path.join(CHECKPOINT_PATH, '02_cleaned.csv')
    df.to_csv(cleaned_backup_path, index=False)

    print(f"\n✓ Контрольная точка сохранена:")
    print(f"   checkpoints/02_cleaned.csv")
    print(f"   Размер: {len(df)} строк, {len(df.columns)} колонок")

    print("\n" + "="*50 + "\n")

==================================================
💾 СОХРАНЕНИЕ КОНТРОЛЬНОЙ ТОЧКИ
==================================================

✓ Контрольная точка сохранена:
   checkpoints/02_cleaned.csv
   Размер: 4853 строк, 11 колонок

==================================================

# БЛОК 5. Разделение данных

In [ ]:
# 5.1 ПОДГОТОВКА К РАЗДЕЛЕНИЮ (СОЗДАНИЕ X И y)

if df is None or df.empty:
    print("❌ Данные не загружены. Пропускаем.")
else:
    print("\n" + "="*50)
    print("🎯 ПОДГОТОВКА К РАЗДЕЛЕНИЮ")
    print("="*50)

    # Проверка целевой колонки
    if not TARGET_COLUMN:
        print("\n⚠️ ВНИМАНИЕ: Целевая колонка не указана!")
        print("   Укажите TARGET_COLUMN в блоке 1.3")
    elif TARGET_COLUMN not in df.columns:
        print(f"\n❌ ОШИБКА: Колонка '{TARGET_COLUMN}' не найдена")
        print(f"   Доступные колонки: {df.columns.tolist()}")
    else:
        # Проверка на пропуски в целевой колонке
        null_count = df[TARGET_COLUMN].isna().sum()
        if null_count > 0:
            print(f"\n⚠️ В целевой колонке '{TARGET_COLUMN}' {null_count} пропусков")
            print("   Рекомендуется удалить эти строки перед разбиением")
        else:
            print(f"\n✓ Целевая колонка '{TARGET_COLUMN}' — пропусков нет")

        # --------------------------------------------
        # Отделение признаков (X) и цели (y)
        # --------------------------------------------
        print("\n--- Отделение X и y ---")

        X = df.drop(columns=[TARGET_COLUMN])
        y = df[TARGET_COLUMN]

        print(f"✓ Признаки X: {X.shape[0]} строк, {X.shape[1]} колонок")
        print(f"✓ Целевая переменная y: {len(y)} значений")

        # --------------------------------------------
        # Информация о целевой переменной
        # --------------------------------------------
        print("\n--- Информация о целевой переменной ---")

        if y.dtype in ['int64', 'Int64', 'float64', 'int32', 'float32']:
            print(f"   Тип: числовой")
            print(f"   Уникальных значений: {y.nunique()}")
            if y.nunique() <= 10:
                print(f"   Диапазон: {y.min()} — {y.max()}")
        else:
            print(f"   Тип: {y.dtype}")
            print(f"   Уникальных значений: {y.nunique()}")
            if y.nunique() <= 20:
                print(f"   Значения: {sorted(y.unique().tolist())}")

        # --------------------------------------------
        # Определение типа задачи
        # --------------------------------------------
        if FORCE_TASK_TYPE:
            is_classification = FORCE_TASK_TYPE == 'classification'
            task_source = "принудительно"
        else:
            is_classification = y.dtype not in ['int64', 'Int64', 'float64', 'int32', 'float32'] or y.nunique() <= 10
            task_source = "автоопределение"

        print(f"\n📊 Тип задачи: {'классификация' if is_classification else 'регрессия'} ({task_source})")

        # --------------------------------------------
        # Анализ дисбаланса классов (для классификации)
        # --------------------------------------------
        if is_classification and y.nunique() <= 20:
            print("\n--- Анализ дисбаланса классов ---")

            class_counts = y.value_counts()
            total = len(y)
            n_classes = len(class_counts)
            max_count = class_counts.max()
            min_count = class_counts.min()
            ratio = max_count / min_count

            print(f"   Всего классов: {n_classes}")
            print(f"   Соотношение max/min: {ratio:.1f}:1")
            print(f"\n   Распределение:")
            for cls, count in class_counts.items():
                pct = count / total * 100
                bar = '█' * int(pct / 2)
                print(f"   Класс {cls}: {count:>6} ({pct:>5.1f}%) {bar}")

            if ratio > 3:
                print(f"\n   ⚠️ Обнаружен дисбаланс классов ({ratio:.1f}:1)")
                print("   💡 Рекомендации:")
                print("      - Использовать class_weight='balanced'")
                print("      - Или применить SMOTE для балансировки")
            elif ratio > 1.5:
                print(f"\n   ℹ️ Умеренный дисбаланс ({ratio:.1f}:1)")
                print("      Можно использовать class_weight='balanced'")
            else:
                print(f"\n   ✓ Классы сбалансированы ({ratio:.1f}:1)")
        else:
            print("\n--- Анализ дисбаланса ---")
            print("   ℹ️ Задача регрессии или много классов — не применимо")

        print("\n" + "="*50)
        print("✓ Подготовка к разделению завершена")
        print("="*50 + "\n")

==================================================
🎯 ПОДГОТОВКА К РАЗДЕЛЕНИЮ
==================================================

✓ Целевая колонка 'stroke' — пропусков нет

--- Отделение X и y ---
✓ Признаки X: 4853 строк, 10 колонок
✓ Целевая переменная y: 4853 значений

--- Информация о целевой переменной ---
   Тип: числовой
   Уникальных значений: 2
   Диапазон: 0 — 1

📊 Тип задачи: классификация (принудительно)

--- Анализ дисбаланса классов ---
   Всего классов: 2
   Соотношение max/min: 22.2:1

   Распределение:
   Класс 0:   4644 ( 95.7%) ███████████████████████████████████████████████
   Класс 1:    209 (  4.3%) ██

   ⚠️ Обнаружен дисбаланс классов (22.2:1)
   💡 Рекомендации:
      - Использовать class_weight='balanced'
      - Или применить SMOTE для балансировки

==================================================
✓ Подготовка к разделению завершена
==================================================

In [ ]:
# 5.2 РАЗДЕЛЕНИЕ НА ТРИ ВЫБОРКИ (TRAIN / VAL / TEST)

print("\n" + "="*50)
print("✂️ РАЗДЕЛЕНИЕ НА ВЫБОРКИ")
print("="*50)

# Проверка готовности
if not is_split_ready(df, X, TARGET_COLUMN):
    X_train = X_val = X_test = y_train = y_val = y_test = None
    print("❌ Разделение отменено")
else:
    # Определение типа задачи
    if FORCE_TASK_TYPE:
        is_classification = FORCE_TASK_TYPE == 'classification'
    else:
        is_classification = y.nunique() <= 10

    # Проверка минимального размера
    min_samples = 30
    if len(X) < min_samples:
        print(f"\n⚠️ КРИТИЧЕСКОЕ ПРЕДУПРЕЖДЕНИЕ: Датасет слишком маленький!")
        print(f"   Текущий размер: {len(X)} строк")
        print(f"   Минимальный размер для разбиения: {min_samples} строк")
        print(f"\n   Рекомендации:")
        print(f"   - Собрать больше данных")
        print(f"   - Использовать кросс-валидацию вместо train/val/test")
        print(f"\n❌ Разделение отменено")
        X_train = X_val = X_test = y_train = y_val = y_test = None
    else:
        # Проверка маленьких классов
        if is_classification:
            class_counts = y.value_counts()
            small_classes = class_counts[class_counts < 3].index.tolist()
            if small_classes:
                print(f"\n⚠️ ВНИМАНИЕ: Обнаружены классы с < 3 примерами:")
                for cls in small_classes:
                    print(f"   Класс '{cls}': {class_counts[cls]} примеров")
                print(f"   Стратификация может работать некорректно")

        # Первое разделение: train + temp
        temp_size = SPLIT_VAL_SIZE + SPLIT_TEST_SIZE
        print(f"\n--- Шаг 1: train ({SPLIT_TRAIN_SIZE:.0%}) + temp ({temp_size:.0%}) ---")

        X_train, X_temp, y_train, y_temp = train_test_split(
            X, y,
            test_size=temp_size,
            random_state=RANDOM_STATE,
            stratify=y if is_classification else None
        )

        print(f"   Train: {len(X_train)} строк ({len(X_train)/len(X)*100:.1f}%)")
        print(f"   Temp:  {len(X_temp)} строк ({len(X_temp)/len(X)*100:.1f}%)")

        # Второе разделение: temp → val + test
        print(f"\n--- Шаг 2: temp → val ({SPLIT_VAL_SIZE:.0%}) + test ({SPLIT_TEST_SIZE:.0%}) ---")

        X_val, X_test, y_val, y_test = train_test_split(
            X_temp, y_temp,
            test_size=SPLIT_TEST_SIZE / temp_size,
            random_state=RANDOM_STATE,
            stratify=y_temp if is_classification else None
        )

        print(f"   Val:  {len(X_val)} строк ({len(X_val)/len(X)*100:.1f}%)")
        print(f"   Test: {len(X_test)} строк ({len(X_test)/len(X)*100:.1f}%)")

        # Итоговые размеры
        print("\n--- Итоговые размеры ---")
        print(f"   Train: {len(X_train):>6} ({len(X_train)/len(X)*100:>5.1f}%)")
        print(f"   Val:   {len(X_val):>6} ({len(X_val)/len(X)*100:>5.1f}%)")
        print(f"   Test:  {len(X_test):>6} ({len(X_test)/len(X)*100:>5.1f}%)")
        print(f"   Всего: {len(X):>6} (100%)")

        # Финальная проверка
        print("\n--- Финальная проверка ---")

        if len(X_train) == 0 or len(X_val) == 0 or len(X_test) == 0:
            print("   ❌ ОШИБКА: Одна из выборок пуста!")
        else:
            print("   ✓ Все выборки содержат данные")

        # Проверка классов в выборках
        if is_classification:
            train_classes = set(y_train.unique())
            val_classes = set(y_val.unique())
            test_classes = set(y_test.unique())
            all_classes = set(y.unique())

            if len(train_classes) < len(all_classes):
                missing = all_classes - train_classes
                print(f"   ⚠️ В train отсутствуют классы: {missing}")
            else:
                print(f"   ✓ Все классы присутствуют в train")

            # --------------------------------------------
            # ДЕТАЛЬНОЕ РАСПРЕДЕЛЕНИЕ КЛАССОВ
            # --------------------------------------------
            print("\n--- Распределение классов по выборкам ---")

            # Получаем распределение в исходных данных
            original_dist = y.value_counts(normalize=True)

            # Распределение по выборкам
            train_dist = y_train.value_counts(normalize=True)
            val_dist = y_val.value_counts(normalize=True)
            test_dist = y_test.value_counts(normalize=True)

            # Вывод таблицы
            print(f"\n   {'Класс':<10} {'Исходное':>10} {'Train':>10} {'Val':>10} {'Test':>10}")
            print("   " + "-" * 52)

            for cls in sorted(all_classes):
                orig_pct = original_dist.get(cls, 0) * 100
                train_pct = train_dist.get(cls, 0) * 100
                val_pct = val_dist.get(cls, 0) * 100
                test_pct = test_dist.get(cls, 0) * 100

                # Абсолютные значения
                train_abs = (y_train == cls).sum()
                val_abs = (y_val == cls).sum()
                test_abs = (y_test == cls).sum()

                print(f"   {str(cls):<10} {orig_pct:>9.1f}% {train_pct:>9.1f}% {val_pct:>9.1f}% {test_pct:>9.1f}%")

            print("\n   Абсолютные значения:")
            print(f"   {'Класс':<10} {'Train':>10} {'Val':>10} {'Test':>10}")
            print("   " + "-" * 42)
            for cls in sorted(all_classes):
                train_abs = (y_train == cls).sum()
                val_abs = (y_val == cls).sum()
                test_abs = (y_test == cls).sum()
                print(f"   {str(cls):<10} {train_abs:>10} {val_abs:>10} {test_abs:>10}")

            # Проверка качества стратификации
            print("\n   📊 Проверка стратификации:")
            max_deviation = 0
            for cls in sorted(all_classes):
                orig = original_dist[cls]
                train_dev = abs(train_dist.get(cls, 0) - orig) / orig * 100
                val_dev = abs(val_dist.get(cls, 0) - orig) / orig * 100
                test_dev = abs(test_dist.get(cls, 0) - orig) / orig * 100
                max_deviation = max(max_deviation, train_dev, val_dev, test_dev)

            if max_deviation < 5:
                print("   ✓ Отклонение <5% — стратификация работает отлично")
            elif max_deviation < 10:
                print(f"   ⚡ Отклонение {max_deviation:.1f}% — стратификация приемлема")
            else:
                print(f"   ⚠️ Отклонение {max_deviation:.1f}% — возможен дисбаланс")

        # Параметры разбиения
        print(f"\n📌 Параметры разбиения:")
        print(f"   train={SPLIT_TRAIN_SIZE:.0%}, val={SPLIT_VAL_SIZE:.0%}, test={SPLIT_TEST_SIZE:.0%}")
        print(f"   random_state={RANDOM_STATE}")
        if is_classification:
            print(f"   stratify=True")

print("\n" + "="*50)
print("✓ Разделение завершено")
print("="*50 + "\n")

==================================================
✂️ РАЗДЕЛЕНИЕ НА ВЫБОРКИ
==================================================

--- Шаг 1: train (60%) + temp (40%) ---
   Train: 2911 строк (60.0%)
   Temp:  1942 строк (40.0%)

--- Шаг 2: temp → val (20%) + test (20%) ---
   Val:  971 строк (20.0%)
   Test: 971 строк (20.0%)

--- Итоговые размеры ---
   Train:   2911 ( 60.0%)
   Val:      971 ( 20.0%)
   Test:     971 ( 20.0%)
   Всего:   4853 (100%)

--- Финальная проверка ---
   ✓ Все выборки содержат данные
   ✓ Все классы присутствуют в train

--- Распределение классов по выборкам ---

   Класс        Исходное      Train        Val       Test
   ----------------------------------------------------
   0               95.7%      95.7%      95.7%      95.7%
   1                4.3%       4.3%       4.3%       4.3%

   Абсолютные значения:
   Класс           Train        Val       Test
   ------------------------------------------
   0                2786        929        929
   1                 125         42         42

   📊 Проверка стратификации:
   ✓ Отклонение <5% — стратификация работает отлично

📌 Параметры разбиения:
   train=60%, val=20%, test=20%
   random_state=42
   stratify=True

==================================================
✓ Разделение завершено
==================================================

# БЛОК 6. Анализ train

In [ ]:
# 6.1 ПРОВЕРКА НА ВЫБРОСЫ В TRAIN ВЫБОРКЕ

print("\n" + "="*50)
print("🔍 ПРОВЕРКА НА ВЫБРОСЫ (TRAIN)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    print(f"\n📐 Метод: IQR, коэффициент = {OUTLIER_IQR_COEFF}")

    # Находим числовые колонки
    numeric_cols_train = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()

    if len(numeric_cols_train) == 0:
        print("\nℹ️ Нет числовых колонок для анализа выбросов")
    else:
        outlier_info = []

        for col in numeric_cols_train:
            Q1 = X_train[col].quantile(0.25)
            Q3 = X_train[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - OUTLIER_IQR_COEFF * IQR
            upper_bound = Q3 + OUTLIER_IQR_COEFF * IQR

            outliers = X_train[(X_train[col] < lower_bound) | (X_train[col] > upper_bound)]
            outlier_count = len(outliers)
            outlier_pct = outlier_count / len(X_train) * 100

            # Определяем уровень
            if outlier_pct == 0:
                level = "🟢"
            elif outlier_pct < 5:
                level = "🟢"
            elif outlier_pct < 10:
                level = "🟡"
            else:
                level = "🔴"

            outlier_info.append({
                'col': col,
                'count': outlier_count,
                'pct': outlier_pct,
                'bounds': (lower_bound, upper_bound),
                'level': level
            })

        if outlier_info:
            print("\n⚠️ Обнаружены выбросы:\n")
            print(f"   {'':<3} {'Колонка':<22} {'Выбросов':>10} {'%':>8} {'Границы [низ, верх]':>32}")
            print("   " + "-" * 80)

            for info in outlier_info:
                bounds_str = f"[{info['bounds'][0]:.2f}, {info['bounds'][1]:.2f}]"
                print(f"   {info['level']} {info['col']:<20} {info['count']:>10} {info['pct']:>7.1f}% {bounds_str:>32}")

            # Сводка по уровням
            print("\n💡 Рекомендации:")

            high_outlier_cols = [info for info in outlier_info if info['pct'] > 10]
            medium_outlier_cols = [info for info in outlier_info if 5 <= info['pct'] <= 10]
            low_outlier_cols = [info for info in outlier_info if 0 < info['pct'] < 5]
            no_outlier_cols = [info for info in outlier_info if info['pct'] == 0]

            if high_outlier_cols:
                cols = ', '.join([info['col'] for info in high_outlier_cols])
                print(f"\n   🔴 Высокий % выбросов (>10%): {cols}")
                print("      → Проверьте данные на ошибки или используйте RobustScaler")

            if medium_outlier_cols:
                cols = ', '.join([info['col'] for info in medium_outlier_cols])
                print(f"\n   🟡 Умеренный % выбросов (5-10%): {cols}")
                print("      → Рассмотрите clipping (обрезание по квантилям)")

            if low_outlier_cols:
                cols = ', '.join([info['col'] for info in low_outlier_cols])
                print(f"\n   🟢 Низкий % выбросов (<5%): {cols}")
                print("      → Можно оставить, большинство моделей устойчивы")

            if no_outlier_cols:
                cols = ', '.join([info['col'] for info in no_outlier_cols])
                print(f"\n   ✅ Нет выбросов: {cols}")
        else:
            print("\n✅ Выбросов не обнаружено")

print("\n" + "="*50)
print("✓ Проверка на выбросы завершена")
print("="*50 + "\n")

==================================================
🔍 ПРОВЕРКА НА ВЫБРОСЫ (TRAIN)
==================================================

📐 Метод: IQR, коэффициент = 1.5

⚠️ Обнаружены выбросы:

       Колонка                  Выбросов        %              Границы [низ, верх]
   --------------------------------------------------------------------------------
   🟢 age                           0     0.0%                 [-26.50, 113.50]
   🟡 hypertension                278     9.5%                     [0.00, 0.00]
   🟢 heart_disease               145     5.0%                     [0.00, 0.00]
   🔴 avg_glucose_level           347    11.9%                  [21.67, 167.47]
   🟢 bmi                          60     2.1%                    [9.85, 47.05]

💡 Рекомендации:

   🔴 Высокий % выбросов (>10%): avg_glucose_level
      → Проверьте данные на ошибки или используйте RobustScaler

   🟡 Умеренный % выбросов (5-10%): hypertension
      → Рассмотрите clipping (обрезание по квантилям)

   🟢 Низкий % выбросов (<5%): heart_disease, bmi
      → Можно оставить, большинство моделей устойчивы

   ✅ Нет выбросов: age

==================================================
✓ Проверка на выбросы завершена
==================================================

In [ ]:
# 6.2 КОРРЕЛЯЦИЯ ЧИСЛОВЫХ ПРИЗНАКОВ (TRAIN)

print("\n" + "="*50)
print("📈 КОРРЕЛЯЦИЯ ЧИСЛОВЫХ ПРИЗНАКОВ (TRAIN)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    # Находим числовые колонки
    numeric_cols_train = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()

    if len(numeric_cols_train) == 0:
        print("\nℹ️ Нет числовых колонок для анализа корреляции")
    elif len(numeric_cols_train) == 1:
        print(f"\nℹ️ Только одна числовая колонка: {numeric_cols_train[0]}")
        print("   Корреляцию посчитать невозможно")
    else:
        corr_matrix = X_train[numeric_cols_train].corr()

        # Поиск сильных корреляций (>0.7)
        high_corr_pairs = []
        for i in range(len(corr_matrix.columns)):
            for j in range(i+1, len(corr_matrix.columns)):
                corr_value = corr_matrix.iloc[i, j]
                if abs(corr_value) > 0.7:
                    high_corr_pairs.append((corr_matrix.columns[i], corr_matrix.columns[j], corr_value))

        if high_corr_pairs:
            print("\n⚠️ Обнаружены сильные корреляции (|r| > 0.7):\n")
            for col1, col2, corr in high_corr_pairs:
                # Определяем цвет по силе корреляции
                if abs(corr) > 0.9:
                    level = "🔴"
                elif abs(corr) > 0.8:
                    level = "🟠"
                elif abs(corr) > 0.7:
                    level = "🟡"
                else:
                    level = "🟢"

                direction = "→" if corr > 0 else "←"
                print(f"   {level} {col1} {direction} {col2}: {corr:+.2f}")

            print("\n💡 Рекомендации:")
            print("   • Для линейных моделей (LR, Ridge): удалите один из пары")
            print("   • Для tree-based (RF, XGBoost): можно оставить оба")
            print("   • Рассмотрите PCA для уменьшения размерности")
        else:
            print("\n✅ Сильных корреляций (|r| > 0.7) не обнаружено")

        # Топ-3 корреляции с цветовой индикацией
        print("\n📊 Топ-5 по абсолютной величине:\n")

        corr_pairs = []
        for i in range(len(corr_matrix.columns)):
            for j in range(i+1, len(corr_matrix.columns)):
                corr_pairs.append((
                    corr_matrix.columns[i],
                    corr_matrix.columns[j],
                    corr_matrix.iloc[i, j]
                ))

        corr_pairs.sort(key=lambda x: abs(x[2]), reverse=True)

        print(f"   {'':<3} {'Пара признаков':<40} {'Корреляция':>12}")
        print("   " + "-" * 58)

        for i, (col1, col2, corr) in enumerate(corr_pairs[:5], 1):
            abs_corr = abs(corr)

            # Определяем цвет по силе корреляции
            if abs_corr > 0.7:
                level = "🔴"
            elif abs_corr > 0.5:
                level = "🟠"
            elif abs_corr > 0.3:
                level = "🟡"
            else:
                level = "🟢"

            direction = "→" if corr > 0 else "←"
            pair_str = f"{col1} {direction} {col2}"
            print(f"   {level} {pair_str:<38} {corr:>+10.2f}")

        # Сводка по уровням корреляции
        print("\n💡 Легенда:")
        print("   🔴 Сильная (|r| > 0.7)  — высокая мультиколлинеарность")
        print("   🟠 Средняя (|r| > 0.5)  — умеренная связь")
        print("   🟡 Слабая (|r| > 0.3)   — заметная связь")
        print("   🟢 Очень слабая (|r| ≤ 0.3) — практически нет связи")

print("\n" + "="*50)
print("✓ Анализ корреляции завершён")
print("="*50 + "\n")

==================================================
📈 КОРРЕЛЯЦИЯ ЧИСЛОВЫХ ПРИЗНАКОВ (TRAIN)
==================================================

✅ Сильных корреляций (|r| > 0.7) не обнаружено

📊 Топ-5 по абсолютной величине:

       Пара признаков                             Корреляция
   ----------------------------------------------------------
   🟡 age → bmi                                   +0.32
   🟢 age → hypertension                          +0.28
   🟢 age → heart_disease                         +0.26
   🟢 age → avg_glucose_level                     +0.22
   🟢 hypertension → avg_glucose_level            +0.20

💡 Легенда:
   🔴 Сильная (|r| > 0.7)  — высокая мультиколлинеарность
   🟠 Средняя (|r| > 0.5)  — умеренная связь
   🟡 Слабая (|r| > 0.3)   — заметная связь
   🟢 Очень слабая (|r| ≤ 0.3) — практически нет связи

==================================================
✓ Анализ корреляции завершён
==================================================

In [ ]:
# 6.3 ПРОВЕРКА НА МУЛЬТИКОЛЛИНЕАРНОСТЬ (VIF)

print("\n" + "="*50)
print("🔗 МУЛЬТИКОЛЛИНЕАРНОСТЬ (VIF)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    numeric_cols_train = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()

    if len(numeric_cols_train) <= 1:
        print(f"\nℹ️ Недостаточно числовых колонок для VIF (нужно ≥2)")
        print(f"   Найдено: {len(numeric_cols_train)}")
    else:
        # Проверка пропусков
        null_counts = X_train[numeric_cols_train].isnull().sum()
        cols_with_nulls = null_counts[null_counts > 0].index.tolist()

        if cols_with_nulls:
            print(f"\n❌ Невозможно рассчитать VIF: обнаружены пропуски")
            print(f"   Колонки с пропусками: {cols_with_nulls}")
            print(f"\n💡 Сначала обработайте пропуски в блоке 3.4")
        else:
            print(f"\n✅ Данные готовы: {len(numeric_cols_train)} числовых колонок без пропусков")

            try:
                from statsmodels.stats.outliers_influence import variance_inflation_factor
                from statsmodels.tools.tools import add_constant

                # Подготовка данных
                X_vif = X_train[numeric_cols_train].copy()
                for col in X_vif.columns:
                    if X_vif[col].dtype == 'Int64':
                        X_vif[col] = X_vif[col].astype(float)

                X_vif_const = add_constant(X_vif)

                # Расчёт VIF
                vif_data = []
                for i in range(1, len(X_vif_const.columns)):
                    vif = variance_inflation_factor(X_vif_const.values, i)
                    vif_data.append({
                        "feature": X_vif_const.columns[i],
                        "VIF": round(vif, 2)
                    })

                vif_data.sort(key=lambda x: x["VIF"], reverse=True)

                # Анализ результатов
                high_vif = [v for v in vif_data if v["VIF"] > 10]
                moderate_vif = [v for v in vif_data if 5 < v["VIF"] <= 10]

                print("\n📊 РЕЗУЛЬТАТЫ VIF:\n")

                if high_vif:
                    print("🔴 Высокая мультиколлинеарность (VIF > 10):")
                    for v in high_vif:
                        print(f"   {v['feature']}: VIF = {v['VIF']}")
                    print("\n💡 Рекомендация: удалите признаки с VIF > 10")
                    print("   (начиная с самого высокого, пересчитывая VIF после каждого удаления)")

                if moderate_vif:
                    print("🟡 Умеренная мультиколлинеарность (5 < VIF ≤ 10):")
                    for v in moderate_vif:
                        print(f"   {v['feature']}: VIF = {v['VIF']}")
                    if not high_vif:
                        print("\n💡 Рекомендация: можно оставить, но следите за интерпретацией коэффициентов")

                if not high_vif and not moderate_vif:
                    print("🟢 Мультиколлинеарность в норме (VIF ≤ 5)")

                # Топ-5 VIF
                print("\n📈 Топ-5 VIF:")
                for i, v in enumerate(vif_data[:5], 1):
                    if v["VIF"] > 10:
                        icon = "🔴"
                    elif v["VIF"] > 5:
                        icon = "🟡"
                    else:
                        icon = "🟢"
                    print(f"   {icon} {i}. {v['feature']}: {v['VIF']}")

            except ImportError:
                print("\n⚠️ statsmodels не установлен")
                print("   Выполните: !pip install statsmodels")
            except Exception as e:
                print(f"\n⚠️ Ошибка при расчёте VIF: {e}")

print("\n" + "="*50)
print("✓ Проверка мультиколлинеарности завершена")
print("="*50 + "\n")

==================================================
🔗 МУЛЬТИКОЛЛИНЕАРНОСТЬ (VIF)
==================================================

✅ Данные готовы: 5 числовых колонок без пропусков

📊 РЕЗУЛЬТАТЫ VIF:

🟢 Мультиколлинеарность в норме (VIF ≤ 5)

📈 Топ-5 VIF:
   🟢 1. age: 1.27
   🟢 2. bmi: 1.14
   🟢 3. hypertension: 1.12
   🟢 4. avg_glucose_level: 1.1
   🟢 5. heart_disease: 1.09

==================================================
✓ Проверка мультиколлинеарности завершена
==================================================

In [ ]:
# 6.4 РЕКОМЕНДАЦИИ ПО КОДИРОВАНИЮ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ

print("\n" + "="*50)
print("🏷️ КОДИРОВАНИЕ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    categorical_cols_train = X_train.select_dtypes(include=['category', 'object']).columns.tolist()

    if len(categorical_cols_train) == 0:
        print("\nℹ️ Нет категориальных признаков для анализа")
    else:
        print(f"\n📊 Найдено категориальных признаков: {len(categorical_cols_train)}\n")

        summary = []

        for col in categorical_cols_train:
            unique_count = X_train[col].nunique()
            total_count = len(X_train[col])
            top_cat = X_train[col].value_counts().head(2)
            top1_pct = (top_cat.iloc[0] / total_count) * 100

            # Определяем рекомендацию и уровень
            if unique_count == 2:
                recommendation = "LabelEncoder"
                priority = "🟢"
                priority_desc = "идеально"
            elif unique_count <= 5:
                recommendation = f"OneHotEncoder ({unique_count} колонок)"
                priority = "🟢"
                priority_desc = "отлично"
            elif unique_count <= 10:
                recommendation = f"OneHotEncoder ({unique_count} колонок)"
                priority = "🟡"
                priority_desc = "нормально"
            elif unique_count <= 50:
                recommendation = "TargetEncoder / FrequencyEncoder"
                priority = "🟠"
                priority_desc = "осторожно"
            else:
                recommendation = "TargetEncoder / FeatureHasher"
                priority = "🔴"
                priority_desc = "проблема"

            summary.append({
                'col': col,
                'unique': unique_count,
                'top_cat': top_cat.index[0],
                'top_pct': top1_pct,
                'rec': recommendation,
                'priority': priority,
                'priority_desc': priority_desc
            })

            print(f"   {priority} {col}:")
            print(f"      Уникальных значений: {unique_count}")
            print(f"      Топ: '{top_cat.index[0]}' ({top1_pct:.1f}%)")

            if unique_count == 2:
                print(f"      → LabelEncoder (бинарная)")
            elif unique_count <= 5:
                print(f"      → OneHotEncoder ({unique_count} колонок)")
            elif unique_count <= 10:
                print(f"      → OneHotEncoder ({unique_count} колонок)")
                if top1_pct > 90:
                    print(f"      ⚠️ Доминирующая категория ({top1_pct:.1f}%)")
            elif unique_count <= 50:
                print(f"      → TargetEncoder / FrequencyEncoder")
            else:
                print(f"      → TargetEncoder / FeatureHasher")
                print(f"      ⚠️ Высокая кардинальность ({unique_count} значений)")
            print()

        # Сводная таблица с легендой
        print("   " + "-"*70)
        print("\n📋 СВОДКА ПО ВСЕМ КАТЕГОРИАЛЬНЫМ ПРИЗНАКАМ:\n")
        print(f"   {'':<3} {'Признак':<18} {'Уник':>6} {'Топ %':>7} {'Рекомендация':<32}")
        print("   " + "-"*70)

        for s in summary:
            print(f"   {s['priority']} {s['col']:<15} {s['unique']:>6} {s['top_pct']:>6.1f}% {s['rec']:<32}")

        # Градация
        print("\n   " + "-"*70)
        print("\n📖 ГРАДАЦИЯ:")
        print("   🟢 Зелёный  → низкая кардинальность (≤5), идеально для OneHotEncoder")
        print("   🟡 Жёлтый   → средняя кардинальность (6-10), OneHotEncoder допустим")
        print("   🟠 Оранжевый → высокая кардинальность (11-50), нужен TargetEncoder")
        print("   🔴 Красный  → очень высокая кардинальность (>50), требуется специальная обработка")

        # Общие рекомендации
        print("\n💡 ОБЩИЕ РЕКОМЕНДАЦИИ:\n")
        print("   • Бинарные (2 значения) → LabelEncoder (0/1)")
        print("   • Низкокардинальные (≤10) → OneHotEncoder (drop='first')")
        print("   • Среднекардинальные (11-50) → TargetEncoder или FrequencyEncoder")
        print("   • Высококардинальные (>50) → TargetEncoder или FeatureHasher")

        print("\n📌 ПО ТИПУ МОДЕЛИ:")
        print("   • Линейные модели → OneHotEncoder или TargetEncoder")
        print("   • Деревья (RF, XGBoost) → OrdinalEncoder или LabelEncoder")
        print("   • CatBoost → встроенная обработка категорий (не требует кодирования)")

        print("\n⚠️ ВАЖНО:")
        print("   • Для порядковых признаков используйте OrdinalEncoder с указанием порядка")
        print("   • При OneHotEncoding используйте drop='first' (избежать дамми-ловушки)")
        print("   • TargetEncoder считайте ТОЛЬКО на train, потом применяйте к val/test")

print("\n" + "="*50)
print("✓ Анализ категориальных признаков завершён")
print("="*50 + "\n")

==================================================
🏷️ КОДИРОВАНИЕ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ
==================================================

📊 Найдено категориальных признаков: 5

   🟢 gender:
      Уникальных значений: 2
      Топ: 'female' (59.4%)
      → LabelEncoder (бинарная)

   🟢 ever_married:
      Уникальных значений: 2
      Топ: 'yes' (65.9%)
      → LabelEncoder (бинарная)

   🟢 work_type:
      Уникальных значений: 5
      Топ: 'private' (57.2%)
      → OneHotEncoder (5 колонок)

   🟢 residence_type:
      Уникальных значений: 2
      Топ: 'urban' (50.4%)
      → LabelEncoder (бинарная)

   🟢 smoking_status:
      Уникальных значений: 4
      Топ: 'never_smoked' (39.1%)
      → OneHotEncoder (4 колонок)

   ----------------------------------------------------------------------

📋 СВОДКА ПО ВСЕМ КАТЕГОРИАЛЬНЫМ ПРИЗНАКАМ:

       Признак              Уник   Топ % Рекомендация
   ----------------------------------------------------------------------
   🟢 gender               2   59.4% LabelEncoder
   🟢 ever_married         2   65.9% LabelEncoder
   🟢 work_type            5   57.2% OneHotEncoder (5 колонок)
   🟢 residence_type       2   50.4% LabelEncoder
   🟢 smoking_status       4   39.1% OneHotEncoder (4 колонок)

   ----------------------------------------------------------------------

📖 ГРАДАЦИЯ:
   🟢 Зелёный  → низкая кардинальность (≤5), идеально для OneHotEncoder
   🟡 Жёлтый   → средняя кардинальность (6-10), OneHotEncoder допустим
   🟠 Оранжевый → высокая кардинальность (11-50), нужен TargetEncoder
   🔴 Красный  → очень высокая кардинальность (>50), требуется специальная обработка

💡 ОБЩИЕ РЕКОМЕНДАЦИИ:

   • Бинарные (2 значения) → LabelEncoder (0/1)
   • Низкокардинальные (≤10) → OneHotEncoder (drop='first')
   • Среднекардинальные (11-50) → TargetEncoder или FrequencyEncoder
   • Высококардинальные (>50) → TargetEncoder или FeatureHasher

📌 ПО ТИПУ МОДЕЛИ:
   • Линейные модели → OneHotEncoder или TargetEncoder
   • Деревья (RF, XGBoost) → OrdinalEncoder или LabelEncoder
   • CatBoost → встроенная обработка категорий (не требует кодирования)

⚠️ ВАЖНО:
   • Для порядковых признаков используйте OrdinalEncoder с указанием порядка
   • При OneHotEncoding используйте drop='first' (избежать дамми-ловушки)
   • TargetEncoder считайте ТОЛЬКО на train, потом применяйте к val/test

==================================================
✓ Анализ категориальных признаков завершён
==================================================

In [ ]:
# 6.5 ПРОВЕРКА НА КОНСТАНТНЫЕ И НИЗКОВАРИАТИВНЫЕ ПРИЗНАКИ

print("\n" + "="*50)
print("🔒 ПРОВЕРКА НА БЕСПОЛЕЗНЫЕ ПРИЗНАКИ (TRAIN)")
print("="*50)

if not is_train_ready(X_train):
    print("⚠️ Пропускаем: X_train не определён")
else:
    constant_cols = []
    near_constant_cols = []
    low_variance_cols = []

    for col in X_train.columns:
        unique_count = X_train[col].nunique()

        if unique_count == 1:
            constant_cols.append(col)
        elif unique_count == 2:
            value_counts = X_train[col].value_counts(normalize=True)
            max_ratio = value_counts.max()
            if max_ratio > 0.99:
                near_constant_cols.append((col, max_ratio))
            elif max_ratio > 0.95:
                low_variance_cols.append((col, unique_count, max_ratio))
        elif unique_count <= 3:
            value_counts = X_train[col].value_counts(normalize=True)
            max_ratio = value_counts.max()
            if max_ratio > 0.95:
                low_variance_cols.append((col, unique_count, max_ratio))

    # Константные колонки
    if constant_cols:
        print("\n🔴 КОНСТАНТНЫЕ КОЛОНКИ (только одно значение):\n")
        for col in constant_cols:
            value = X_train[col].iloc[0]
            print(f"   • {col}: '{value}'")

        print("\n💡 Рекомендация: УДАЛИТЬ (не несут информации)")
        print("\n📌 Добавьте в блок 1.3 (Настройки проекта):")
        print(f"   columns_to_drop = {constant_cols}")
    else:
        print("\n🟢 Константных колонок нет")

    # Почти константные (>99%)
    if near_constant_cols:
        print("\n🟡 ПОЧТИ КОНСТАНТНЫЕ (>99% одно значение):\n")
        for col, ratio in near_constant_cols:
            print(f"   • {col}: {ratio*100:.1f}% — одно значение")

        print("\n💡 Рекомендация: рассмотреть удаление (минимум информации)")

    # Низковариативные (>95%)
    if low_variance_cols:
        print("\n🟠 НИЗКОВАРИАТИВНЫЕ (>95% одно значение):\n")
        for col, unique_count, max_ratio in low_variance_cols:
            print(f"   • {col}: {unique_count} значений, {max_ratio*100:.1f}% доминирует")

        print("\n💡 Рекомендация: можно удалить, если не критичны для бизнес-логики")

    # Сводка
    print("\n" + "-"*50)
    print("\n📊 СВОДКА:")
    print(f"   Всего признаков: {len(X_train.columns)}")
    print(f"   🔴 Константных: {len(constant_cols)}")
    print(f"   🟡 Почти константных (>99%): {len(near_constant_cols)}")
    print(f"   🟠 Низковариативных (>95%): {len(low_variance_cols)}")
    print(f"   🟢 Нормальных: {len(X_train.columns) - len(constant_cols) - len(near_constant_cols) - len(low_variance_cols)}")

    if constant_cols or near_constant_cols:
        print("\n⚠️ Рекомендуется перезапустить пайплайн после удаления константных признаков")

print("\n" + "="*50)
print("✓ Проверка завершена")
print("="*50 + "\n")

==================================================
🔒 ПРОВЕРКА НА БЕСПОЛЕЗНЫЕ ПРИЗНАКИ (TRAIN)
==================================================

🟢 Константных колонок нет

🟠 НИЗКОВАРИАТИВНЫЕ (>95% одно значение):

   • heart_disease: 2 значений, 95.0% доминирует

💡 Рекомендация: можно удалить, если не критичны для бизнес-логики

--------------------------------------------------

📊 СВОДКА:
   Всего признаков: 10
   🔴 Константных: 0
   🟡 Почти константных (>99%): 0
   🟠 Низковариативных (>95%): 1
   🟢 Нормальных: 9

==================================================
✓ Проверка завершена
==================================================

# БЛОК 7. Сохранение и итоги

In [ ]:
# 7.1 СОХРАНЕНИЕ ВЫБОРОК И МЕТАДАННЫХ

print("\n" + "="*50)
print("💾 СОХРАНЕНИЕ ВЫБОРОК И МЕТАДАННЫХ")
print("="*50)

if not is_train_ready(X_train):
    print("\n⚠️ Пропускаем: выборки не созданы")
else:
    # --------------------------------------------
    # Сохранение признаков (X)
    # --------------------------------------------
    print("\n--- Сохранение признаков (X) ---")

    X_train_path = os.path.join(SPLITS_PATH, 'X_train.csv')
    X_val_path = os.path.join(SPLITS_PATH, 'X_val.csv')
    X_test_path = os.path.join(SPLITS_PATH, 'X_test.csv')

    X_train.to_csv(X_train_path, index=False)
    X_val.to_csv(X_val_path, index=False)
    X_test.to_csv(X_test_path, index=False)

    print(f"   ✓ X_train.csv ({len(X_train)} строк, {len(X_train.columns)} признаков)")
    print(f"   ✓ X_val.csv ({len(X_val)} строк)")
    print(f"   ✓ X_test.csv ({len(X_test)} строк)")

    # --------------------------------------------
    # Сохранение целевой переменной (y)
    # --------------------------------------------
    print("\n--- Сохранение целевой переменной (y) ---")

    y_train_path = os.path.join(SPLITS_PATH, 'y_train.csv')
    y_val_path = os.path.join(SPLITS_PATH, 'y_val.csv')
    y_test_path = os.path.join(SPLITS_PATH, 'y_test.csv')

    y_train.to_csv(y_train_path, index=False, header=True)
    y_val.to_csv(y_val_path, index=False, header=True)
    y_test.to_csv(y_test_path, index=False, header=True)

    print(f"   ✓ y_train.csv ({len(y_train)} значений)")
    print(f"   ✓ y_val.csv ({len(y_val)} значений)")
    print(f"   ✓ y_test.csv ({len(y_test)} значений)")

    # --------------------------------------------
    # Проверка сохранённых файлов
    # --------------------------------------------
    print("\n--- Проверка сохранённых файлов ---")

    expected_files = ['X_train.csv', 'X_val.csv', 'X_test.csv',
                      'y_train.csv', 'y_val.csv', 'y_test.csv']

    saved_files = os.listdir(SPLITS_PATH)
    missing_files = [f for f in expected_files if f not in saved_files]

    if missing_files:
        print(f"   ⚠️ Не найдены файлы: {missing_files}")
    else:
        print(f"   ✓ Все 6 файлов сохранены в: {SPLITS_PATH}")

    # --------------------------------------------
    # Определение типа задачи
    # --------------------------------------------
    if FORCE_TASK_TYPE:
        task_type = FORCE_TASK_TYPE
    else:
        if y.dtype in ['int64', 'Int64', 'float64'] and y.nunique() > 10:
            task_type = "regression"
        else:
            task_type = "classification"

    # --------------------------------------------
    # Сбор версий пакетов
    # --------------------------------------------
    package_versions = {
        "python": sys.version.split()[0],
        "pandas": pd.__version__,
        "numpy": np.__version__,
        "scikit-learn": sklearn.__version__
    }

    try:
        import statsmodels
        package_versions["statsmodels"] = statsmodels.__version__
    except ImportError:
        pass

    # --------------------------------------------
    # Подготовка метаданных
    # --------------------------------------------
    metadata = {
        "project_name": str(PROJECT_NAME),
        "target_column": str(TARGET_COLUMN),
        "task_type": task_type,
        "feature_names": X_train.columns.tolist(),
        "feature_count": len(X_train.columns),
        "train_size": len(X_train),
        "val_size": len(X_val),
        "test_size": len(X_test),
        "total_size": len(X),
        "split_ratio": {
            "train": SPLIT_TRAIN_SIZE,
            "val": SPLIT_VAL_SIZE,
            "test": SPLIT_TEST_SIZE
        },
        "random_state": RANDOM_STATE,
        "date_processed": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "has_missing_values": bool(df.isnull().sum().sum() > 0),
        "package_versions": package_versions
    }

    # Информация о классах (для классификации)
    if task_type == "classification":
        metadata["classes"] = [str(cls) for cls in sorted(y.unique().tolist())]
        metadata["class_count"] = y.nunique()
        train_dist = y_train.value_counts().to_dict()
        metadata["train_class_distribution"] = {str(k): int(v) for k, v in train_dist.items()}
    else:
        metadata["target_min"] = float(y.min()) if not pd.isna(y.min()) else None
        metadata["target_max"] = float(y.max()) if not pd.isna(y.max()) else None
        metadata["target_mean"] = float(y.mean()) if not pd.isna(y.mean()) else None

    # --------------------------------------------
    # Сохранение метаданных в JSON
    # --------------------------------------------
    print("\n--- Сохранение метаданных ---")

    def convert_to_serializable(obj):
        """Рекурсивно конвертирует numpy-типы в Python-типы"""
        if isinstance(obj, (np.integer, np.int64, np.int32)):
            return int(obj)
        elif isinstance(obj, (np.floating, np.float64, np.float32)):
            return float(obj)
        elif isinstance(obj, np.bool_):
            return bool(obj)
        elif isinstance(obj, pd.Timestamp):
            return str(obj)
        elif isinstance(obj, (list, tuple)):
            return [convert_to_serializable(item) for item in obj]
        elif isinstance(obj, dict):
            return {key: convert_to_serializable(value) for key, value in obj.items()}
        else:
            return obj

    metadata_serializable = convert_to_serializable(metadata)

    metadata_path = os.path.join(PROJECT_PATH, 'metadata.json')
    with open(metadata_path, 'w', encoding='utf-8') as f:
        json.dump(metadata_serializable, f, ensure_ascii=False, indent=2)

    print(f"   ✓ metadata.json сохранён")

    # --------------------------------------------
    # Краткая информация
    # --------------------------------------------
    print("\n" + "="*50)
    print("📊 ИТОГОВАЯ ИНФОРМАЦИЯ")
    print("="*50)
    print(f"\n   Проект: {PROJECT_NAME}")
    print(f"   Целевая переменная: {TARGET_COLUMN}")
    print(f"   Тип задачи: {task_type}")
    print(f"   Признаков: {len(X_train.columns)}")
    print(f"   Всего данных: {len(X)} строк")
    print(f"   Train: {len(X_train)} ({len(X_train)/len(X)*100:.1f}%)")
    print(f"   Val:   {len(X_val)} ({len(X_val)/len(X)*100:.1f}%)")
    print(f"   Test:  {len(X_test)} ({len(X_test)/len(X)*100:.1f}%)")

    if task_type == "classification":
        print(f"\n   🎯 Классы целевой переменной '{TARGET_COLUMN}':")
        for cls in sorted(y.unique()):
            cls_name = str(cls)
            train_count = (y_train == cls).sum()
            train_pct = train_count / len(y_train) * 100
            print(f"      • {cls_name}: {train_count} в train ({train_pct:.1f}%)")

    print(f"\n   📦 Версии пакетов:")
    for pkg, ver in package_versions.items():
        print(f"      • {pkg}: {ver}")

print("\n" + "="*50)
print("✓ Сохранение завершено")
print("="*50 + "\n")

==================================================
💾 СОХРАНЕНИЕ ВЫБОРОК И МЕТАДАННЫХ
==================================================

--- Сохранение признаков (X) ---
   ✓ X_train.csv (2911 строк, 10 признаков)
   ✓ X_val.csv (971 строк)
   ✓ X_test.csv (971 строк)

--- Сохранение целевой переменной (y) ---
   ✓ y_train.csv (2911 значений)
   ✓ y_val.csv (971 значений)
   ✓ y_test.csv (971 значений)

--- Проверка сохранённых файлов ---
   ✓ Все 6 файлов сохранены в: /content/drive/MyDrive/ml_learning/datasets/stroke_test/splits

--- Сохранение метаданных ---
   ✓ metadata.json сохранён

==================================================
📊 ИТОГОВАЯ ИНФОРМАЦИЯ
==================================================

   Проект: stroke_test
   Целевая переменная: stroke
   Тип задачи: classification
   Признаков: 10
   Всего данных: 4853 строк
   Train: 2911 (60.0%)
   Val:   971 (20.0%)
   Test:  971 (20.0%)

   🎯 Классы целевой переменной 'stroke':
      • 0: 2786 в train (95.7%)
      • 1: 125 в train (4.3%)

   📦 Версии пакетов:
      • python: 3.12.13
      • pandas: 2.2.2
      • numpy: 2.0.2
      • scikit-learn: 1.6.1
      • statsmodels: 0.14.6

==================================================
✓ Сохранение завершено
==================================================

In [ ]:
# 7.2 ИТОГИ ВЫПОЛНЕНИЯ

print("\n" + "="*50)
print("🎉 ИТОГИ ВЫПОЛНЕНИЯ")
print("="*50)

if not is_train_ready(X_train):
    print("\n⚠️ ВЫБОРКИ НЕ СОЗДАНЫ")
    print("   Причина: TARGET_COLUMN не указан или не найден")
    print("\n💡 Для завершения предобработки:")
    print("   1. Укажите TARGET_COLUMN в блоке 1.3")
    print("   2. Перезапустите блоки 5.1-7.1")
else:
    # --------------------------------------------
    # Выполненные шаги
    # --------------------------------------------
    print("\n📋 ВЫПОЛНЕННЫЕ ШАГИ:")
    print("   ✓ Часть 1: Настройка и загрузка")
    print("   ✓ Часть 2: Первичный осмотр данных")
    print("   ✓ Часть 3: Предобработка данных")
    print("   ✓ Часть 4: Очистка и финализация")
    print("   ✓ Часть 5: Разбиение данных")
    print("   ✓ Часть 6: Анализ train выборки")
    print("   ✓ Часть 7: Сохранение результатов")

    # --------------------------------------------
    # Итоговая статистика
    # --------------------------------------------
    print("\n📊 ИТОГОВАЯ СТАТИСТИКА:")
    print(f"\n   Размеры выборок:")
    print(f"   • Train: {len(X_train)} строк, {len(X_train.columns)} признаков")
    print(f"   • Val:   {len(X_val)} строк, {len(X_val.columns)} признаков")
    print(f"   • Test:  {len(X_test)} строк, {len(X_test.columns)} признаков")

    # Типы колонок
    numeric_cols = X_train.select_dtypes(include=['int64', 'Int64', 'float64']).columns.tolist()
    categorical_cols = X_train.select_dtypes(include=['category', 'object']).columns.tolist()

    print(f"\n   Состав признаков:")
    print(f"   • Числовые: {len(numeric_cols)}")
    print(f"   • Категориальные: {len(categorical_cols)}")

    # Целевая переменная
    print(f"\n   Целевая переменная: {TARGET_COLUMN}")

    if FORCE_TASK_TYPE:
        task_type = FORCE_TASK_TYPE
    else:
        task_type = "classification" if y.nunique() <= 10 else "regression"

    if task_type == "classification":
        print(f"   • Тип: классификация")
        print(f"   • Классы: {sorted(y.unique().tolist())}")
        print(f"   • Распределение в train:")
        for cls, count in y_train.value_counts().items():
            pct = count / len(y_train) * 100
            print(f"     - {cls}: {count} ({pct:.1f}%)")
    else:
        print(f"   • Тип: регрессия")
        print(f"   • Диапазон: {y.min():.2f} — {y.max():.2f}")

    # Пропуски
    total_nulls = df.isnull().sum().sum()
    if total_nulls > 0:
        print(f"\n   ⚠️ Пропуски: {total_nulls} всего")
    else:
        print(f"\n   ✅ Пропусков нет")

    # --------------------------------------------
    # Результаты анализа
    # --------------------------------------------
    print("\n🔍 РЕЗУЛЬТАТЫ АНАЛИЗА (TRAIN):")

    # Выбросы — проверяем через поиск по globals()
    outlier_cols = []
    if 'numeric_cols_train' in globals():
        for col in numeric_cols:
            Q1 = X_train[col].quantile(0.25)
            Q3 = X_train[col].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - OUTLIER_IQR_COEFF * IQR
            upper = Q3 + OUTLIER_IQR_COEFF * IQR
            outliers = X_train[(X_train[col] < lower) | (X_train[col] > upper)]
            if len(outliers) > 0:
                outlier_cols.append((col, len(outliers), len(outliers)/len(X_train)*100))

    if outlier_cols:
        print(f"\n   📊 Выбросы (IQR={OUTLIER_IQR_COEFF}):")
        for col, count, pct in outlier_cols[:5]:
            print(f"     • {col}: {count} ({pct:.1f}%)")
    else:
        print(f"\n   ✅ Выбросов не обнаружено")

    # Корреляции
    if 'high_corr_pairs' in globals() and high_corr_pairs:
        print(f"\n   📈 Сильные корреляции (>0.7):")
        for col1, col2, corr in high_corr_pairs[:3]:
            print(f"     • {col1} ↔ {col2}: {corr:.2f}")

    # VIF
    if 'high_vif' in globals() and high_vif:
        print(f"\n   ⚠️ Высокий VIF (>10):")
        for v in high_vif[:3]:
            print(f"     • {v['feature']}: {v['VIF']}")

    # Константные колонки
    constant_cols = []
    for col in X_train.columns:
        if X_train[col].nunique() == 1:
            constant_cols.append(col)

    if constant_cols:
        print(f"\n   🔴 Константные колонки:")
        for col in constant_cols:
            print(f"     • {col}")

    # --------------------------------------------
    # Пути к результатам
    # --------------------------------------------
    print("\n📂 ПУТИ К РЕЗУЛЬТАТАМ:")
    print(f"   • Проект: {PROJECT_PATH}")
    print(f"   • Чекпоинты: {CHECKPOINT_PATH}")
    print(f"   • Сплиты: {SPLITS_PATH}")
    print(f"   • Отчёты: {REPORTS_PATH}")
    print(f"   • Метаданные: {PROJECT_PATH}/metadata.json")

    # --------------------------------------------
    # Рекомендации
    # --------------------------------------------
    print("\n💡 РЕКОМЕНДАЦИИ ДЛЯ СЛЕДУЮЩЕГО ЭТАПА:")

    recommendations = []

    if categorical_cols:
        recommendations.append("• Закодировать категориальные признаки (OneHotEncoder / TargetEncoder)")
    if numeric_cols:
        recommendations.append("• Масштабировать числовые признаки (StandardScaler / RobustScaler)")
    if total_nulls > 0:
        recommendations.append("• Обработать оставшиеся пропуски")
    if 'high_corr_pairs' in globals() and high_corr_pairs:
        recommendations.append("• Рассмотреть удаление сильно коррелирующих признаков")
    if 'high_vif' in globals() and high_vif:
        recommendations.append("• Использовать регуляризацию (Ridge, Lasso) из-за мультиколлинеарности")
    if constant_cols:
        recommendations.append("• Удалить константные колонки (добавить в columns_to_drop в блоке 1.3)")

    for rec in recommendations:
        print(f"   {rec}")

    if not recommendations:
        print("   ✅ Данные готовы к обучению модели!")

    # --------------------------------------------
    # Сохранение итогового отчёта
    # --------------------------------------------
    print("\n--- Сохранение итогового отчёта ---")

    report_lines = []
    report_lines.append("=" * 60)
    report_lines.append("ИТОГОВЫЙ ОТЧЁТ ПО ПРЕДОБРАБОТКЕ")
    report_lines.append("=" * 60)
    report_lines.append(f"Проект: {PROJECT_NAME}")
    report_lines.append(f"Дата: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append("")
    report_lines.append(f"Размеры: Train={len(X_train)}, Val={len(X_val)}, Test={len(X_test)}")
    report_lines.append(f"Признаки: {len(X_train.columns)} (числовых: {len(numeric_cols)}, категориальных: {len(categorical_cols)})")
    report_lines.append(f"Цель: {TARGET_COLUMN}, тип: {task_type}")
    report_lines.append("")

    if recommendations:
        report_lines.append("Рекомендации:")
        for rec in recommendations:
            report_lines.append(f"  {rec}")

    report_lines.append("")
    report_lines.append("=" * 60)

    report_path = os.path.join(REPORTS_PATH, 'final_report.txt')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report_lines))

    print(f"   ✓ Итоговый отчёт сохранён: {report_path}")

    print("\n" + "="*50)
    print("✅ ПРЕДОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
    print("="*50 + "\n")

==================================================
🎉 ИТОГИ ВЫПОЛНЕНИЯ
==================================================

📋 ВЫПОЛНЕННЫЕ ШАГИ:
   ✓ Часть 1: Настройка и загрузка
   ✓ Часть 2: Первичный осмотр данных
   ✓ Часть 3: Предобработка данных
   ✓ Часть 4: Очистка и финализация
   ✓ Часть 5: Разбиение данных
   ✓ Часть 6: Анализ train выборки
   ✓ Часть 7: Сохранение результатов

📊 ИТОГОВАЯ СТАТИСТИКА:

   Размеры выборок:
   • Train: 2911 строк, 10 признаков
   • Val:   971 строк, 10 признаков
   • Test:  971 строк, 10 признаков

   Состав признаков:
   • Числовые: 5
   • Категориальные: 5

   Целевая переменная: stroke
   • Тип: классификация
   • Классы: [0, 1]
   • Распределение в train:
     - 0: 2786 (95.7%)
     - 1: 125 (4.3%)

   ✅ Пропусков нет

🔍 РЕЗУЛЬТАТЫ АНАЛИЗА (TRAIN):

   📊 Выбросы (IQR=1.5):
     • hypertension: 278 (9.5%)
     • heart_disease: 145 (5.0%)
     • avg_glucose_level: 347 (11.9%)
     • bmi: 60 (2.1%)

📂 ПУТИ К РЕЗУЛЬТАТАМ:
   • Проект: /content/drive/MyDrive/ml_learning/datasets/stroke_test
   • Чекпоинты: /content/drive/MyDrive/ml_learning/datasets/stroke_test/checkpoints
   • Сплиты: /content/drive/MyDrive/ml_learning/datasets/stroke_test/splits
   • Отчёты: /content/drive/MyDrive/ml_learning/datasets/stroke_test/reports
   • Метаданные: /content/drive/MyDrive/ml_learning/datasets/stroke_test/metadata.json

💡 РЕКОМЕНДАЦИИ ДЛЯ СЛЕДУЮЩЕГО ЭТАПА:
   • Закодировать категориальные признаки (OneHotEncoder / TargetEncoder)
   • Масштабировать числовые признаки (StandardScaler / RobustScaler)

--- Сохранение итогового отчёта ---
   ✓ Итоговый отчёт сохранён: /content/drive/MyDrive/ml_learning/datasets/stroke_test/reports/final_report.txt

==================================================
✅ ПРЕДОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!
==================================================